force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProjectSelectorTest.cls
@isTest
private class ProjectSelectorTest {

	@TestSetup
	static void makeData(){
		DataMaker dataMaker = DataMaker.getInstance();
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
	}

	@isTest
	static void getProjectByIdTest() {
		Project__c testProject = [SELECT Id,Name FROM Project__c WHERE ProjectCode__c ='AA01'];
		Map<Id,Project__c> projectMap = ProjectSelector.getInstance().getProjectById(new Set<Id>{testProject.Id});
		System.assertEquals(testProject, projectMap.get(testProject.Id));
	}

	@isTest
	static void getProjectMapByProjectCodeTest(){
		Project__c testProject = [SELECT Id,Name,ProjectCode__c FROM Project__c WHERE ProjectCode__c ='AA01'];
		Map<String,Project__c> projectMap = ProjectSelector.getInstance().getProjectMapByProjectCode(new Set<String>{testProject.ProjectCode__c});
		System.assertEquals(testProject, projectMap.get(testProject.ProjectCode__c));
	}
}