force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>คำบรรยาย project</description>
    <label>Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>ActiveFrom__c</fullName>
    <description>Promotion นี้จะใช้ได้ตั้งแต่</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>ActiveTo__c</fullName>
    <description>Promotion นี้ี้จะใช้ได้จนถึง</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/AdditionalDetail__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDetail__c</fullName>
    <label>Promotion Detail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>รายละเอียดของ Promotion เพิ่มเติม</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Promotion นี้ยังสามารถใช้งานได้หรือไม่

หากอยู่ในวันที่ระหว่าง Active From และ Active To จะมีค่าเป็น True หากไม่อยู่ในช่วงระหว่างนั้นจะมีค่าเป้น False</description>
    <formula>IF(   ActiveFrom__c    &lt; TODAY()&amp;&amp; (TODAY() &lt;   ActiveTo__c  ), TRUE, FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Project ใด</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/PromotionCost__c.field-meta.xml
<CustomField>
    <fullName>PromotionCost__c</fullName>
    <description>ต้นทุนของ Promotion</description>
    <label>Promotion Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/PromotionMasterKey__c.field-meta.xml
<CustomField>
    <fullName>PromotionMasterKey__c</fullName>
    <formula>Project__r.ProjectCode__c + &apos;_&apos; +  Unit__r.ProductCode</formula>
    <label>Promotion Master Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/PromotionType__c.field-meta.xml
<CustomField>
    <fullName>PromotionType__c</fullName>
    <label>Promotion Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount (ส่วนลด)</fullName>
            </value>
            <value>
                <fullName>Marketing Campaign</fullName>
            </value>
            <value>
                <fullName>Premium (ของแถม)</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Personal Discount (ส่วนลดส่วนตัวของ Sales)</fullName>
            </value>
            <value>
                <fullName>Promotion on Transferred day</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
                <isActive>false</isActive>
                <label>B</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>Promotion on Transferred day (ส่วนลดวันโอน)</fullName>
                <isActive>false</isActive>
                <label>Promotion on Transferred day (ส่วนลดวันโอน)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion ที่ผูกกับ unit</description>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/UnitCode__c.field-meta.xml
<CustomField>
    <fullName>UnitCode__c</fullName>
    <formula>Unit__r.ProductCode</formula>
    <label>Unit Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>คำบรรยาย Unit</description>
    <label>Description</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UnitCode__c.field-meta.xml
<CustomField>
    <fullName>UnitCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>รหัสของ Unit นี้</description>
    <externalId>true</externalId>
    <label>Unit Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PromotionMasterSelector.cls
public with sharing class PromotionMasterSelector {
	public static PromotionMasterSelector instance;
	public static PromotionMasterSelector getInstance() {
		if (instance == null) {
			instance = new PromotionMasterSelector();
		}
		return instance;
	}
	public Map<Id, PromotionMaster__c> getPromotionMasterMapById(Set<Id> promotionMasterIds) {
		return new Map<Id, PromotionMaster__c>(
			[
				SELECT
					Id,
					ActiveFrom__c,
					ActiveTo__c,
					Description__c,
					IsActive__c,
					Project__c,
					PromotionCost__c,
					AdditionalDetail__c,
					PromotionType__c,
					Source__c,
					Unit__c
				FROM PromotionMaster__c
				WHERE Id IN :promotionMasterIds
			]
		);
	}

	public Map<String, List<PromotionMaster__c>> getMarketingPromotionsMapByKey(
		Set<String> projectCodes,
		Set<String> unitCodes
	) {
		Map<String, List<PromotionMaster__c>> marketingPromotionsMapByKey = new Map<String, List<PromotionMaster__c>>();
		List<PromotionMaster__c> promotionMasters = [
			SELECT
				Id,
				ActiveFrom__c,
				ActiveTo__c,
				Description__c,
				IsActive__c,
				Project__c,
				ProjectCode__c,
				PromotionCost__c,
				AdditionalDetail__c,
				PromotionType__c,
				Source__c,
				Unit__c,
				UnitCode__c,
				PromotionMasterKey__c
			FROM PromotionMaster__c
			WHERE
				(ProjectCode__c IN :projectCodes
				OR UnitCode__c IN :unitCodes)
				AND IsActive__c = TRUE
				AND Source__c = 'Marketing'
			ORDER BY CreatedDate ASC
		];
		for (PromotionMaster__c promotionMaster : promotionMasters) {
			String key = promotionMaster.ProjectCode__c;
			if (promotionMaster.UnitCode__c != null) {
				key = key + '_' + promotionMaster.UnitCode__c;
			}
			if (!marketingPromotionsMapByKey.containsKey(key)) {
				marketingPromotionsMapByKey.put(key, new List<PromotionMaster__c>());
			}
			marketingPromotionsMapByKey.get(key).add(promotionMaster);
		}
		return marketingPromotionsMapByKey;
	}
}