force-app/main/default/objects/CustomerVisit__c/CustomerVisit__c.object-meta.xml
<CustomObject>
    <label>Customer Visit</label>
    <nameField>
        <displayFormat>CV-{0000}</displayFormat>
        <label>Customer Visit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Visit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/TriggerActivation__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to configure to acitvatate/deactivate trigger execution</description>
    <label>Trigger Activation</label>
    <pluralLabel>Trigger Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean to check to activate/deactivate Trigger</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomerVisitTriggerHandler.cls
public with sharing class CustomerVisitTriggerHandler {
    public static CustomerVisitTriggerHandler instance;
    public static CustomerVisitTriggerHandler getInstance() {
        if (instance == null) {
            instance = new CustomerVisitTriggerHandler();
        }
        return instance;
    }

    public Boolean isActive = true;
    public List<CustomerVisit__c> newRecords;
    public Map<Id, CustomerVisit__c> oldMap;

    public Boolean isTriggerActivated() {
        if (TriggerActivation__mdt.getInstance('CustomerVisitTrigger') != null) {
            return this.isActive && TriggerActivation__mdt.getInstance('CustomerVisitTrigger').isActive__c;
        }
        return this.isActive;
    }

    public void setParams(List<CustomerVisit__c> newRecords, Map<Id, CustomerVisit__c> oldMap) {
        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }

    public void setBypass() {
        this.isActive = false;
    }

    public void clearBypass() {
        this.isActive = true;
    }

	public void executeAfterInsert(){
		this.updateOpportunityTourAnalysisFromCustomerVisit();
	}

	private void updateOpportunityTourAnalysisFromCustomerVisit(){
		OpportunityService oppService = OpportunityService.getInstance();
		List<Opportunity> opportunitiesList = oppService.stampTourAnalysisFromCustomerVisit(this.newRecords);
		if(!opportunitiesList.isEmpty()) {
			OpportunityTriggerHandler.getInstance().setBypass();
			update opportunitiesList;
			OpportunityTriggerHandler.getInstance().clearBypass();
		}
	}
}