force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/PromotionOpportunity__c.object-meta.xml
<CustomObject>
    <label>Promotion Opportunity</label>
    <nameField>
        <displayFormat>POP-{000000}</displayFormat>
        <label>Promotion Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PromotionOpportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>promotion นี้อยู่ภายใต้ opportunity(โอกาสการขาย) ใด</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Promotion_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/fields/PromotionMaster__c.field-meta.xml
<CustomField>
    <fullName>PromotionMaster__c</fullName>
    <description>Promotion ที่ถูกใช่คือ promotion ใด</description>
    <label>Promotion Master</label>
    <referenceTo>PromotionMaster__c</referenceTo>
    <relationshipLabel>Promotion Opportunities</relationshipLabel>
    <relationshipName>Promotion_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PromotionOpportunitySelector.cls
public with sharing class PromotionOpportunitySelector {
	public static PromotionOpportunitySelector instance;
	public static PromotionOpportunitySelector getInstance() {
		if (instance == null) {
			instance = new PromotionOpportunitySelector();
		}
		return instance;
	}

	public Map<Id, List<PromotionOpportunity__c>> getPromotionOpportunitiesMapByOppId(Set<Id> oppIds) {
		Map<Id, List<PromotionOpportunity__c>> promotionOpportunitiesMapByOppId = new Map<Id, List<PromotionOpportunity__c>>();
		List<PromotionOpportunity__c> promotionOpportunities = [
			SELECT Id, Opportunity__c, PromotionMaster__c
			FROM PromotionOpportunity__c
			WHERE Opportunity__c IN :oppIds
		];
		for (PromotionOpportunity__c promotionOpportunity : promotionOpportunities){
			if (!promotionOpportunitiesMapByOppId.containsKey(promotionOpportunity.Opportunity__c)){
				promotionOpportunitiesMapByOppId.put(promotionOpportunity.Opportunity__c , new List<PromotionOpportunity__c>());
			}
			promotionOpportunitiesMapByOppId.get(promotionOpportunity.Opportunity__c).add(promotionOpportunity);
		}
		return promotionOpportunitiesMapByOppId;
	}
}