force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Term Masters</relationshipLabel>
    <relationshipName>Payment_Term_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentTermSelectorTest.cls
@isTest 
public with sharing class PaymentTermSelectorTest {
	@isTest 
	static void getPaymentTermMasterWithLineItemsMapByIdTest(){
		Test.startTest();
		DataMaker dataMaker = DataMaker.getInstance();
		PaymentTermSelector selector = PaymentTermSelector.getInstance();
		Project__c project = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert project;
		PaymentTermMaster__c paymentTermMaster = dataMaker.craetePaymentTermMaster(project.Id,'TQ Series 5-10-85', 'Series', 'Thai', 25);
		insert paymentTermMaster;
		Map<Id,PaymentTermMaster__c> paymentTermMasterMapById = selector.getPaymentTermMasterWithLineItemsMapById(new Set<Id>{paymentTermMaster.Id});
		System.assertEquals(paymentTermMaster.Id, (new List<Id>(paymentTermMasterMapById.keyset())).get(0));
		Test.stopTest();
	}
}