force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <formula>&quot;On the &quot; &amp; TEXT( PaymentTermMaster__r.DueDate__c ) &amp; &quot;th of Every Month&quot;</formula>
    <label>Due Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/NoofInstallment__c.field-meta.xml
<CustomField>
    <fullName>NoofInstallment__c</fullName>
    <formula>PaymentTermMaster__r.NoofInstallment__c</formula>
    <label>No. of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>ประเภทของงวดชำระ</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>ActiveFrom__c</fullName>
    <description>Displays the start date of the Payment Term Master, indicating when the payment terms become effective.</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>ActiveTo__c</fullName>
    <description>Displays the end date of the Payment Term Master, indicating when the payment terms expire or are no longer valid.</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <inlineHelpText>Date for collecting payments (installment)</inlineHelpText>
    <label>Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/NoofInstallment__c.field-meta.xml
<CustomField>
    <fullName>NoofInstallment__c</fullName>
    <label>No. of Installment</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Term Masters</relationshipLabel>
    <relationshipName>Payment_Term_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>Foreign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Balloon</fullName>
            </value>
            <value>
                <fullName>Bullet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentTermSelector.cls
public with sharing class PaymentTermSelector {
    public static PaymentTermSelector instance;
    public PaymentTermSelector() {
    }
    public static PaymentTermSelector getInstance() {
        if (instance == null) {
            instance = new PaymentTermSelector();
        }
        return instance;
    }

    // get Payment Term Master with Payment Term Line item
    public Map<Id,PaymentTermMaster__c> getPaymentTermMasterWithLineItemsMapById(Set<Id> paymentTermIds) {
        return new Map<Id,PaymentTermMaster__c>([
            SELECT
                Id,
                Name,
                ActiveFrom__c,
                ActiveTo__c,
                DueDate__c,
                NoofInstallment__c,
                Project__c,
                Quota__c,
                Type__c,
                (SELECT Id, Amount__c, Percent__c, Term__c, Order__c, PaymentTermMaster__c,IsAllowedPaymentByGateway__c FROM Payment_Term__r)
            FROM PaymentTermMaster__c
            WHERE Id IN :paymentTermIds
        ]);
    }
}