force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentTermLineItemAdjustmentController.cls
public with sharing class PaymentTermLineItemAdjustmentController {
    @AuraEnabled
    public static PaymentTermMaster__c getPaymentTermMasterWithLineItem(Id paymentTermMasterId) {
        try {
            PaymentTermSelector paymentTermSelector = PaymentTermSelector.getInstance();
            Map<Id, PaymentTermMaster__c> paymentTermMasterMapById = paymentTermSelector.getPaymentTermMasterWithLineItemsMapById(
                new Set<Id>{ paymentTermMasterId }
            );
            return paymentTermMasterMapById.get(paymentTermMasterId);
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static List<PaymentTerm__c> upsertPaymentTermLineItem(String paymentTermLineItemToBeUpsertedJSON) {
        try {
            PaymentTermService service = PaymentTermService.getInstance();
            List<PaymentTerm__c> upsertedPaymentTermLineItems = service.getPaymentTermLineItemFromJSONString(
                paymentTermLineItemToBeUpsertedJSON
            );
            upsert upsertedPaymentTermLineItems;
            return upsertedPaymentTermLineItems;
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
}