force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>ประเภทของงวดชำระ</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentTermService.cls
public with sharing class PaymentTermService {
    public static PaymentTermService instance;
    public PaymentTermService() {
    }
    public static PaymentTermService getInstance() {
        if (instance == null) {
            instance = new PaymentTermService();
        }
        return instance;
    }

    public List<PaymentTerm__c> getPaymentTermLineItemFromJSONString(String paymentTermLineItemJSON) {
        List<PaymentTerm__c> paymentTermLineItemsResult = new List<PaymentTerm__c>();
        List<PaymentTermLineItemWrapper> paymentTermLineItemWrappers = (List<PaymentTermLineItemWrapper>) JSON.deserialize(
            paymentTermLineItemJSON,
            List<PaymentTermLineItemWrapper>.class
        );
        for (PaymentTermLineItemWrapper wrapper : paymentTermLineItemWrappers) {
            PaymentTerm__c paymentTermLineItem = new PaymentTerm__c();
            paymentTermLineItem.Id = wrapper.id;
            paymentTermLineItem.Order__c = wrapper.order;
            paymentTermLineItem.Amount__c = wrapper.amount;
            paymentTermLineItem.Percent__c = wrapper.percent;
            paymentTermLineItem.Term__c = wrapper.term;
            paymentTermLineItem.IsAllowedPaymentByGateway__c = wrapper.isAllowedPayment;
            paymentTermLineItem.PaymentTermMaster__c = wrapper.paymentTermMasterId;
            paymentTermLineItemsResult.add(paymentTermLineItem);
        }
        return paymentTermLineItemsResult;
    }

    public class PaymentTermLineItemWrapper {
        public Integer order;
        public Decimal amount;
        public Decimal percent;
        public String term;
        public String id;
        public Boolean isAllowedPayment;
        public String paymentTermMasterId;
    }
}