force-app/main/default/objects/DocumentTemplateMapping__mdt/DocumentTemplateMapping__mdt.object-meta.xml
<CustomObject>
    <description>สำหรับเป็นตารางในการชี้เอกสารสัญญาและเอกสารแนบท้ายสัญญาที่จะนำมาเป็น Template</description>
    <label>Document Template Mapping</label>
    <pluralLabel>Document Template Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>TH/EN</fullName>
                <default>true</default>
                <label>TH/EN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentGeneratorController.cls
public with sharing class DocumentGeneratorController {
    @AuraEnabled(cacheable=true)
	public static List<ComboboxModel> getLanguages(String templateMappingType) {
		List<DocumentTemplateMapping__mdt> docTemplateMdts = DocumentTemplateMappingMDTSelector.getInstance().getByTemplateAndMappingType(templateMappingType);
		Set<String> languageSet = new Set<String>();
		for (DocumentTemplateMapping__mdt docTemplateMdt : docTemplateMdts) {
			languageSet.add(docTemplateMdt.Language__c);
		}

		List<ComboboxModel> selectedModels = new List<ComboboxModel>();
		for (String language : languageSet) {
			selectedModels.add(
				new ComboboxModel( language, language )
			);
		}
		return selectedModels;
	}
}