force-app/main/default/objects/DocumentTemplateMapping__mdt/DocumentTemplateMapping__mdt.object-meta.xml
<CustomObject>
    <description>สำหรับเป็นตารางในการชี้เอกสารสัญญาและเอกสารแนบท้ายสัญญาที่จะนำมาเป็น Template</description>
    <label>Document Template Mapping</label>
    <pluralLabel>Document Template Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/AdditionalCondition__c.field-meta.xml
<CustomField>
    <fullName>AdditionalCondition__c</fullName>
    <description>เอาไว้ใส่ condition อื่นๆ ที่ต้องการ filter record เพิ่ม</description>
    <label>Additional Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/AdditionalConditionFields__c.field-meta.xml
<CustomField>
    <fullName>AdditionalConditionFields__c</fullName>
    <description>field ที่ใช้สำหรับการ query เพื่อมาใช้ใน Additional Condition ซึ่งจะทำการคั่นด้วย (,)</description>
    <label>Additional Condition Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/DocumentTemplateName__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateName__c</fullName>
    <description>ชื่อเอกสาร Master Template ที่อยู่ใน Object ZipFile__c ที่ record Type เป็น MasterDataType</description>
    <label>Document Template Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/FieldAPINameSaveToExistingFile__c.field-meta.xml
<CustomField>
    <fullName>FieldAPINameSaveToExistingFile__c</fullName>
    <description>field API Name ถ้า field IsSaveToExistingFile มีค่าเป็น true จะต้องใส่ค่า Field API Name ของ Object ที่กด generate เอกสารที่เก็บ existing ContentDocumentId ลงใน field นี้ด้วย</description>
    <label>Field API Name save to existing file</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/IsSaveToExistingFile__c.field-meta.xml
<CustomField>
    <fullName>IsSaveToExistingFile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ต้องการสร้างไฟล์ใหม่ หรือ save ทับไฟล์เดิม ถ้าต้องการสร้างไฟล์ทับไฟล์เดิมให้ set เป็น true</description>
    <label>Is Save To Existing File</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>TH/EN</fullName>
                <default>true</default>
                <label>TH/EN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
                <default>true</default>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>ClientOffer__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/TemplateMappingType__c.field-meta.xml
<CustomField>
    <fullName>TemplateMappingType__c</fullName>
    <label>Template Mapping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Client Offer</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
            <value>
                <fullName>Supplementary Agreement</fullName>
            </value>
            <value>
                <fullName>Addendum</fullName>
                <isActive>false</isActive>
                <label>Addendum</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentTemplateMappingMDTSelector.cls
public with sharing class DocumentTemplateMappingMDTSelector {
	public static DocumentTemplateMappingMDTSelector instance;

	public static DocumentTemplateMappingMDTSelector getInstance() {
		if (instance == null) {
			instance = new DocumentTemplateMappingMDTSelector();
		}
		return instance;
	}

	public List<DocumentTemplateMapping__mdt> getByObjAPIAndLangAndTemplateMappingType(
		String objectApiName,
		String language,
		String templateMappingType
	) {
		return [
			SELECT Id, DocumentTemplateName__c, IsActive__c, Language__c, ObjectName__c , TemplateMappingType__c, 
				IsSaveToExistingFile__c, FieldAPINameSaveToExistingFile__c, AdditionalCondition__c, AdditionalConditionFields__c
			FROM DocumentTemplateMapping__mdt 
			WHERE ObjectName__c =: objectApiName AND 
				Language__c =: language AND
				TemplateMappingType__c =: templateMappingType AND 
				IsActive__c = true
		];
	}

	public List<DocumentTemplateMapping__mdt> getByTemplateAndMappingType(String templateMappingType) {
		return [
			SELECT Language__c
			FROM DocumentTemplateMapping__mdt 
			WHERE TemplateMappingType__c =: templateMappingType
		];
	}
}