force-app/main/default/objects/DocumentTemplateMapping__mdt/DocumentTemplateMapping__mdt.object-meta.xml
<CustomObject>
    <description>สำหรับเป็นตารางในการชี้เอกสารสัญญาและเอกสารแนบท้ายสัญญาที่จะนำมาเป็น Template</description>
    <label>Document Template Mapping</label>
    <pluralLabel>Document Template Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/DocumentTemplateName__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateName__c</fullName>
    <description>ชื่อเอกสาร Master Template ที่อยู่ใน Object ZipFile__c ที่ record Type เป็น MasterDataType</description>
    <label>Document Template Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>TH/EN</fullName>
                <default>true</default>
                <label>TH/EN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
                <default>true</default>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>ClientOffer__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentTemplateMapping__mdt/fields/TemplateMappingType__c.field-meta.xml
<CustomField>
    <fullName>TemplateMappingType__c</fullName>
    <label>Template Mapping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Client Offer</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
            <value>
                <fullName>Supplementary Agreement</fullName>
            </value>
            <value>
                <fullName>Addendum</fullName>
                <isActive>false</isActive>
                <label>Addendum</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/NameFormattingMasterData__c.object-meta.xml
<CustomObject>
    <description>สำหรับเก็บข้อมูล Backend value ต่างๆ เช่น Running Number</description>
    <label>Name Formatting Master Data</label>
    <nameField>
        <displayFormat>NFMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Formatting Master Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NameFormattingMasterData__c/fields/CurrentRunningNumber__c.field-meta.xml
<CustomField>
    <fullName>CurrentRunningNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Current Running number</description>
    <inlineHelpText>Start with 1</inlineHelpText>
    <label>Current Running Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/DocumentTemplateMappingType__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateMappingType__c</fullName>
    <label>Document Template Mapping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Client Offer</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
            <value>
                <fullName>Supplementary Agreement</fullName>
            </value>
            <value>
                <fullName>Payment Summary</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <inlineHelpText>Please add when a type of record is &apos;running number&apos;</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>ClientOffer__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>PaymentReceipt__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/RunningFormat__c.field-meta.xml
<CustomField>
    <fullName>RunningFormat__c</fullName>
    <description>store format of each running key</description>
    <label>Running Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/WordContentMaster__c.object-meta.xml
<CustomObject>
    <description>ใช้สำหรับเก็บ field ในเอกสาร word ตั้งต้น ตอน Upload file ที่ Document Template</description>
    <label>Word Content Master</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Content Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WordContentMaster__c/fields/ConditionToQuery__c.field-meta.xml
<CustomField>
    <fullName>ConditionToQuery__c</fullName>
    <label>Condition To Query</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/DocumentPathName__c.field-meta.xml
<CustomField>
    <fullName>DocumentPathName__c</fullName>
    <label>Document Path Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/FieldToQuery__c.field-meta.xml
<CustomField>
    <fullName>FieldToQuery__c</fullName>
    <label>Field To Query</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/FormatType__c.field-meta.xml
<CustomField>
    <fullName>FormatType__c</fullName>
    <label>Format Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IMAGELOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>LOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>FIELD</fullName>
            </value>
            <value>
                <fullName>IFF</fullName>
            </value>
            <value>
                <fullName>MDT</fullName>
            </value>
            <value>
                <fullName>IMAGEOBJECT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/KeyToReplace__c.field-meta.xml
<CustomField>
    <fullName>KeyToReplace__c</fullName>
    <label>Key To Replace</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/LookupFieldToQuery__c.field-meta.xml
<CustomField>
    <fullName>LookupFieldToQuery__c</fullName>
    <label>Lookup Field To Query</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/ObjectToQuery__c.field-meta.xml
<CustomField>
    <fullName>ObjectToQuery__c</fullName>
    <label>Object To Query</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/SourceField__c.field-meta.xml
<CustomField>
    <fullName>SourceField__c</fullName>
    <description>ใช้สำหรับ Tag Image เพื่อบอกว่า field ที่ไป query record ที่จะไปดึงรูปมา จะเอา record ไหน</description>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/WordContentExternalKey__c.field-meta.xml
<CustomField>
    <fullName>WordContentExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>Word Content External Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/ZipFileMasterId__c.field-meta.xml
<CustomField>
    <fullName>ZipFileMasterId__c</fullName>
    <label>Zip File Master Id</label>
    <referenceTo>ZipFile__c</referenceTo>
    <relationshipLabel>Word Content Master</relationshipLabel>
    <relationshipName>tms_WordContentMaster</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipFile__c/ZipFile__c.object-meta.xml
<CustomObject>
    <label>Zip File</label>
    <nameField>
        <label>ZipFile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZipFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WordContentControllerTest.cls
@isTest
public with sharing class WordContentControllerTest {
    @isTest
    public static void validateRecordIdtoGetDocumentTemplateTest() {
        DataMaker dataMaker = DataMaker.getInstance();

        String sampleContractZipFileName = 'Sample Contract.docx';

        NameFormattingMasterData__c runningNumberFormatDocument = new NameFormattingMasterData__c(
            ObjectName__c = 'Contract',
            RunningFormat__c = '{ContractNumber}_{Account.Name}',
            RunningPurpose__c = 'Document',
            Type__c = 'Format',
            CurrentRunningNumber__c = 1,
            DocumentTemplateMappingType__c = 'Contract'
        );
        insert new List<NameFormattingMasterData__c>{ runningNumberFormatDocument };

        Account account = new Account(Name = 'United Oil & Gas Corp.' , Phone = '0111111111');
        insert account;

        ContractTriggerHandler.getInstance().setBypass();
        Contract contract = new Contract(AccountId = account.Id);
        insert contract;
        ContractTriggerHandler.getInstance().clearBypass();

        Order order = new Order(
            AccountId = account.Id,
            ContractId = contract.Id,
            EffectiveDate = Date.newInstance(2024, 8, 1),
            EndDate = Date.newInstance(2025, 7, 31),
            Status = 'Draft'
        );
        insert order;
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'Image';
        contentVersion.VersionData = Blob.valueOf('Image Data');
        contentVersion.PathOnClient = 'Image.jpg';
        insert contentVersion;
        ContentDocument contentDocument = [
            SELECT Id, Title
            FROM ContentDocument
            WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id)
            LIMIT 1
        ];
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink(
            LinkedEntityId = contract.Id,
            ContentDocumentId = contentDocument.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert contentDocumentLink;

        StaticResource staticResource = [
            SELECT Id, ContentType, BodyLength, Body, Description
            FROM StaticResource
            WHERE Name = 'SampleContractWordRelsXML'
        ];

        ZipFile__c sampleContractZipFile = new ZipFile__c(
            Name = sampleContractZipFileName,
            RecordTypeId = ZipUtility.getInstance().MASTER_DATA_RECORDTYPE
        );
        insert new List<ZipFile__c>{ sampleContractZipFile };
        // WordContentMaster__c testWordContentMaster = dataMaker.createWordContentMester(sampleContractZipFile.Id);
        // testWordContentMaster.FormatType__c = 'IMAGELOOPRELATEDOBJECT';
        // testWordContentMaster.ObjectToQuery__c = 'Contract';
        // testWordContentMaster.FieldToQuery__c = 'FirstName,LastName';
        // testWordContentMaster.ConditionToQuery__c = '';
        // testWordContentMaster.LookupFieldToQuery__c = '';
        WordContentMaster__c testWordContentMaster = new WordContentMaster__c(
            ZipFileMasterId__c = sampleContractZipFile.Id,
            KeyToReplace__c = 'Image.jpg',
            ObjectToQuery__c = 'Main',
            FieldToQuery__c = 'Id,ContractNumber',
			SourceField__c = 'Id',
            ConditionToQuery__c = null,
            LookupFieldToQuery__c = null,
            WordContentExternalKey__c = (sampleContractZipFile.Id + '_1_1'),
            FormatType__c = 'IMAGEOBJECT',
            DocumentPathName__c = 'word/document.xml'
        );
        insert testWordContentMaster;

        String attachmentXml = staticResource.Body.toString().replace('a02dM000004mhJhQAI', sampleContractZipFile.Id);

        Attachment attachSampleContractMaster = new Attachment();
        attachSampleContractMaster.Name = 'word/_rels/document.xml.rels';
        attachSampleContractMaster.Body = Blob.valueOf(attachmentXml);
        attachSampleContractMaster.ParentId = sampleContractZipFile.Id;
        attachSampleContractMaster.ContentType = 'application/msword';
        attachSampleContractMaster.IsPrivate = false;
        attachSampleContractMaster.Description = 'Test';

        insert new List<Attachment>{ attachSampleContractMaster };

        List<DocumentDetailWrapper> results = WordContentController.validateRecordIdtoGetDocumentTemplate(
            contract.Id,
            'TH',
            'Contract',
            ''
        );
        System.assertEquals(1, results.size());

        DocumentDetailWrapper result = results.get(0);

        List<DocumentTemplateMapping__mdt> docTemplateMdts = [
            SELECT Id, DocumentTemplateName__c, IsActive__c, Language__c, ObjectName__c, TemplateMappingType__c
            FROM DocumentTemplateMapping__mdt
            WHERE DocumentTemplateName__c = :sampleContractZipFileName AND IsActive__c = TRUE
        ];
        Map<String, DocumentTemplateMapping__mdt> docTemplateMdtMapByDocTemplateName = new Map<String, DocumentTemplateMapping__mdt>();
        for (DocumentTemplateMapping__mdt docTemplateMdt : docTemplateMdts) {
            docTemplateMdtMapByDocTemplateName.put(docTemplateMdt.DocumentTemplateName__c, docTemplateMdt);
        }

        Zipfile__c zipFileMerge = [
            SELECT Id, Name, RecordTypeId
            FROM ZipFile__c
            WHERE Name = :sampleContractZipFileName AND RecordTypeId = :ZipUtility.getInstance().MERGE_DATA_RECORDTYPE
            LIMIT 1
        ];

        System.assertEquals(contract.Id, result.RecordId);
        System.assertEquals('Contract', result.ObjectAPIName);
        System.assertEquals(zipFileMerge.Id, result.DocumentId);
        System.assertEquals(sampleContractZipFileName, result.DocumentName);
        System.assertEquals('', result.ErrorMessage);
        System.assertNotEquals(null, result.DocumentTemplateMappingMDT);
        System.assertEquals('', result.ParamInput);
        // System.assertEquals('SPA-00100011_United Oil [AMPERSAND] Gas Corp.', result.RunningNumber);
        // System.assertEquals(new List<Integer>{1,3,5}, result.TableRowToRemoves);
    }
}