force-app/main/default/objects/WordContentMaster__c/WordContentMaster__c.object-meta.xml
<CustomObject>
    <description>ใช้สำหรับเก็บ field ในเอกสาร word ตั้งต้น ตอน Upload file ที่ Document Template</description>
    <label>Word Content Master</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Content Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WordContentMaster__c/fields/ConditionToQuery__c.field-meta.xml
<CustomField>
    <fullName>ConditionToQuery__c</fullName>
    <label>Condition To Query</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/DocumentPathName__c.field-meta.xml
<CustomField>
    <fullName>DocumentPathName__c</fullName>
    <label>Document Path Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/FieldToQuery__c.field-meta.xml
<CustomField>
    <fullName>FieldToQuery__c</fullName>
    <label>Field To Query</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/FormatType__c.field-meta.xml
<CustomField>
    <fullName>FormatType__c</fullName>
    <label>Format Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IMAGELOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>LOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>FIELD</fullName>
            </value>
            <value>
                <fullName>IFF</fullName>
            </value>
            <value>
                <fullName>MDT</fullName>
            </value>
            <value>
                <fullName>IMAGEOBJECT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/KeyToReplace__c.field-meta.xml
<CustomField>
    <fullName>KeyToReplace__c</fullName>
    <label>Key To Replace</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/LookupFieldToQuery__c.field-meta.xml
<CustomField>
    <fullName>LookupFieldToQuery__c</fullName>
    <label>Lookup Field To Query</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/ObjectToQuery__c.field-meta.xml
<CustomField>
    <fullName>ObjectToQuery__c</fullName>
    <label>Object To Query</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/SourceField__c.field-meta.xml
<CustomField>
    <fullName>SourceField__c</fullName>
    <description>ใช้สำหรับ Tag Image เพื่อบอกว่า field ที่ไป query record ที่จะไปดึงรูปมา จะเอา record ไหน</description>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/SourceObject__c.field-meta.xml
<CustomField>
    <fullName>SourceObject__c</fullName>
    <description>ใช้สำหรับ Tag Image ว่าจะต้องไปดึงรูปที่ Object ไหน</description>
    <label>Source Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/WordContentExternalKey__c.field-meta.xml
<CustomField>
    <fullName>WordContentExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>Word Content External Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/ZipFileMasterId__c.field-meta.xml
<CustomField>
    <fullName>ZipFileMasterId__c</fullName>
    <label>Zip File Master Id</label>
    <referenceTo>ZipFile__c</referenceTo>
    <relationshipLabel>Word Content Master</relationshipLabel>
    <relationshipName>tms_WordContentMaster</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WordContentMasterSelector.cls
public with sharing class WordContentMasterSelector {
	public static WordContentMasterSelector instance;

	public static WordContentMasterSelector getInstance() {
		if (instance == null) {
			instance = new WordContentMasterSelector();
		}
		return instance;
	}

    public List<WordContentMaster__c> getByZipId(String zipId){
        return [
            SELECT Id, Name, ZipFileMasterId__c, KeyToReplace__c, ObjectToQuery__c, FieldToQuery__c,
                ConditionToQuery__c, LookupFieldToQuery__c, WordContentExternalKey__c, FormatType__c,
                DocumentPathName__c, SourceObject__c, SourceField__c
            FROM WordContentMaster__c 
            WHERE ZipFileMasterId__c =: zipId
        ];
    }

    public List<WordContentMaster__c> getByZipIdSetAndFormatTypeSet(Set<Id> zipIdSet, Set<String> formatTypeSet){
        return [
            SELECT Id, Name, ZipFileMasterId__c, KeyToReplace__c, ObjectToQuery__c, FieldToQuery__c,
                ConditionToQuery__c, LookupFieldToQuery__c, WordContentExternalKey__c, FormatType__c,
                DocumentPathName__c, SourceObject__c, SourceField__c
            FROM WordContentMaster__c 
            WHERE ZipFileMasterId__c IN: zipIdSet
                AND FormatType__c IN: formatTypeSet
        ];
    }
}