force-app/main/default/objects/WordContentMaster__c/WordContentMaster__c.object-meta.xml
<CustomObject>
    <description>ใช้สำหรับเก็บ field ในเอกสาร word ตั้งต้น ตอน Upload file ที่ Document Template</description>
    <label>Word Content Master</label>
    <nameField>
        <displayFormat>WCM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Content Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WordContentMaster__c/fields/FormatType__c.field-meta.xml
<CustomField>
    <fullName>FormatType__c</fullName>
    <label>Format Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IMAGELOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>LOOPRELATEDOBJECT</fullName>
            </value>
            <value>
                <fullName>FIELD</fullName>
            </value>
            <value>
                <fullName>IFF</fullName>
            </value>
            <value>
                <fullName>MDT</fullName>
            </value>
            <value>
                <fullName>IMAGEOBJECT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WordContentMaster__c/fields/ZipFileMasterId__c.field-meta.xml
<CustomField>
    <fullName>ZipFileMasterId__c</fullName>
    <label>Zip File Master Id</label>
    <referenceTo>ZipFile__c</referenceTo>
    <relationshipLabel>Word Content Master</relationshipLabel>
    <relationshipName>tms_WordContentMaster</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipFile__c/ZipFile__c.object-meta.xml
<CustomObject>
    <label>Zip File</label>
    <nameField>
        <label>ZipFile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZipFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WordContentMasterSelectorTest.cls
@isTest
private class WordContentMasterSelectorTest {
    @TestSetup
    static void makeData(){
        DataMaker dataMaker = DataMaker.getInstance();
        ZipFile__c testZipFile = dataMaker.createZipFile('Test ZipFile', ZipUtility.getInstance().MASTER_DATA_RECORDTYPE);
        insert testZipFile;
        WordContentMaster__c testWordContentMaster = dataMaker.createWordContentMester(testZipFile.Id);
        testWordContentMaster.FormatType__c = 'IMAGELOOPRELATEDOBJECT';
        insert testWordContentMaster;
    }
    @isTest
    static void getByZipIdTest() {
        WordContentMaster__c testWordContentMaster = [SELECT Id,ZipFileMasterId__c FROM WordContentMaster__c LIMIT 1];
        List<WordContentMaster__c> results = WordContentMasterSelector.getInstance().getByZipId(testWordContentMaster.ZipFileMasterId__c);
        System.assertEquals(testWordContentMaster.ZipFileMasterId__c, results[0].ZipFileMasterId__c);
    }
    @isTest
    static void getByZipIdSetAndFormatTypeSetTest() {
        WordContentMaster__c testWordContentMaster = [SELECT Id,ZipFileMasterId__c FROM WordContentMaster__c LIMIT 1];
        List<WordContentMaster__c> results = WordContentMasterSelector.getInstance().getByZipIdSetAndFormatTypeSet(new Set<Id>{testWordContentMaster.ZipFileMasterId__c},new Set<String>{'IMAGELOOPRELATEDOBJECT'});
        System.assertEquals(testWordContentMaster.ZipFileMasterId__c, results[0].ZipFileMasterId__c);
    }
    
}