force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnitCode__c.field-meta.xml
<CustomField>
    <fullName>UnitCode__c</fullName>
    <formula>Unit__r.ProductCode</formula>
    <label>Unit Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Project ใด</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion ที่ผูกกับ unit</description>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/UnitCode__c.field-meta.xml
<CustomField>
    <fullName>UnitCode__c</fullName>
    <formula>Unit__r.ProductCode</formula>
    <label>Unit Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Unit Type ใด</description>
    <label>Unit Type</label>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/PromotionOpportunity__c.object-meta.xml
<CustomObject>
    <label>Promotion Opportunity</label>
    <nameField>
        <displayFormat>POP-{000000}</displayFormat>
        <label>Promotion Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PromotionOpportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>promotion นี้อยู่ภายใต้ opportunity(โอกาสการขาย) ใด</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Promotion_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/fields/PromotionMaster__c.field-meta.xml
<CustomField>
    <fullName>PromotionMaster__c</fullName>
    <description>Promotion ที่ถูกใช่คือ promotion ใด</description>
    <label>Promotion Master</label>
    <referenceTo>PromotionMaster__c</referenceTo>
    <relationshipLabel>Promotion Opportunities</relationshipLabel>
    <relationshipName>Promotion_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ชื่อ Floor ที่ Unit นี้อยู่</description>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UnitCode__c.field-meta.xml
<CustomField>
    <fullName>UnitCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>รหัสของ Unit นี้</description>
    <externalId>true</externalId>
    <label>Unit Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่ื่อ Unit Type ของ Unit นี้</description>
    <label>Unit Type</label>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PromotionOpportunityServiceTest.cls
@isTest
public with sharing class PromotionOpportunityServiceTest {
	@TestSetup
	static void makeData() {
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'PJ01', 'CD');
		insert testProject;
		Project__c testProject2 = dataMaker.createProject('Test Project 2', 'PJ02', 'CD');
		insert testProject2;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		Floor__c testFloor2 = dataMaker.createFloor('Test Floor 2', 'FF02', testProject2.Id);
		insert testFloor2;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		UnitType__c unitType2 = dataMaker.createUnitType('Test Unit Type', testProject2.Id);
		insert unitType2;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product 1',
			'UN01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		Product2 testProduct2 = dataMaker.createUnit(
			'Test Product 1',
			'UN02',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct2;
		Product2 testProduct3 = dataMaker.createUnit(
			'Test Product 3',
			'UN03',
			testProject2.Id,
			testFloor2.Id,
			'Available',
			unitType2.Id
		);
		insert testProduct3;
		Product2 testProduct4 = dataMaker.createUnit(
			'Test Product 4',
			'UN04',
			testProject2.Id,
			testFloor2.Id,
			'Available',
			unitType2.Id
		);
		insert testProduct4;
		// Create Promotion Master
		PromotionMaster__c promotionMasterSales1 = dataMaker.craeteActivePromotionMaster(
			null,
			null,
			'ส่วนลด',
			'Sales',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing1 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			null,
			'ส่วนลด',
			'Marketing',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing2 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			null,
			'ที่จอดรถ',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			100.00
		);
		PromotionMaster__c promotionMasterMarketing3 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			testProduct.Id,
			'ฟรีส่วนกลาง',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			1000.00
		);
		PromotionMaster__c promotionMasterMarketing4 = dataMaker.craeteActivePromotionMaster(
			testProject2.Id,
			null,
			'ส่วนลด',
			'Marketing',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing5 = dataMaker.craeteActivePromotionMaster(
			testProject2.Id,
			null,
			'ที่จอดรถ',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			100.00
		);
		List<PromotionMaster__c> promotionMasters = new List<PromotionMaster__c>{
			promotionMasterSales1,
			promotionMasterMarketing1,
			promotionMasterMarketing2,
			promotionMasterMarketing3,
			promotionMasterMarketing4,
			promotionMasterMarketing5
		};
		insert promotionMasters;
		// Create Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		OpportunityTriggerHandler oppTriggerHandler = OpportunityTriggerHandler.getInstance();
		oppTriggerHandler.setBypass();
		Opportunity opportunity1 = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp with Unit 1',
			Date.today(),
			'Open',
			testProduct.Id,
			'Foreign',
			null,
			testProject.Id
		);
		insert opportunity1;
		Opportunity opportunity2 = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp with Unit 3',
			Date.today(),
			'Open',
			testProduct3.Id,
			'Foreign',
			null,
			testProject2.Id
		);
		insert opportunity2;
	}

	@isTest
	static void createPromotionOpportunityRelateToOpportunityTest() {
		Test.startTest();
		PromotionOpportunityService service = PromotionOpportunityService.getInstance();
		List<Opportunity> opportunities = [SELECT Id, ProjectCode__c, UnitCode__c FROM Opportunity];
		Opportunity targetOpp1 = opportunities[0];
		System.debug('key for opp1: ' + targetOpp1.ProjectCode__c + '_' + targetOpp1.UnitCode__c);
		Opportunity targetOpp2 = opportunities[1];
		System.debug('key for opp2: ' + targetOpp2.ProjectCode__c + '_' + targetOpp2.UnitCode__c);
		List<PromotionOpportunity__c> promotionOpportunities = service.createPromotionOpportunityRelateToOpportunity(
			opportunities
		);
		System.assertEquals(3, promotionOpportunities.size());
		List<PromotionOpportunity__c> promotionOpportunitiesInOpp1 = new List<PromotionOpportunity__c>();
		List<PromotionOpportunity__c> promotionOpportunitiesInOpp2 = new List<PromotionOpportunity__c>();
		for (PromotionOpportunity__c promotionOpportunity : promotionOpportunities) {
			if (promotionOpportunity.Opportunity__c == targetOpp1.Id) {
				promotionOpportunitiesInOpp1.add(promotionOpportunity);
			} else if (promotionOpportunity.Opportunity__c == targetOpp2.Id) {
				promotionOpportunitiesInOpp2.add(promotionOpportunity);
			}
		}
		System.assertEquals(1, promotionOpportunitiesInOpp1.size());
		System.assertEquals(2, promotionOpportunitiesInOpp2.size());
		Test.stopTest();
	}

	@isTest
	static void createPromotionOpportunityRelateToOpportunityNegativeTest() {
		Test.startTest();
		PromotionOpportunityService service = PromotionOpportunityService.getInstance();
		List<Opportunity> opportunities = [SELECT Id, Project__c,ProjectCode__c, UnitCode__c FROM Opportunity];
		Opportunity targetOpp1 = opportunities[0];
		targetOpp1.Project__c = null;
		OpportunityTriggerHandler.getInstance().setBypass();
		update targetOpp1;
		OpportunityTriggerHandler.getInstance().clearBypass();
		List<Opportunity> updatedOpportunities = [SELECT Id, Project__c,ProjectCode__c, UnitCode__c FROM Opportunity];
		List<PromotionOpportunity__c> promotionOpportunities = service.createPromotionOpportunityRelateToOpportunity(
			updatedOpportunities
		);
		Test.stopTest();
	}

	@isTest
	static void deleteAndCreateNewPromotionOpportunityTest(){
		Test.startTest();
		PromotionOpportunityService service = PromotionOpportunityService.getInstance();
		Product2 targetUnit = [SELECT Id FROM Product2 WHERE ProductCode = 'UN01' LIMIT 1];
		List<Opportunity> opportunities = [SELECT Id, Unit__c, ProjectCode__c, UnitCode__c FROM Opportunity];
		PromotionMaster__c targetPromotionMaster = [SELECT Id FROM PromotionMaster__c WHERE Unit__r.ProductCode = 'UN01' LIMIT 1];
		opportunities[1].Unit__c = targetUnit.Id;
		List<PromotionOpportunity__c> promotionOpportunities = service.deleteAndCreateNewPromotionOpportunity(opportunities);
		Test.stopTest();
	}
}