force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Project ใด</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Unit Type ใด</description>
    <label>Unit Type</label>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/PromotionOpportunity__c.object-meta.xml
<CustomObject>
    <label>Promotion Opportunity</label>
    <nameField>
        <displayFormat>POP-{000000}</displayFormat>
        <label>Promotion Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PromotionOpportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/fields/PromotionMaster__c.field-meta.xml
<CustomField>
    <fullName>PromotionMaster__c</fullName>
    <description>Promotion ที่ถูกใช่คือ promotion ใด</description>
    <label>Promotion Master</label>
    <referenceTo>PromotionMaster__c</referenceTo>
    <relationshipLabel>Promotion Opportunities</relationshipLabel>
    <relationshipName>Promotion_Opportunities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PromotionOpportunitySelectorTest.cls
@isTest
public with sharing class PromotionOpportunitySelectorTest {
	@TestSetup
	static void makeData() {
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		Project__c testProject2 = dataMaker.createProject('Test Project 2', 'AA02', 'CD');
		insert testProject2;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(
			testProduct.Id,
			15000000,
			20000000,
			10000000
		);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Create Promotion Master
		PromotionMaster__c promotionMasterSales1 = dataMaker.craeteActivePromotionMaster(
			null,
			null,
			'ส่วนลด',
			'Sales',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing1 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			null,
			'ส่วนลด',
			'Marketing',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing2 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			null,
			'ที่จอดรถ',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			100.00
		);
		PromotionMaster__c promotionMasterMarketing3 = dataMaker.craeteActivePromotionMaster(
			testProject.Id,
			testProduct.Id,
			'ฟรีส่วนกลาง',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			1000.00
		);
		PromotionMaster__c promotionMasterMarketing4 = dataMaker.craeteActivePromotionMaster(
			testProject2.Id,
			null,
			'ส่วนลด',
			'Marketing',
			'Discount (ส่วนลด)',
			'Add Detail',
			'Description',
			200.00
		);
		PromotionMaster__c promotionMasterMarketing5 = dataMaker.craeteActivePromotionMaster(
			testProject2.Id,
			null,
			'ที่จอดรถ',
			'Marketing',
			'Premium (ของแถม)',
			'Add Detail',
			'Description',
			100.00
		);
		List<PromotionMaster__c> promotionMasters = new List<PromotionMaster__c>{
			promotionMasterSales1,
			promotionMasterMarketing1,
			promotionMasterMarketing2,
			promotionMasterMarketing3,
			promotionMasterMarketing4,
			promotionMasterMarketing5
		};
		insert promotionMasters;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		OpportunityTriggerHandler handler = OpportunityTriggerHandler.getInstance();
		handler.setBypass();
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Foreign',
			null,
			testProject.Id
		);
		insert opportunity;
		handler.clearBypass();
		// Create Promotion Opportunity
		PromotionOpportunity__c promotionOpp1 = dataMaker.createPromotionOpportunity(
			opportunity.Id,
			promotionMasterMarketing1.Id
		);
		PromotionOpportunity__c promotionOpp2 = dataMaker.createPromotionOpportunity(
			opportunity.Id,
			promotionMasterMarketing2.Id
		);
		List<PromotionOpportunity__c> promotionOpportunities = new List<PromotionOpportunity__c>{
			promotionOpp1,
			promotionOpp2
		};
		insert promotionOpportunities;
	}

	@isTest
	static void getPromotionOpportunitiesMapByOppIdTest() {
		Test.startTest();
		Map<Id, Opportunity> opportunityMapById = new Map<Id, Opportunity>([SELECT Id FROM Opportunity]);
		PromotionOpportunitySelector selector = PromotionOpportunitySelector.getInstance();
		Map<Id, List<PromotionOpportunity__c>> promotionOpportunitiesMapByOppId = selector.getPromotionOpportunitiesMapByOppId(
			opportunityMapById.keySet()
		);
		System.assertEquals(2, promotionOpportunitiesMapByOppId.values()[0].size());
		Test.stopTest();
	}
}