force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityAccountChangeLogSelectorTest.cls
/**
 * Phase2
 * Details:
 * - Add new class to be test class of OpportunityAccountChangeLogSelector
 */
@isTest
public class OpportunityAccountChangeLogSelectorTest {

	@TestSetup
	static void makeData() {
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(
			testProduct.Id,
			15000000,
			20000000,
			10000000
		);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opp1 = dataMaker.createOpportunity(
							account.Id,
							'Omitted',
							'Test Opp',
							Date.today(),
							'Open',
							testProduct.Id,
							'Foreign',
							null,
							testProject.Id
						);
		Opportunity opp2 = dataMaker.createOpportunity(
							account.Id,
							'Omitted',
							'Test Opp2',
							Date.today(),
							'Open',
							testProduct.Id,
							'Foreign',
							null,
							testProject.Id
						);
		Opportunity opp3 = dataMaker.createOpportunity(
							account.Id,
							'Omitted',
							'Test Opp3',
							Date.today(),
							'Open',
							testProduct.Id,
							'Foreign',
							null,
							testProject.Id
						);
		List<Opportunity> opportunities = new List<Opportunity>{opp1,opp2,opp3};
		insert opportunities;
		// Craete OpportunityAccountChangeLog__c
		OpportunityAccountChangeLog__c oppAccChangeLog = dataMaker.createOpportunityAccountChangeLog(opp1.Id,opp2.Id,opp1.AccountId,opp2.AccountId);
		List<OpportunityAccountChangeLog__c> oppAccChangeLogs = new List<OpportunityAccountChangeLog__c>{oppAccChangeLog};
		insert oppAccChangeLogs;
	}

	/**
	 * Phase2
	 * Details:
	 * - Add test class to test method getOpportunityAccountChangeLogWithSnapshotReceipts
	 */
	@isTest
	static void getOpportunityAccountChangeLogWithSnapshotReceiptsTest(){
		Test.startTest();
		OpportunityAccountChangeLogSelector selector = OpportunityAccountChangeLogSelector.getInstance();
		Map<Id,OpportunityAccountChangeLog__c> oppAccChangeLogMapById = new Map<Id,OpportunityAccountChangeLog__c>([SELECT Id FROM OpportunityAccountChangeLog__c]);
		Map<Id,OpportunityAccountChangeLog__c> targetResult = selector.getOpportunityAccountChangeLogWithSnapshotReceipts(oppAccChangeLogMapById.keySet());
		System.assertEquals(oppAccChangeLogMapById.values().size(), targetResult.values().size());
		Test.stopTest();
	}

	/**
	 * Phase2
	 * Details:
	 * - Add test class to test method getOpportunityAccountChangeLogFromPreviousOpportuntiyId
	 */
	@isTest
	static void getOpportunityAccountChangeLogFromPreviousOpportuntiyIdTest(){
		Test.startTest();
		OpportunityAccountChangeLogSelector selector = OpportunityAccountChangeLogSelector.getInstance();
		OpportunityAccountChangeLog__c oppAccChangeLog = [SELECT Id,PreviousOpportunity__c,PreviousAccount__c FROM OpportunityAccountChangeLog__c LIMIT 1];
		Map<Id,OpportunityAccountChangeLog__c> targetResult = selector.getOpportunityAccountChangeLogFromPreviousOpportuntiyIdMapByPreviousAccountId(new Set<Id>{oppAccChangeLog.PreviousAccount__c});
		Test.stopTest();
	}
}