force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateRecordFromOpportunityCtrlTest.cls
@isTest
public with sharing class CreateRecordFromOpportunityCtrlTest {
    @TestSetup
    static void makeData() {
        DataMaker dataMaker = DataMaker.getInstance();
        // Create Project
        Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
        insert testProject;
        // Craete Floor
        Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
        insert testFloor;
        // Create Unit Type
        UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
        insert unitType;
        // Create Unit
        Product2 testProduct = dataMaker.createUnit(
            'Test Product',
            'PP01',
            testProject.Id,
            testFloor.Id,
            'Available',
            unitType.Id
        );
        insert testProduct;
        // Create Pricebook Entry
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(
            testProduct.Id,
            15000000,
            20000000,
            10000000
        );
        testPricebookEntry1.Pricebook2Id = pricebookId;
        testPricebookEntry1.UseStandardPrice = false;
        insert testPricebookEntry1;
        // Creat Account
        Id recordTypeId = Schema.getGlobalDescribe()
            .get('Account')
            .getDescribe()
            .getRecordTypeInfosByName()
            .get('Co-Owner - Corporate')
            .getRecordTypeId();
        Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
        insert account;
        // Create Opportunity
        List<Opportunity> opportunities = new List<Opportunity>{
            dataMaker.createOpportunity(
                account.Id,
                'Omitted',
                'Test Opp',
                Date.today(),
                'Open',
                testProduct.Id,
                'Foreign',
                null,
                testProject.Id
            )
        };
        insert opportunities;
    }

    @isTest 
    static void createQuoteFromOpportunityTest(){
        Test.startTest();
        Opportunity targetOpp = [SELECT Id FROM Opportunity LIMIT 1];
        List<Quote__c> targetQuotes = new List<Quote__c>{CreateRecordFromOpportunityController.createQuoteFromOpportunity(targetOpp.Id)};
        List<Quote__c> resultQuotes = [SELECT Id , Opportunity__c FROM Quote__c ];
        System.assertEquals(1, targetQuotes.size());
        Quote__c resultQuote = resultQuotes[0];
        System.assertEquals(targetOpp.Id, resultQuote.Opportunity__c);
        Test.stopTest();
    }

    @isTest 
    static void createContractFromOpportunityTest(){
        Test.startTest();
        Opportunity targetOpp = [SELECT Id,AccountId FROM Opportunity LIMIT 1];
        List<Contract> targetContracts = new List<Contract>{ CreateRecordFromOpportunityController.createContractFromOpportunity(targetOpp.Id) };
        List<Contract> resultContracts = [SELECT Id , Opportunity__c, AccountId FROM Contract ];
        System.assertEquals(1, targetContracts.size());
        Contract resultContract = resultContracts[0];
        System.assertEquals(targetOpp.Id, resultContract.Opportunity__c);
        System.assertEquals(targetOpp.AccountId, resultContract.AccountId);
        Test.stopTest();
    }
}