force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Quota__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Quota__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReservationPrice__c.field-meta.xml
<CustomField>
    <fullName>ReservationPrice__c</fullName>
    <formula>Unit__r.ReservationPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reservation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SyncedQuoteId__c.field-meta.xml
<CustomField>
    <fullName>SyncedQuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SyncedQuoteId</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Term Masters</relationshipLabel>
    <relationshipName>Payment_Term_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ReservationPrice__c.field-meta.xml
<CustomField>
    <fullName>ReservationPrice__c</fullName>
    <label>Reservation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SyncQuoteCtrlTest.cls
@isTest
private class SyncQuoteCtrlTest {
    @TestSetup
    static void makeData(){
        DataMaker dataMaker = DataMaker.getInstance();
        // Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
        insert testProject;
        // Craete Floor
        Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
        insert testFloor;
        // Create Unit Type
        UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
        insert unitType;
        // Create Unit
        Product2 testProduct = dataMaker.createUnit(
            'Test Product',
            'PP01',
            testProject.Id,
            testFloor.Id,
            'Available',
            unitType.Id
        );
        testProduct.ReservationPrice__c = 10000;
        insert testProduct;
        // Create Pricebook
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(testProduct.Id, 150000, 200000,10000000);
        testPricebookEntry1.Pricebook2Id = pricebookId;
        testPricebookEntry1.UseStandardPrice = false;
        insert testPricebookEntry1;
        // Creat Account
        Id recordTypeId = Schema.getGlobalDescribe()
            .get('Account')
            .getDescribe()
            .getRecordTypeInfosByName()
            .get('Co-Owner - Corporate')
            .getRecordTypeId();
        Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
        insert account;
        PaymentTermMaster__c paymentTermMasterNew = dataMaker.craetePaymentTermMaster(testProject.Id,'TQ Series 5-10-85', 'Series', 'Thai', 25);
        insert paymentTermMasterNew;
        List<PaymentTerm__c> paymentTermWrappers = new List<PaymentTerm__c>();
        PaymentTerm__c paymentTarm1 = dataMaker.createPaymentTermLineItem(
            paymentTermMasterNew.Id,
            1,
            null,
            10,
            'Contract'
        );
        PaymentTerm__c paymentTarm2 = dataMaker.createPaymentTermLineItem(
            paymentTermMasterNew.Id,
            2,
            null,
            20,
            'Installment 1'
        );
        PaymentTerm__c paymentTarm3 = dataMaker.createPaymentTermLineItem(
            paymentTermMasterNew.Id,
            3,
            null,
            null,
            'Transfer'
        );
        paymentTermWrappers.add(paymentTarm1);
        paymentTermWrappers.add(paymentTarm2);
        paymentTermWrappers.add(paymentTarm3);
        insert paymentTermWrappers;
        // Create Opportunity
        List<Opportunity> opportunities = new List<Opportunity>{
            dataMaker.createOpportunity(
                account.Id,
                'Omitted',
                'Test Opp',
                Date.today(),
                'Open',
                testProduct.Id,
                'Thai',
                paymentTermMasterNew.Id,
                testProject.Id
            )
        };
        insert opportunities;
        Quote__c testQuote = dataMaker.createQuote(
            opportunities[0].Id
        );  
        insert testQuote;
    }
    @isTest 
    static void syncQuoteFromOpportunityTest(){
        Quote__c quote = [SELECT Id,Opportunity__c , IsSyncing__c FROM Quote__c LIMIT 1];
        Quote__c result = SyncQuoteCtrl.syncQuoteFromOpportunity(quote.Id);
        Opportunity opp = [SELECT Id , SyncedQuoteId__c FROM Opportunity WHERE  Id=: result.Opportunity__c];
        System.assertEquals(true, result.IsSyncing__c);
        System.assertEquals(opp.SyncedQuoteId__c, result.Id);
        
    }
}