force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MakeAPaymentConfig__mdt/MakeAPaymentConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuring information to be displayed when the &apos;Make a Payment&apos; button is pressed on the Opportunity, ensuring that relevant payment details are shown on the screen.</description>
    <label>Make a Payment Config</label>
    <pluralLabel>Make a Payment Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/MakeAPaymentConfig__mdt/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__c</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProceedPaymentControllerTest.cls
@isTest
public with sharing class ProceedPaymentControllerTest {
	@TestSetup
	static void makeData() {
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(
			testProduct.Id,
			15000000,
			20000000,
			10000000
		);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Thai',
			null,
			testProject.Id
		);
		insert opportunity;
		// Create Opp Payments
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPayment,
			contractOppPayment,
			installmentOppPayment,
			transferOppPayment
		};
		insert oppPayments;
		// Create Invoice
		Invoice__c invoice = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 10, 6), Date.newInstance(2024, 10, 1), true, 'Address');
		Invoice__c invoice2 = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 11, 6), Date.newInstance(2024, 11, 1),  true, 'Address');
		List<Invoice__c> invoices = new List<Invoice__c>{ invoice, invoice2 };
		insert invoices;
		// Create Invoice Line Item
		InvoiceLineItem__c invoiceLineItem1 = dataMaker.createInvoiceLineItem(
			invoice.Id,
			reservationOppPayment.Id,
			50000,
			Date.newInstance(2024, 12, 1),
			''
		);
		InvoiceLineItem__c invoiceLineItem2 = dataMaker.createInvoiceLineItem(
			invoice2.Id,
			contractOppPayment.Id,
			100000,
			Date.newInstance(2025, 1, 1),
			''
		);
		List<InvoiceLineItem__c> invoiceLineItems = new List<InvoiceLineItem__c>{ invoiceLineItem1, invoiceLineItem2 };
		insert invoiceLineItems;
		// Create Name Formatting
		NameFormattingMasterData__c format = dataMaker.createNameFormattingMasterData(
			'PaymentReceipt__c', 'Format', 'Object', 'RV-{Opportunity__r.Project__r.ProjectCode__c}{{CreatedDate:FORMATDATETIME:yyMM}{RUNNINGNUMBER:000}', 1, null
		);
		insert format;
	}

	@isTest
	static void getMakeAPaymentConfigTest() {
		Test.startTest();
		List<MakeAPaymentConfig__mdt> configs = ProceedPaymentController.getMakeAPaymentConfig();
		Test.stopTest();
	}

	@isTest
	static void getPicklistValuesTest() {
		Test.startTest();
		List<ComboboxModel> picklists = ProceedPaymentController.getPicklistValues(
			'PaymentMethod__c',
			'PaymentType__c'
		);
		Test.stopTest();
	}

	@isTest
	static void proceedPaymentTest() {
		Test.startTest();
		Opportunity opportuntiy = [SELECT Id FROM Opportunity LIMIT 1];
		List<PaymentMethod__c> paymentMethods = new List<PaymentMethod__c>{
			new PaymentMethod__c(PaymentType__c = 'Credit Card', ReceivedAmount__c = 10000),
			new PaymentMethod__c(PaymentType__c = 'Credit Card', ReceivedAmount__c = 40000)
		};
		Map<String, List<SObject>> result = ProceedPaymentController.proceedPayment(
			opportuntiy.Id,
			50000,
			paymentMethods,
			null,
			false
		);
		PaymentReceipt__c paymentReceipt = [SELECT Id, ReceiptNo__c FROM PaymentReceipt__c LIMIT 1];
		System.assertEquals(paymentReceipt.Id, result.get('PaymentReceipt__c')[0].Id);
		System.assertEquals(paymentReceipt.ReceiptNo__c, result.get('PaymentReceipt__c')[0].get('ReceiptNo__c'));
		List<PaymentReceiptLineItem__c> paymentReceiptLineItems = [
			SELECT Id, ReceivedAmount__c, PaymentReceipt__c, Status__c, OpportunityPayment__c, InvoiceLineItem__c
			FROM PaymentReceiptLineItem__c
			WHERE PaymentReceipt__c = :paymentReceipt.Id
		];
		InvoiceLineItem__c reservationInvoiceLine = [
			SELECT Id, PaymentReceiptLineItem__c
			FROM InvoiceLineItem__c
			WHERE OpportunityPayment__r.Term__c = 'Reservation'
			LIMIT 1
		];
		System.assertEquals(1, paymentReceiptLineItems.size());
		OpportunityPayment__c reservationOppPayment = [SELECT Id, ReceivedAmount__c, Remaining__c FROM OpportunityPayment__c WHERE Term__c = 'Reservation'];
		System.assertEquals(0, reservationOppPayment.Remaining__c);
		System.assertEquals(2, result.get('PaymentMethod__c').size());
		Test.stopTest();
	}

	/**
	 * Phase2
	 * Details:
	 * - add test method for getCompanyBanks
	 */
	@isTest
	static void getCompanyBanksTest() {
		Test.startTest();
		Opportunity opportunity = [SELECT Id,IsPaidNovationFee__c FROM Opportunity LIMIT 1];
		List<ComboboxModel> picklistValues = ProceedPaymentController.getCompanyBanks(opportunity.Id);
		Test.stopTest();
	}

	/**
	 * Phase2
	 * Details:
	 * - add test method for proceedNovationPayment
	 */
	@isTest
	static void proceedNovationPaymentTest() {
		Test.startTest();
		Opportunity opportunity = [SELECT Id,IsPaidNovationFee__c FROM Opportunity LIMIT 1];
		System.assertEquals(false, opportunity.IsPaidNovationFee__c);
		List<PaymentMethod__c> paymentMethods = new List<PaymentMethod__c>{
			new PaymentMethod__c(PaymentType__c = 'Credit Card', ReceivedAmount__c = 50000)
		};
		Map<String, List<SObject>> result = ProceedPaymentController.proceedNovationPayment(
			opportunity.Id,
			50000,
			paymentMethods
		);
		PaymentReceipt__c paymentReceipt = [SELECT Id, ReceiptNo__c,ReceiptType__c FROM PaymentReceipt__c LIMIT 1];
		System.assertEquals(paymentReceipt.Id, result.get('PaymentReceipt__c')[0].Id);
		System.assertEquals(paymentReceipt.ReceiptNo__c, result.get('PaymentReceipt__c')[0].get('ReceiptNo__c'));
		System.assertEquals(GlobalConstants.RECEIPT_TYPE_NOVATION, paymentReceipt.ReceiptType__c);
		List<PaymentReceiptLineItem__c> paymentReceiptLineItems = [
			SELECT Id, ReceivedAmount__c, PaymentReceipt__c, Status__c, OpportunityPayment__c, InvoiceLineItem__c
			FROM PaymentReceiptLineItem__c
			WHERE PaymentReceipt__c = :paymentReceipt.Id
		];
		System.assertEquals(1, paymentReceiptLineItems.size());
		System.assertEquals(50000, paymentReceiptLineItems[0].ReceivedAmount__c);
		Opportunity updatedOpportunity = [SELECT Id,IsPaidNovationFee__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];
		System.assertEquals(true, updatedOpportunity.IsPaidNovationFee__c);
		Test.stopTest();
	}

	/**
	 * Phase2
	 * Details:
	 * - add test method for getAreaDetails
	 */
	@isTest
	static void getAreaDetailsTest(){
		Test.startTest();
		Opportunity opportunity = [SELECT Id,Project__c FROM Opportunity LIMIT 1];
		Map<String,Decimal> result = ProceedPaymentController.getAreaDetails(opportunity.Id);
		System.assertEquals(0, result.get('areaBookedOrSoldAsFQQuota'));
		Test.stopTest();
	}


	/**
	 * Phase2
	 * Details:
	 * - add test method for proceedPaymentTest in case Recurring Payment
	 */
	@isTest
	static void proceedPaymentRecurringTest() {
		Test.startTest();
		Opportunity opportuntiy = [SELECT Id FROM Opportunity LIMIT 1];
		List<PaymentMethod__c> paymentMethods = new List<PaymentMethod__c>{
			new PaymentMethod__c(PaymentType__c = 'Credit Card', ReceivedAmount__c = 10000),
			new PaymentMethod__c(PaymentType__c = 'Credit Card', ReceivedAmount__c = 40000)
		};
		Map<String, List<SObject>> result = ProceedPaymentController.proceedPayment(
			opportuntiy.Id,
			50000,
			paymentMethods,
			null,
			true
		);
		PaymentReceipt__c paymentReceipt = [SELECT Id, ReceiptNo__c,ReceiptType__c FROM PaymentReceipt__c LIMIT 1];
		System.assertEquals(paymentReceipt.Id, result.get('PaymentReceipt__c')[0].Id);
		System.assertEquals(paymentReceipt.ReceiptNo__c, result.get('PaymentReceipt__c')[0].get('ReceiptNo__c'));
		System.assertEquals(paymentReceipt.ReceiptType__c, GlobalConstants.RECEIPT_TYPE_RECURRING);
		List<PaymentReceiptLineItem__c> paymentReceiptLineItems = [
			SELECT Id, ReceivedAmount__c, PaymentReceipt__c, Status__c, OpportunityPayment__c, InvoiceLineItem__c
			FROM PaymentReceiptLineItem__c
			WHERE PaymentReceipt__c = :paymentReceipt.Id
		];
		InvoiceLineItem__c reservationInvoiceLine = [
			SELECT Id, PaymentReceiptLineItem__c
			FROM InvoiceLineItem__c
			WHERE OpportunityPayment__r.Term__c = 'Reservation'
			LIMIT 1
		];
		System.assertEquals(1, paymentReceiptLineItems.size());
		OpportunityPayment__c reservationOppPayment = [SELECT Id, ReceivedAmount__c, Remaining__c FROM OpportunityPayment__c WHERE Term__c = 'Reservation'];
		System.assertEquals(0, reservationOppPayment.Remaining__c);
		System.assertEquals(2, result.get('PaymentMethod__c').size());
		Test.stopTest();
	}

}