force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <formula>Opportunity__r.UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <formula>(  BLANKVALUE(UnitPrice__c, 0.00)  -( BLANKVALUE(UnitPrice__c, 0.00) *BLANKVALUE(TotalDiscountPercent__c, 0.00) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Quota__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Quota__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReservationDueDate__c.field-meta.xml
<CustomField>
    <fullName>ReservationDueDate__c</fullName>
    <label>Reservation Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReservationPrice__c.field-meta.xml
<CustomField>
    <fullName>ReservationPrice__c</fullName>
    <formula>Unit__r.ReservationPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reservation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The original price before discounts. Get value from &apos;Pricebook2&apos;</description>
    <label>Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/IsMasterData__c.field-meta.xml
<CustomField>
    <fullName>IsMasterData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>เพื่อบอกว่า Record นี้ เป็นค่าตั้งต้นใน Opportunity Payment</description>
    <label>Is Master Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <formula>&quot;On the &quot; &amp; TEXT( PaymentTermMaster__r.DueDate__c ) &amp; &quot;th of Every Month&quot;</formula>
    <label>Due Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>ประเภทของงวดชำระ</description>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <inlineHelpText>Date for collecting payments (installment)</inlineHelpText>
    <label>Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Term Masters</relationshipLabel>
    <relationshipName>Payment_Term_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ReservationPrice__c.field-meta.xml
<CustomField>
    <fullName>ReservationPrice__c</fullName>
    <label>Reservation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <description>Date on which Project is finished or completed.</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <formula>TEXT(PaymentTerm__r.DueDate__c) &amp; 
CASE(
  MOD(PaymentTerm__r.DueDate__c, 10),
  1, IF(PaymentTerm__r.DueDate__c = 11, &quot;th&quot;, &quot;st&quot;),
  2, IF(PaymentTerm__r.DueDate__c = 12, &quot;th&quot;, &quot;nd&quot;),
  3, IF(PaymentTerm__r.DueDate__c = 13, &quot;th&quot;, &quot;rd&quot;),
  &quot;th&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityPaymentService.cls
public with sharing class OpportunityPaymentService {
	public static OpportunityPaymentService instance;

	public static OpportunityPaymentService getInstance() {
		if (instance == null) {
			instance = new OpportunityPaymentService();
		}
		return instance;
	}

	public List<OpportunityPayment__c> createOpportunityPayments(List<Opportunity> opportunities) {
		List<PaymentTerm__c> paymentTermLineItems = new List<PaymentTerm__c>();
		Map<Id , List<PaymentTerm__c>> paymentTermMapByOppId = new Map<Id , List<PaymentTerm__c>>();
		List<OpportunityPayment__c> listForInsertOpportunityPayments = new List<OpportunityPayment__c>();
		Set<Id> paymentTermMasterIds = new Set<Id>();
		Set<Id> productIds = new Set<Id>();
		Set<Id> oppIds = new Set<Id>();
		Set<Id> projectIds = new Set<Id>();
		// Id oppId;
		Id paymentTermMasterId;
		for (Opportunity opp : opportunities) {
			oppIds.add(opp.Id);
			paymentTermMasterIds.add(opp.PaymentTermMaster__c);
			productIds.add(opp.Unit__c);
			projectIds.add(opp.Project__c);
		}
		PaymentTermSelector selector = PaymentTermSelector.getInstance();
		ProjectSelector projectSelector = ProjectSelector.getInstance();
		Product2Selector productSelector = Product2Selector.getInstance();
		Map<Id, PaymentTermMaster__c> paymentTermMasterWithPaymentTermLineItemMapById = selector.getPaymentTermMasterWithLineItemsMapById(
			paymentTermMasterIds
		);

		Map<Id, Project__c> projectMapById = projectSelector.getProjectById(projectIds);
		Map<Id, Product2> productMapById = productSelector.getProduct2ById(productIds);
		OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		Map<Id, Opportunity> oppMapById = oppSelector.getOpportunityMapById(oppIds);
		for (Opportunity opp : opportunities) {
			PaymentTermMaster__c paymentTermMaster = paymentTermMasterWithPaymentTermLineItemMapById.get(
				opp.PaymentTermMaster__c
			);
			List<PaymentTerm__c> paymentTerms = paymentTermMaster == null
				? new List<PaymentTerm__c>()
				: paymentTermMaster.Payment_Term__r;
			// oppId = opp.Id;
			paymentTermMasterId = opp.PaymentTermMaster__c;
			paymentTermMapByOppId.put(opp.Id , paymentTerms);
			//paymentTermLineItems.addAll(paymentTerms);
		}

		// create map from oppForAdjusts
		Map<Id,List<OpportunityPayment__c>> oppPaymentsMapByOppId = new Map<Id,List<OpportunityPayment__c>>();
		for (Id oppId : oppIds){
			List<OpportunityPayment__c> oppForAdjusts = new List<OpportunityPayment__c>();
			Opportunity targetOpp = oppMapById.get(oppId);
			paymentTermLineItems = paymentTermMapByOppId.get(oppId);
			oppForAdjusts.addAll(generateOpportunityPaymentsFromPaymentTerms(
				paymentTermLineItems,
				targetOpp.PaymentTermMaster__c,
				targetOpp
			));
			oppPaymentsMapByOppId.put(oppId,oppForAdjusts);
		}
		for (Opportunity opp : opportunities) {
			Opportunity targetOpp = oppMapById.get(opp.Id);
			List<OpportunityPayment__c> targetOppPayment = oppPaymentsMapByOppId.get(opp.Id);
			List<OpportunityPayment__c> adjustAmountOpportunityPayments = new List<OpportunityPayment__c>();
			List<OpportunityPayment__c> adjustDueDateOpportunityPayments = new List<OpportunityPayment__c>();
			adjustAmountOpportunityPayments = adjustAmount(
				targetOppPayment,
				targetOpp,
				paymentTermMasterWithPaymentTermLineItemMapById,
				productMapById
			);
			adjustDueDateOpportunityPayments = adjustDueDate(
				adjustAmountOpportunityPayments,
				targetOpp,
				paymentTermMasterWithPaymentTermLineItemMapById,
				projectMapById
			);
			listForInsertOpportunityPayments.addAll(adjustDueDateOpportunityPayments);
		}
		return listForInsertOpportunityPayments;
	}

	public List<OpportunityPayment__c> updateOpportunityPaymentByPaymentMaster(List<Opportunity> opportunitys) {
		Set<Id> oppIds = new Set<Id>();
		List<OpportunityPayment__c> opportunityPaymentsToDelete = new List<OpportunityPayment__c>();
		for (Opportunity opp : opportunitys) {
			oppIds.add(opp.Id);
		}
		OpportunityPaymentSelector selectorOpportunityPayment = OpportunityPaymentSelector.getInstance();
		Map<Id, List<OpportunityPayment__c>> oldOpportunityPayments = selectorOpportunityPayment.getOpportunityPaymentsMapByOppId(
			oppIds
		);
		for (Opportunity opp : opportunitys) {
			opportunityPaymentsToDelete = oldOpportunityPayments.get(opp.Id) == null
				? new List<OpportunityPayment__c>()
				: oldOpportunityPayments.get(opp.Id);
		}
		if (!opportunityPaymentsToDelete.isEmpty()) {
			delete opportunityPaymentsToDelete;
		}
		List<OpportunityPayment__c> result = createOpportunityPayments(opportunitys);
		return result;
	}

	public List<OpportunityPayment__c> adjustRelatedOpportunityPaymentAfterApplyDiscount(
		List<Opportunity> opportunitys
	) {
		List<OpportunityPayment__c> adjustOpportunitys = new List<OpportunityPayment__c>();
		List<OpportunityPayment__c> updateOppPayments = new List<OpportunityPayment__c>();
		Set<Id> oppIds = new Set<Id>();
		Set<Id> paymentMasterIds = new Set<Id>();
		Set<Id> productIds = new Set<Id>();

		for (Opportunity opp : opportunitys) {
			oppIds.add(opp.Id);
			paymentMasterIds.add(opp.PaymentTermMaster__c);
			productIds.add(opp.Unit__c);
		}
		PaymentTermSelector selector = PaymentTermSelector.getInstance();
		Product2Selector productSelector = Product2Selector.getInstance();
		Map<Id, PaymentTermMaster__c> paymentTermMasterWithPaymentTermLineItemMapById = selector.getPaymentTermMasterWithLineItemsMapById(
			paymentMasterIds
		);
		Map<Id, Product2> productMapById = productSelector.getProduct2ById(productIds);
		OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		Map<Id, List<OpportunityPayment__c>> oppPaymentListMapById = oppPaymentSelector.getOpportunityPaymentsMapByOppId(
			oppIds
		);
		Map<Id, Opportunity> oppMapById = oppSelector.getOpportunityMapById(oppIds);
		for (Opportunity opp : opportunitys) {
			List<OpportunityPayment__c> oppPaymentListById = oppPaymentListMapById.get(opp.Id) == null
				? new List<OpportunityPayment__c>()
				: oppPaymentListMapById.get(opp.Id);
			Opportunity oppById = oppMapById.get(opp.Id);
			adjustOpportunitys = adjustAmount(
				oppPaymentListById,
				oppById,
				paymentTermMasterWithPaymentTermLineItemMapById,
				productMapById
			);
			updateOppPayments.addAll(adjustOpportunitys);
		}
		return updateOppPayments;
	}

	public List<OpportunityPayment__c> adjustRelatedOpportunityPaymentAfterChangeReservationDueDate(
		List<Opportunity> opportunitys
	) {
		List<OpportunityPayment__c> adjustOpportunitys = new List<OpportunityPayment__c>();
		List<OpportunityPayment__c> updateOppPayments = new List<OpportunityPayment__c>();
		Set<Id> oppIds = new Set<Id>();
		Set<Id> paymentMasterIds = new Set<Id>();
		Set<Id> projectIds = new Set<Id>();

		for (Opportunity opp : opportunitys) {
			oppIds.add(opp.Id);
			paymentMasterIds.add(opp.PaymentTermMaster__c);
			projectIds.add(opp.Project__c);
		}
		PaymentTermSelector selector = PaymentTermSelector.getInstance();
		ProjectSelector projectSelector = ProjectSelector.getInstance();
		Map<Id, PaymentTermMaster__c> paymentTermMasterWithPaymentTermLineItemMapById = selector.getPaymentTermMasterWithLineItemsMapById(
			paymentMasterIds
		);
		Map<Id, Project__c> getProjectMap = projectSelector.getProjectById(projectIds);
		OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		Map<Id, List<OpportunityPayment__c>> oppPaymentListMapById = oppPaymentSelector.getOpportunityPaymentsMapByOppId(
			oppIds
		);
		Map<Id, Opportunity> oppMapById = oppSelector.getOpportunityMapById(oppIds);
		for (Opportunity opp : opportunitys) {
			List<OpportunityPayment__c> oppPaymentListById = oppPaymentListMapById.get(opp.Id);
			Opportunity oppById = oppMapById.get(opp.Id);
			adjustOpportunitys = adjustDueDate(
				oppPaymentListById,
				oppById,
				paymentTermMasterWithPaymentTermLineItemMapById,
				getProjectMap
			);
			updateOppPayments.addAll(adjustOpportunitys);
		}
		return updateOppPayments;
	}

	public List<OpportunityPayment__c> getOppPaymentsFromJSONString(String oppPaymentJSON) {
		List<OpportunityPayment__c> oppPaymentsResult = new List<OpportunityPayment__c>();
		List<OpportunityPaymentWrapper> opportunityPaymentWrappers = (List<OpportunityPaymentWrapper>) JSON.deserialize(
			oppPaymentJSON,
			List<OpportunityPaymentWrapper>.class
		);
		for (OpportunityPaymentWrapper wrapper : opportunityPaymentWrappers) {
			OpportunityPayment__c oppPayment = new OpportunityPayment__c();
			oppPayment.Id = wrapper.id;
			oppPayment.Order__c = wrapper.order;
			oppPayment.Amount__c = wrapper.amount;
			oppPayment.DueDate__c = wrapper.dueDate;
			oppPayment.Term__c = wrapper.term;
			oppPayment.IsMasterData__c = true;
			oppPayment.Name = String.valueOf(wrapper.order);
			if (wrapper.isNewRecord) {
				oppPayment.Opportunity__c = wrapper.oppId;
			}
			oppPaymentsResult.add(oppPayment);
		}
		return oppPaymentsResult;
	}

	//แยก Method ที่ adjust Due Date
	public List<OpportunityPayment__c> adjustDueDate(
		List<OpportunityPayment__c> oppPayments,
		Opportunity opportunity,
		Map<Id, PaymentTermMaster__c> paymentTermMasterWithPaymentTermLineItemMapById,
		Map<Id, Project__c> getProjectMap
	) {
		Date accumulatorDate = opportunity.ReservationDueDate__c;
		Id paymentMasterId = opportunity.PaymentTermMaster__c;
		PaymentTermMaster__c paymentTermMaster = paymentTermMasterWithPaymentTermLineItemMapById.get(paymentMasterId);
		Integer dueDateOfInstallment = paymentTermMaster == null ? null : Integer.valueOf(paymentTermMaster.DueDate__c);
		// loop over oppPayments to assign DueDate__c
		Integer installmentDateCount = 1;
		Integer contractDateCount = 1;
		Date contractDateForInstallment = accumulatorDate;
		for (OpportunityPayment__c oppPayment : oppPayments) {
			if (oppPayment.Term__c == 'Reservation') {
				oppPayment.DueDate__c = accumulatorDate;
			} else if (oppPayment.Term__c.contains('Contract')) {
				Date contractDate = accumulatorDate?.addDays(14 * contractDateCount);
				System.debug('Date Contract : ' + contractDate);
				oppPayment.DueDate__c = contractDate;
				contractDateForInstallment = contractDate;
				contractDateCount++;
			} else if (oppPayment.Term__c.contains('Installment')) {
				Date installmentDate = contractDateForInstallment?.addMonths(installmentDateCount);
				Integer year = installmentDate?.year();
				Integer month = installmentDate?.month();
				Date installmentDueDate = contractDateForInstallment != null &&
					dueDateOfInstallment != null
					? Date.newInstance(year, month, dueDateOfInstallment)
					: null;
				System.debug('Date Installment : ' + accumulatorDate);
				oppPayment.DueDate__c = installmentDueDate;
				installmentDateCount++;
			} else if (oppPayment.Term__c.contains('Transfer')) {
				Project__c project = getProjectMap.get(opportunity.Project__c);
				oppPayment.DueDate__c = project?.CompletionDate__c;
			}
		}
		return oppPayments;
	}

	public List<OpportunityPayment__c> adjustAmount(
		List<OpportunityPayment__c> oppPayments,
		Opportunity opportunity,
		Map<Id, PaymentTermMaster__c> paymentTermMasterWithPaymentTermLineItemMapById,
		Map<Id, Product2> productMapById
	) {
		Id paymentMasterId = opportunity.PaymentTermMaster__c;
		List<OpportunityPayment__c> resultOppPayments = new List<OpportunityPayment__c>();
		PaymentTermMaster__c paymentTermMaster = paymentTermMasterWithPaymentTermLineItemMapById.get(paymentMasterId);
		List<PaymentTerm__c> paymentTermLineItems = paymentTermMaster == null
			? new List<PaymentTerm__c>()
			: paymentTermMaster.Payment_Term__r;
		Product2 product = productMapById.get(opportunity.Unit__c);
		Map<String, PaymentTerm__c> paymentTermMapByTerm = new Map<String, PaymentTerm__c>();
		for (PaymentTerm__c paymentTerm : paymentTermLineItems) {
			if (paymentTerm.Term__c.contains('Contract')) {
				paymentTermMapByTerm.put(paymentTerm.Term__c, paymentTerm);
			} else if (paymentTerm.Term__c.contains('Installment')) {
				paymentTermMapByTerm.put(paymentTerm.Term__c, paymentTerm);
			} else if (paymentTerm.Term__c.contains('Transfer')) {
				paymentTermMapByTerm.put(paymentTerm.Term__c, paymentTerm);
			}
		}
		list<Decimal> accumulators = new List<Decimal>();
		Decimal accumulator = product?.ReservationPrice__c;
		accumulators.add(accumulator);
		Decimal netPrice = opportunity.NetPrice__c;
		Decimal unitPrice = opportunity.UnitPrice__c;
		System.debug('unitPrice: ' + unitPrice);
		List<OpportunityPayment__c> reservationOppPayment = new List<OpportunityPayment__c>();
		List<OpportunityPayment__c> contractOppPayment = new List<OpportunityPayment__c>();
		List<OpportunityPayment__c> installmentOppPayment = new List<OpportunityPayment__c>();
		List<OpportunityPayment__c> transferOppPayment = new List<OpportunityPayment__c>();
		for (OpportunityPayment__c oppPayment : oppPayments) {
			System.debug('oppPayment: ' + oppPayment);
			if (oppPayment.Term__c == 'Reservation') {
				reservationOppPayment.add(oppPayment);
			} else if (oppPayment.Term__c.contains('Contract')) {
				contractOppPayment.add(oppPayment);
			} else if (oppPayment.Term__c.contains('Installment')) {
				installmentOppPayment.add(oppPayment);
			} else if (oppPayment.Term__c.contains('Transfer')) {
				transferOppPayment.add(oppPayment);
			}
		}
		List<OpportunityPayment__c> resultReservationOppPaymentList = this.calculateReservationAmount(
			reservationOppPayment,
			accumulator
		);
		List<OpportunityPayment__c> resultContractOppPaymentList = this.calculateContractAmount(
			contractOppPayment,
			paymentTermMapByTerm,
			accumulators,
			unitPrice
		);
		List<OpportunityPayment__c> resultInstallmentOppPaymentList = this.calculateInstallmentAmount(
			installmentOppPayment,
			paymentTermMapByTerm,
			accumulators,
			unitPrice
		);
		List<OpportunityPayment__c> resultTransferOppPaymentList = this.calculateTransferAmount(
			transferOppPayment,
			accumulators,
			netPrice
		);

		resultOppPayments.addAll(resultReservationOppPaymentList);
		resultOppPayments.addAll(resultContractOppPaymentList);
		resultOppPayments.addAll(resultInstallmentOppPaymentList);
		resultOppPayments.addAll(resultTransferOppPaymentList);

		return resultOppPayments;
	}

	public List<OpportunityPayment__c> getClonedOpportunityPaymentByQuote(List<Quote__c> quotes) {
		List<OpportunityPayment__c> targetOpportunityPayments = new List<OpportunityPayment__c>();
		OpportunityPaymentSelector selector = OpportunityPaymentSelector.getInstance();
		Set<Id> oppIds = new Set<Id>();
		for (Quote__c quote : quotes) {
			oppIds.add(quote.Opportunity__c);
		}
		Map<Id, List<OpportunityPayment__c>> oppPaymentsMapByOppId = selector.getOpportunityPaymentsMapByOppId(oppIds);
		for (Quote__c quote : quotes) {
			List<OpportunityPayment__c> oppPayments = oppPaymentsMapByOppId.get(quote.Opportunity__c) == null
				? new List<OpportunityPayment__c>()
				: oppPaymentsMapByOppId.get(quote.Opportunity__c);
			for (OpportunityPayment__c oppPayment : oppPayments) {
				OpportunityPayment__c clonedOppPayment = oppPayment.clone(false, false, false, false);
				clonedOppPayment.Quote__c = quote.Id;
				clonedOppPayment.IsMasterData__c = false;
				targetOpportunityPayments.add(clonedOppPayment);
			}
		}
		return targetOpportunityPayments;
	}

	public List<OpportunityPayment__c> stampFieldFromReceiptLineItem(List<PaymentReceiptLineItem__c> receiptLineItems) {
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>();
		OpportunityPaymentSelector selector = OpportunityPaymentSelector.getInstance();
		Set<Id> oppPaymentIds = new Set<Id>();
		Map<Id, Decimal> totalReceivedAmountMapByOppPaymentId = new Map<Id, Decimal>();
		for (PaymentReceiptLineItem__c receiptLineItem : receiptLineItems) {
			System.debug('---test receiptLineItem.ReceivedAmount__c: ' + receiptLineItem.ReceivedAmount__c);
			oppPaymentIds.add(receiptLineItem.OpportunityPayment__c);
			if (!totalReceivedAmountMapByOppPaymentId.containsKey(receiptLineItem.OpportunityPayment__c)) {
				totalReceivedAmountMapByOppPaymentId.put(receiptLineItem.OpportunityPayment__c, 0);
			}
			Decimal receivedAmount = totalReceivedAmountMapByOppPaymentId.get(receiptLineItem.OpportunityPayment__c);
			System.debug('---test receivedAmount: ' + receivedAmount);
			totalReceivedAmountMapByOppPaymentId.put(receiptLineItem.OpportunityPayment__c , receivedAmount + receiptLineItem.ReceivedAmount__c);
		}
		Map<Id, OpportunityPayment__c> oppPaymentMapById = selector.getOpportunityPaymentMapById(oppPaymentIds);
		for (Id oppPaymentId : oppPaymentMapById.keySet()) {
			OpportunityPayment__c targetOppPayment = oppPaymentMapById.get(oppPaymentId);
			targetOppPayment.ReceivedAmount__c = targetOppPayment.ReceivedAmount__c == null
				? totalReceivedAmountMapByOppPaymentId.get(oppPaymentId)
				: targetOppPayment.ReceivedAmount__c + totalReceivedAmountMapByOppPaymentId.get(oppPaymentId);
			oppPayments.add(targetOppPayment);
		}
		return oppPayments;
	}

	public List<OpportunityPayment__c> cancelRecievedAmountFromReceiptLineItem(
		List<PaymentReceiptLineItem__c> receiptLineItems
	) {
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>();
		OpportunityPaymentSelector selector = OpportunityPaymentSelector.getInstance();
		Set<Id> oppPaymentIds = new Set<Id>();
		Map<Id, Decimal> totalReceivedAmountMapByOppPaymentId = new Map<Id, Decimal>();
		for (PaymentReceiptLineItem__c receiptLineItem : receiptLineItems) {
			oppPaymentIds.add(receiptLineItem.OpportunityPayment__c);
			if (!totalReceivedAmountMapByOppPaymentId.containsKey(receiptLineItem.OpportunityPayment__c)) {
				totalReceivedAmountMapByOppPaymentId.put(receiptLineItem.OpportunityPayment__c, 0);
			}
			Decimal receivedAmount = totalReceivedAmountMapByOppPaymentId.get(receiptLineItem.OpportunityPayment__c);
			totalReceivedAmountMapByOppPaymentId.put(receiptLineItem.OpportunityPayment__c , receivedAmount + receiptLineItem.ReceivedAmount__c);
		}
		Map<Id, OpportunityPayment__c> oppPaymentMapById = selector.getOpportunityPaymentMapById(oppPaymentIds);
		for (Id oppPaymentId : oppPaymentMapById.keySet()) {
			OpportunityPayment__c targetOppPayment = oppPaymentMapById.get(oppPaymentId);
			targetOppPayment.ReceivedAmount__c = targetOppPayment.ReceivedAmount__c == null
				? null
				: targetOppPayment.ReceivedAmount__c - totalReceivedAmountMapByOppPaymentId.get(oppPaymentId);
			oppPayments.add(targetOppPayment);
		}
		return oppPayments;
	}

	public Map<Id, List<OpportunityPayment__c>> getOppPaymentsMapByOppId(List<OpportunityPayment__c> oppPayments) {
		Map<Id, List<OpportunityPayment__c>> oppPaymentsMapByOppId = new Map<Id, List<OpportunityPayment__c>>();
		for (OpportunityPayment__c oppPayment : oppPayments) {
			List<OpportunityPayment__c> opportunityPayments = oppPaymentsMapByOppId.get(oppPayment.Opportunity__c);

			if (opportunityPayments == null) {
				oppPaymentsMapByOppId.put(oppPayment.Opportunity__c, new List<OpportunityPayment__c>{ oppPayment });
			} else {
				opportunityPayments.add(oppPayment);
			}
		}
		return oppPaymentsMapByOppId;
	}

	// ----- Start Private Service -----
	private List<OpportunityPayment__c> calculateReservationAmount(
		List<OpportunityPayment__c> reservationOppPayments,
		Decimal accumulator
	) {
		List<OpportunityPayment__c> adjustReservationAmountList = new List<OpportunityPayment__c>();
		for (OpportunityPayment__c oppPayment : reservationOppPayments) {
			oppPayment.Amount__c = accumulator;
			adjustReservationAmountList.add(oppPayment);
		}
		return adjustReservationAmountList;
	}

	/**
	 * Phase: 1
	* UAT Issue: DF-UAT-027
	*/
	private List<OpportunityPayment__c> calculateContractAmount(
		List<OpportunityPayment__c> contractOppPayments,
		Map<String, PaymentTerm__c> paymentTermMapByTerm,
		List<Decimal> accumulators,
		Decimal netPrice
	) {
		List<OpportunityPayment__c> adjustContractAmountList = new List<OpportunityPayment__c>();
		Decimal roundUpAmount;
		for (OpportunityPayment__c oppPayment : contractOppPayments) {
			PaymentTerm__c paymentTermByMap = paymentTermMapByTerm.get('Contract');
			System.debug('paymentTermByMap: ' + paymentTermByMap);
			if (paymentTermByMap.Percent__c == null) {
				oppPayment.Amount__c = paymentTermByMap.Amount__c / contractOppPayments.size();
				accumulators.add(oppPayment.Amount__c);
			} else {
				roundUpAmount = (netPrice * (paymentTermByMap.Percent__c / 100));
				//oppPayment.Amount__c = (netPrice * (paymentTermByMap.Percent__c / 100)) / contractOppPayments.size();
				oppPayment.Amount__c = (roundUpAmount.round(RoundingMode.UP))  / contractOppPayments.size();
				accumulators.add(oppPayment.Amount__c);
			}

			adjustContractAmountList.add(oppPayment);
		}
		return adjustContractAmountList;
	}

	/**
	 * Phase: 1
	* UAT Issue: DF-UAT-027
	*/
	private List<OpportunityPayment__c> calculateInstallmentAmount(
		List<OpportunityPayment__c> installmentOppPayments,
		Map<String, PaymentTerm__c> paymentTermMapByTerm,
		List<Decimal> accumulators,
		Decimal netPrice
	) {
		List<OpportunityPayment__c> adjustInstallmentAmountList = new List<OpportunityPayment__c>();
		Decimal roundUpAmount;
		for (OpportunityPayment__c oppPayment : installmentOppPayments) {
			PaymentTerm__c paymentTermByMap = paymentTermMapByTerm.get(oppPayment.Term__c);
			if (paymentTermByMap.Percent__c == null) {
				oppPayment.Amount__c = paymentTermByMap.Amount__c;
				accumulators.add(oppPayment.Amount__c);
			} else {
				roundUpAmount = (netPrice * (paymentTermByMap.Percent__c / 100));
				//oppPayment.Amount__c = (netPrice * (paymentTermByMap.Percent__c / 100));
				oppPayment.Amount__c = (roundUpAmount.round(RoundingMode.UP));
				accumulators.add(oppPayment.Amount__c);
			}
			adjustInstallmentAmountList.add(oppPayment);
		}
		return adjustInstallmentAmountList;
	}

	private List<OpportunityPayment__c> calculateTransferAmount(
		List<OpportunityPayment__c> transferOppPayments,
		List<Decimal> accumulators,
		Decimal netPrice
	) {
		List<OpportunityPayment__c> adjustTranferAmountList = new List<OpportunityPayment__c>();
		Decimal resultAccumulator = 0;
		for (Decimal accumulator : accumulators) {
			resultAccumulator = accumulator == null ? resultAccumulator + 0 : resultAccumulator + accumulator;
		}
		for (OpportunityPayment__c oppPayment : transferOppPayments) {
			oppPayment.Amount__c = netPrice == null ? netPrice : netPrice - resultAccumulator;
			adjustTranferAmountList.add(oppPayment);
		}
		return adjustTranferAmountList;
	}

	private List<OpportunityPayment__c> generateOpportunityPaymentsFromPaymentTerms(
		List<PaymentTerm__c> paymentTerms,
		Id paymentTermMasterId,
		Opportunity targetOpp
	) {
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>();
		OpportunityPayment__c oppFirstRecord = new OpportunityPayment__c(
			Order__c = 1,
			Name = '1',
			Term__c = 'Reservation',
			Opportunity__c = targetOpp.Id,
			UnitName__c = targetOpp.Unit__r.Name,
			ProjectName__c = targetOpp.Project__r.Name,
			// Unit
			// Project
			IsMasterData__c = true,
			PaymentTermMaster__c = paymentTermMasterId
		);
		oppPayments.add(oppFirstRecord);
		for (PaymentTerm__c payment : paymentTerms) {
			OpportunityPayment__c oppPayment = new OpportunityPayment__c();
			oppPayment.Order__c = payment.Order__c + 1;
			oppPayment.Name = String.valueOf(payment.Order__c + 1);
			oppPayment.Term__c = payment.Term__c;
			oppPayment.Opportunity__c = targetOpp.Id;
			oppPayment.UnitName__c = targetOpp.Unit__r.Name;
			oppPayment.ProjectName__c = targetOpp.Project__r.Name;
			oppPayment.IsMasterData__c = true;
			oppPayment.PaymentTermMaster__c = paymentTermMasterId;
			// Unit
			// Project
			oppPayments.add(oppPayment);
		}
		return oppPayments;
	}
	// ----- End Private Service -----

	// ----- Start Wrapper Class -----
	public class OpportunityPaymentWrapper {
		public Decimal amount;
		public Date dueDate;
		public Decimal order;
		public String term;
		public String id;
		public String oppId;
		public Boolean isNewRecord;
	}
	// ----- End Wrapper Class -----
}