force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityPaymentAdjustmentCtrlTest.cls
@isTest
public with sharing class OpportunityPaymentAdjustmentCtrlTest {
	@TestSetup
	static void makeData() {
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(
			testProduct.Id,
			15000000,
			20000000,
			10000000
		);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Foreign',
			null,
			testProject.Id
		);
		insert opportunity;
	}

	@isTest
	static void getOpportunityPaymentTest() {
		Test.startTest();
		DataMaker dataMaker = DataMaker.getInstance();
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			dataMaker.createOpportunityPayment(opp.Id, 'Reservation', 50000, Date.newInstance(2024, 10, 15), 1),
			dataMaker.createOpportunityPayment(opp.Id, 'Contract', 100000, Date.newInstance(2024, 10, 27), 2),
			dataMaker.createOpportunityPayment(opp.Id, 'Installment 1', 1000000, Date.newInstance(2024, 10, 27), 3),
			dataMaker.createOpportunityPayment(opp.Id, 'Transfer', 1000000, Date.newInstance(2025, 10, 27), 4)
		};
		insert oppPayments;
		List<OpportunityPayment__c> targetOppPayments = OpportunityPaymentAdjustmentController.getOpportunityPayment(
			opp.Id
		);
		System.assertEquals(oppPayments.size(), targetOppPayments.size());
		for (Integer i = 0; i < oppPayments.size(); i++) {
			System.assertEquals(oppPayments[i].Amount__c, targetOppPayments[i].Amount__c);
			System.assertEquals(oppPayments[i].DueDate__c, targetOppPayments[i].DueDate__c);
			System.assertEquals(oppPayments[i].Order__c, targetOppPayments[i].Order__c);
			System.assertEquals(oppPayments[i].Term__c, targetOppPayments[i].Term__c);
			System.assertEquals(oppPayments[i].Opportunity__c, targetOppPayments[i].Opportunity__c);
		}
		Test.stopTest();
	}

	@isTest
	static void upsertOppPaymentsTest() {
		Test.startTest();
		DataMaker dataMaker = DataMaker.getInstance();
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			dataMaker.createOpportunityPayment(opp.Id, 'Reservation', 50000, Date.newInstance(2024, 10, 15), 1),
			dataMaker.createOpportunityPayment(opp.Id, 'Contract', 100000, Date.newInstance(2024, 10, 27), 2),
			dataMaker.createOpportunityPayment(opp.Id, 'Installment 1', 1000000, Date.newInstance(2024, 10, 27), 3),
			dataMaker.createOpportunityPayment(opp.Id, 'Transfer', 1000000, Date.newInstance(2025, 10, 27), 4)
		};
		insert oppPayments;
		List<OpportunityPayment__c> resultOppPayments = [
			SELECT Id, Opportunity__c, Amount__c, DueDate__c, Order__c, Term__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :opp.Id
		];
		List<OpportunityPaymentService.OpportunityPaymentWrapper> oppPaymentWrappers = new List<OpportunityPaymentService.OpportunityPaymentWrapper>();
		for (OpportunityPayment__c oppPayment : resultOppPayments){
			OpportunityPaymentService.OpportunityPaymentWrapper reservationPaymentWrapper = new OpportunityPaymentService.OpportunityPaymentWrapper();
			reservationPaymentWrapper.amount = oppPayment.Amount__c + 100;
			reservationPaymentWrapper.dueDate = oppPayment.DueDate__c;
			reservationPaymentWrapper.order = oppPayment.Order__c;
			reservationPaymentWrapper.term = oppPayment.Term__c;
			reservationPaymentWrapper.id = oppPayment.Id;
			reservationPaymentWrapper.oppId = oppPayment.Opportunity__c;
			reservationPaymentWrapper.isNewRecord = false;
			oppPaymentWrappers.add(reservationPaymentWrapper);
		}
		String oppPaymentsJSON = JSON.serialize(oppPaymentWrappers);
		List<OpportunityPayment__c> upsertedOppPayment = OpportunityPaymentAdjustmentController.upsertOppPayments(oppPaymentsJSON);
		List<OpportunityPayment__c> oppPaymentsAfterUpserted = [
			SELECT Id, Opportunity__c, Amount__c, DueDate__c, Order__c, Term__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :opp.Id
		];
		System.assertEquals(oppPaymentsAfterUpserted.size(), resultOppPayments.size());
		for (Integer i = 0; i < oppPaymentsAfterUpserted.size(); i++) {
			System.assertEquals(oppPaymentsAfterUpserted[i].Amount__c, resultOppPayments[i].Amount__c + 100);
			System.assertEquals(oppPaymentsAfterUpserted[i].DueDate__c, resultOppPayments[i].DueDate__c);
			System.assertEquals(oppPaymentsAfterUpserted[i].Order__c, resultOppPayments[i].Order__c);
			System.assertEquals(oppPaymentsAfterUpserted[i].Term__c, resultOppPayments[i].Term__c);
			System.assertEquals(oppPaymentsAfterUpserted[i].Opportunity__c, resultOppPayments[i].Opportunity__c);
		}
		Test.stopTest();
	}

	@isTest
	static void deleteOppPaymentsTest(){
		Test.startTest();
		DataMaker dataMaker = DataMaker.getInstance();
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			dataMaker.createOpportunityPayment(opp.Id, 'Reservation', 50000, Date.newInstance(2024, 10, 15), 1),
			dataMaker.createOpportunityPayment(opp.Id, 'Contract', 100000, Date.newInstance(2024, 10, 27), 2),
			dataMaker.createOpportunityPayment(opp.Id, 'Installment 1', 1000000, Date.newInstance(2024, 10, 27), 3),
			dataMaker.createOpportunityPayment(opp.Id, 'Transfer', 1000000, Date.newInstance(2025, 10, 27), 4)
		};
		insert oppPayments;
		List<OpportunityPayment__c> resultOppPayments = [
			SELECT Id, Opportunity__c, Amount__c, DueDate__c, Order__c, Term__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :opp.Id
		];
		List<OpportunityPaymentService.OpportunityPaymentWrapper> oppPaymentWrappers = new List<OpportunityPaymentService.OpportunityPaymentWrapper>();
		for (OpportunityPayment__c oppPayment : resultOppPayments){
			OpportunityPaymentService.OpportunityPaymentWrapper reservationPaymentWrapper = new OpportunityPaymentService.OpportunityPaymentWrapper();
			reservationPaymentWrapper.amount = oppPayment.Amount__c + 100;
			reservationPaymentWrapper.dueDate = oppPayment.DueDate__c;
			reservationPaymentWrapper.order = oppPayment.Order__c;
			reservationPaymentWrapper.term = oppPayment.Term__c;
			reservationPaymentWrapper.id = oppPayment.Id;
			reservationPaymentWrapper.oppId = oppPayment.Opportunity__c;
			reservationPaymentWrapper.isNewRecord = false;
			oppPaymentWrappers.add(reservationPaymentWrapper);
		}
		String oppPaymentsJSON = JSON.serialize(oppPaymentWrappers);
		List<OpportunityPayment__c> deletedOppPayment = OpportunityPaymentAdjustmentController.deleteOppPayments(oppPaymentsJSON);
		List<OpportunityPayment__c> oppPaymentsAfterDeleted = [
			SELECT Id, Opportunity__c, Amount__c, DueDate__c, Order__c, Term__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :opp.Id
		];
		System.assertNotEquals(oppPaymentsAfterDeleted.size(), resultOppPayments.size());
		System.assertEquals(0, oppPaymentsAfterDeleted.size());
		Test.stopTest();
	}

	@isTest
	static void validateIsGrantedProfileProfileTest(){
		Test.startTest();
			Boolean isGrantedProfile = OpportunityPaymentAdjustmentController.validateIsGrantedProfileProfile();
			System.assert(isGrantedProfile);
		Test.stopTest();
	}
}