force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TransferredDate__c.field-meta.xml
<CustomField>
    <fullName>TransferredDate__c</fullName>
    <label>Transferred Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Not for Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TransferredDate__c.field-meta.xml
<CustomField>
    <fullName>TransferredDate__c</fullName>
    <label>Transferred Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Product2Service.cls
public with sharing class Product2Service {
	public Product2Service() {

	}
	public static Product2Service instance;

	public static Product2Service getInstance() {
		if (instance == null) {
			instance = new Product2Service();
		}
		return instance;
	}
	public List<Product2> changeUnitStageToBookOrSoldByOpportunityStage(List<Opportunity> opportunities){
		Product2Selector productSelector = Product2Selector.getInstance();
		List<Product2> productToUpdateList = new List<Product2>();
		Set<Id> productIds = new Set<Id>();
		for(Opportunity opp : opportunities){
			productIds.add(opp.Unit__c);
		}
		Map<Id,Product2> productMap = productSelector.getProduct2ById(productIds);
		for(Opportunity opp : opportunities){
			Product2 product = productMap.get(opp.Unit__c);
			if(opp.StageName == 'Reservation'){
				product.Status__c = 'Reserved';
				productToUpdateList.add(product);
			} else if (opp.StageName == 'Contract') {
				product.Status__c = 'Sold';
				productToUpdateList.add(product);
			}else if (opp.StageName == 'Transferred'){
				product.Status__c = 'Transferred';
				product.TransferredDate__c = Date.today();
				productToUpdateList.add(product);
			}
		}
		return productToUpdateList;
	}

	public List<Product2> changeUnitStatusToAvailableByClosedLostOpportunity(List<Opportunity> opportunities){
		Set<Id> productIds = new Set<Id>();
		Product2Selector selector = Product2Selector.getInstance();
		for (Opportunity opportunity : opportunities ){
			productIds.add(opportunity.Unit__c);
		}
		Map<Id,Product2> productMapById = selector.getProduct2ById(productIds);
		List<Product2> products = new List<Product2>();
		for (Product2 product : productMapById.values()){
			product.Status__c = 'Available';
			product.TransferredDate__c = null;
			products.add(product);
		}
		if(!products.isEmpty()){
			update products;
		}
		return products;
	}

}