force-app/main/default/objects/b8log_Application_Log__c/b8log_Application_Log__c.object-meta.xml
<CustomObject>
    <label>b8log Application Log</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>b8log  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/b8log_Application_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/b8log_Integration_Log__c/b8log_Integration_Log__c.object-meta.xml
<CustomObject>
    <label>b8log Integration Log</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{0000000000}</displayFormat>
        <label>b8log Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/b8log_Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>REQUIRED_RETRY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/b8int_SfdcCustomApiCallout_Test.cls
@isTest
public class b8int_SfdcCustomApiCallout_Test {

    public class b8int_SfdcCustomApiCalloutMockResp implements HttpCalloutMock {
    
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), b8int_SfdcCustomApiCallout.RequestDataModel.class);
            b8int_SfdcCustomApiCallout.RequestDataModel requestData = (b8int_SfdcCustomApiCallout.RequestDataModel)requestDataObj;
            b8int_SfdcCustomApiCallout.ResponseDataModel responseData = new b8int_SfdcCustomApiCallout.ResponseDataModel();
            responseData.isSuccess = requestData.expectedSuccessStatus;
    
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseData));
            res.setStatusCode(200);
            return res;
        }
    }

    @isTest static void test_success() {
        Test.setMock(HttpCalloutMock.class, new b8int_SfdcCustomApiCallout_Test.b8int_SfdcCustomApiCalloutMockResp());
        b8int_SfdcCustomApiCallout callout = new b8int_SfdcCustomApiCallout();
        callout.expectedSuccessStatus = true;

        Test.startTest();
        callout.execute();
        Test.stopTest();

        List<b8log_Integration_Log__c> intLogs = [SELECT Id, Status__c FROM b8log_Integration_Log__c];
        System.assertEquals(1, intLogs.size());
        System.assertEquals(b8log.IntegrationStatus.SUCCESS.name(), intLogs.get(0).Status__c);

        List<b8log_Application_Log__c> appLogs = [SELECT Id, Type__c FROM b8log_Application_Log__c];
        System.assertEquals(1, appLogs.size());
        System.assertEquals(b8log.AppLogType.INFO.name(), appLogs.get(0).Type__c);
    }

    @isTest static void test_failed() {
        Test.setMock(HttpCalloutMock.class, new b8int_SfdcCustomApiCallout_Test.b8int_SfdcCustomApiCalloutMockResp());
        b8int_SfdcCustomApiCallout callout = new b8int_SfdcCustomApiCallout();
        callout.expectedSuccessStatus = false;

        Test.startTest();
        callout.execute();
        Test.stopTest();

        List<b8log_Integration_Log__c> intLogs = [SELECT Id, Status__c FROM b8log_Integration_Log__c];
        System.assertEquals(1, intLogs.size());
        System.assertEquals(b8log.IntegrationStatus.REQUIRED_RETRY.name(), intLogs.get(0).Status__c);

        List<b8log_Application_Log__c> appLogs = [SELECT Id, Type__c FROM b8log_Application_Log__c];
        System.assertEquals(1, appLogs.size());
        System.assertEquals(b8log.AppLogType.ERROR.name(), appLogs.get(0).Type__c);
    }
}