force-app/main/default/objects/NameFormattingMasterData__c/NameFormattingMasterData__c.object-meta.xml
<CustomObject>
    <description>สำหรับเก็บข้อมูล Backend value ต่างๆ เช่น Running Number</description>
    <label>Name Formatting Master Data</label>
    <nameField>
        <displayFormat>NFMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Formatting Master Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NameFormattingMasterData__c/fields/CurrentRunningNumber__c.field-meta.xml
<CustomField>
    <fullName>CurrentRunningNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Current Running number</description>
    <inlineHelpText>Start with 1</inlineHelpText>
    <label>Current Running Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/DocumentTemplateMappingType__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateMappingType__c</fullName>
    <label>Document Template Mapping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Client Offer</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
            <value>
                <fullName>Supplementary Agreement</fullName>
            </value>
            <value>
                <fullName>Payment Summary</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <inlineHelpText>Please add when a type of record is &apos;running number&apos;</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>ClientOffer__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>PaymentReceipt__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/RunningFormat__c.field-meta.xml
<CustomField>
    <fullName>RunningFormat__c</fullName>
    <description>store format of each running key</description>
    <label>Running Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/RunningKey__c.field-meta.xml
<CustomField>
    <fullName>RunningKey__c</fullName>
    <description>Key for running number use in back-end</description>
    <label>Running Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NameFormattingMasterDataSelectorTest.cls
@isTest
public with sharing class NameFormattingMasterDataSelectorTest {
	@isTest
	static void getByObjTypePurposeDocTemplateTest() {
		NameFormattingMasterData__c runningNumberFormatDocument = new NameFormattingMasterData__c(
            ObjectName__c = 'Contract',
            RunningFormat__c = 'Contract_{Account.Name}_{StartDate:FORMATDATETH:d MMMM yyyy}_{EndDate:FORMATDATETH:d MMMM yyyy}_{RUNNINGNUMBER:0000}',
            RunningPurpose__c = 'Document',
            Type__c = 'Format',
            CurrentRunningNumber__c = 1,
            DocumentTemplateMappingType__c = 'Contract'
        );
		insert runningNumberFormatDocument;

		List<NameFormattingMasterData__c> result = NameFormattingMasterDataSelector.getInstance().getByObjTypePurposeDocTemplate(
			'Contract',
			'Format',
			'Document',
			'Contract'
		);

		System.assertEquals(runningNumberFormatDocument.ObjectName__c, result.get(0).ObjectName__c);
		System.assertEquals(runningNumberFormatDocument.Type__c, result.get(0).Type__c);
		System.assertEquals(runningNumberFormatDocument.RunningFormat__c, result.get(0).RunningFormat__c);
		System.assertEquals(runningNumberFormatDocument.RunningPurpose__c, result.get(0).RunningPurpose__c);
		System.assertEquals(runningNumberFormatDocument.DocumentTemplateMappingType__c, result.get(0).DocumentTemplateMappingType__c);
	}

	@isTest
	static void getByObjTypePurposeDocTemplateRunningKeyTest() {
		NameFormattingMasterData__c runningNumberFormatDocument = new NameFormattingMasterData__c(
			ObjectName__c = 'Contract',
			RunningFormat__c = null,
			RunningKey__c = 'Contract_United Oil_{RUNNINGNUMBER:0000}',
			RunningPurpose__c = 'Object',
			Type__c = 'Running Number',
			CurrentRunningNumber__c = 5
		);
		insert runningNumberFormatDocument;

		Set<String> runningKeySet = new Set<String>{
			'Contract_United Oil_{RUNNINGNUMBER:0000}'
		};

		List<NameFormattingMasterData__c> result = NameFormattingMasterDataSelector.getInstance().getByObjTypePurposeDocTemplateRunningKey(
			'Contract',
			'Running Number',
			'Object',
			null,
			runningKeySet
		);

		System.assertEquals(runningNumberFormatDocument.ObjectName__c, result.get(0).ObjectName__c);
		System.assertEquals(runningNumberFormatDocument.Type__c, result.get(0).Type__c);
		System.assertEquals(runningNumberFormatDocument.RunningFormat__c, result.get(0).RunningFormat__c);
		System.assertEquals(runningNumberFormatDocument.RunningKey__c, result.get(0).RunningKey__c);
		System.assertEquals(runningNumberFormatDocument.CurrentRunningNumber__c, result.get(0).CurrentRunningNumber__c);
		System.assertEquals(runningNumberFormatDocument.DocumentTemplateMappingType__c, result.get(0).DocumentTemplateMappingType__c);
	}
}