force-app/main/default/objects/NameFormattingMasterData__c/NameFormattingMasterData__c.object-meta.xml
<CustomObject>
    <description>สำหรับเก็บข้อมูล Backend value ต่างๆ เช่น Running Number</description>
    <label>Name Formatting Master Data</label>
    <nameField>
        <displayFormat>NFMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Formatting Master Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NameFormattingMasterData__c/fields/CurrentRunningNumber__c.field-meta.xml
<CustomField>
    <fullName>CurrentRunningNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Current Running number</description>
    <inlineHelpText>Start with 1</inlineHelpText>
    <label>Current Running Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/DocumentTemplateMappingType__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateMappingType__c</fullName>
    <label>Document Template Mapping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Client Offer</fullName>
            </value>
            <value>
                <fullName>Quotation</fullName>
            </value>
            <value>
                <fullName>Supplementary Agreement</fullName>
            </value>
            <value>
                <fullName>Payment Summary</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <inlineHelpText>Please add when a type of record is &apos;running number&apos;</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>ClientOffer__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>PaymentReceipt__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/RunningFormat__c.field-meta.xml
<CustomField>
    <fullName>RunningFormat__c</fullName>
    <description>store format of each running key</description>
    <label>Running Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/fields/RunningKey__c.field-meta.xml
<CustomField>
    <fullName>RunningKey__c</fullName>
    <description>Key for running number use in back-end</description>
    <label>Running Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NameFormattingMasterDataSelector.cls
public without sharing class NameFormattingMasterDataSelector {
    public static NameFormattingMasterDataSelector instance;

    public static NameFormattingMasterDataSelector getInstance() {
        if (instance == null) {
            instance = new NameFormattingMasterDataSelector();
        }
        return instance;
    }

	public List<NameFormattingMasterData__c> getByObjTypePurposeDocTemplate(
        String objectName,
        String type,
        String runningPurpose,
        String docTemplateMappingType
    ){
		return [
            SELECT ObjectName__c, Type__c, RunningFormat__c, RunningPurpose__c, DocumentTemplateMappingType__c
            FROM NameFormattingMasterData__c
            WHERE ObjectName__c =: objectName
                AND Type__c =: type
                AND RunningPurpose__c =: runningPurpose
                AND DocumentTemplateMappingType__c =: docTemplateMappingType
        ];
	}

	public List<NameFormattingMasterData__c> getByObjTypePurposeDocTemplateRunningKey(
        String objectName,
        String type,
        String runningPurpose,
        String docTemplateMappingType,
        Set<String> runningKeySet
    ){
		return [
            SELECT ObjectName__c, Type__c, RunningFormat__c, RunningKey__c, CurrentRunningNumber__c, DocumentTemplateMappingType__c
            FROM NameFormattingMasterData__c
            WHERE ObjectName__c =: objectName
                AND Type__c =: type
                AND RunningPurpose__c =: runningPurpose
                AND DocumentTemplateMappingType__c =: docTemplateMappingType
                AND RunningKey__c IN: runningKeySet
        ];
	}
}