force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/GLKey__c.field-meta.xml
<CustomField>
    <fullName>GLKey__c</fullName>
    <formula>TRIM(&quot;IV_GL_&quot;&amp; Opportunity__r.Account.AccountCode__c + &quot;_&quot; + Opportunity__r.Project__r.ProjectCode__c + &quot;_&quot; + Opportunity__r.Unit__r.ProductCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastCreatedStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastCreatedStatusInPojjaman__c</fullName>
    <label>Last Created Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastGLStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastGLStatusInPojjaman__c</fullName>
    <label>Last GL Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>OpportunityPayment__r.Term__c</formula>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateInvoiceApiCalloutBatch.cls
public with sharing class CreateInvoiceApiCalloutBatch implements Database.Batchable<SObject>, Database.AllowsCallouts{
    public CreateInvoiceApiCalloutBatch() {

    }

	public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT
                Id,
                Opportunity__r.Account.AccountCode__c,
                Opportunity__r.Project__r.ProjectCode__c,
                CreatedDate,
                InvoiceNo__c,
                GLKey__c,
                ResponseCode__c,
                ResponseMessage__c,
                LastIntegrationDateTime__c,
                LastCreatedStatusInPojjaman__c,
                LastGLStatusInPojjaman__c,
				CoBuyerAccountCode__c,
                (
                    SELECT
                        Id,
                        Invoice__r.Opportunity__r.Unit__r.ProductCode,
                        OpportunityPayment__r.Remaining__c,
                        Term__c,
                        Amount__c,
                        Status__c,
                        DueDate__c,
                        ResponseCode__c,
                        ResponseMessage__c,
                        LastIntegrationDateTime__c
                    FROM InvoiceLineItems__r
                )
            FROM Invoice__c
            WHERE
                (LastModifiedDate = TODAY
                OR LastCreatedStatusInPojjaman__c = 'Fail'
				OR LastCreatedStatusInPojjaman__c = null)
			ORDER BY CreatedDate ASC
        ]);
    }

	public void execute(Database.BatchableContext bc, List<SObject> scope) {
		CreateInvoiceApiCallout callout = new CreateInvoiceApiCallout(scope);
        callout.execute();
    }

	public void finish(Database.BatchableContext bc) {
        System.debug('Batch processing finished.');
		// execute next batch
		CreateReceiptApiCalloutBatch createReceiptApiCalloutBatch = new CreateReceiptApiCalloutBatch();
        Database.executeBatch(createReceiptApiCalloutBatch, 25);
    }
}