force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/AccountNameTH__c.field-meta.xml
<CustomField>
    <fullName>AccountNameTH__c</fullName>
    <label>Account Name (TH)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <formula>AddressNoTH__c + &apos; &apos; +   SubDistrictTH__c  + &apos; &apos; +  DistrictTH__c + &apos;   &apos; +  ProvinceTH__c + &apos; &apos; +  ZipCodeTH__c  + &apos; &apos; +  Text(CountryTH__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address TH</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CountryEN__c.field-meta.xml
<CustomField>
    <fullName>CountryEN__c</fullName>
    <label>Country EN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CountryTH__c.field-meta.xml
<CustomField>
    <fullName>CountryTH__c</fullName>
    <label>Country TH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryTH</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerStatus__c.field-meta.xml
<CustomField>
    <fullName>CustomerStatus__c</fullName>
    <description>สถานะของ Customer</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FaxExt__c.field-meta.xml
<CustomField>
    <fullName>FaxExt__c</fullName>
    <label>Fax Ext.</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IDCardNumber__c.field-meta.xml
<CustomField>
    <fullName>IDCardNumber__c</fullName>
    <label>Identification Card No.</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gourmet Cooking Classes with Celebrity Chefs</fullName>
            </value>
            <value>
                <fullName>Private Wine Tasting</fullName>
            </value>
            <value>
                <fullName>Luxury Travel and Bespoke Holidays</fullName>
            </value>
            <value>
                <fullName>Art Collecting and Private Gallery Tours</fullName>
            </value>
            <value>
                <fullName>Philanthropy and Social Impact Investing</fullName>
            </value>
            <value>
                <fullName>Private Aviation (Owning Jets, Helicopters, Chartering Services)</fullName>
            </value>
            <value>
                <fullName>Yacht Ownership and Sailing Regattas</fullName>
            </value>
            <value>
                <fullName>Golf Club Membership and Exclusive Golf Tournaments</fullName>
            </value>
            <value>
                <fullName>Polo and Equestrian Sports</fullName>
            </value>
            <value>
                <fullName>High-End Jewelry and Watch Collecting</fullName>
            </value>
            <value>
                <fullName>Exclusive Fashion Shows and Haute Couture</fullName>
            </value>
            <value>
                <fullName>Rare Vintage Car Collecting and Racing Events</fullName>
            </value>
            <value>
                <fullName>Luxury Real Estate Investment and Property Development</fullName>
            </value>
            <value>
                <fullName>Private Members’ Clubs and Networking Societies</fullName>
            </value>
            <value>
                <fullName>Private Concerts and Cultural Events</fullName>
            </value>
            <value>
                <fullName>Health and Wellness Retreats with Renowned Practitioners</fullName>
            </value>
            <value>
                <fullName>Exclusive Culinary Experiences (Michelin-starred Dining)</fullName>
            </value>
            <value>
                <fullName>Adventure Travel</fullName>
            </value>
            <value>
                <fullName>Collecting Rare Books and Manuscripts</fullName>
            </value>
            <value>
                <fullName>Antique Furniture and Decorative Arts</fullName>
            </value>
            <value>
                <fullName>Luxury Sustainable Living and Off-Grid Properties</fullName>
            </value>
            <value>
                <fullName>Scuba Diving in Remote and Unexplored Locations</fullName>
            </value>
            <value>
                <fullName>Exclusive VIP Access to Fashion Week Events</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LastContactIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>LastContactIntegrationStatus__c</fullName>
    <label>Last Contact Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingAddressEN__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(MailingAddressNoEN__c)), MailingAddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MaillingSubDistrictEN__c)), MaillingSubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingDistrictEN__c)), MailingDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingProvinceEN__c)), MailingProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingZipCodeEN__c)), MailingZipCodeEN__c &amp; &quot;  &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(MailingCountryEN__c))), TEXT(MailingCountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingAddressTH__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressTH__c</fullName>
    <formula>MailingAddressNoTH__c  + &apos; &apos; +  MaillingSubDistrictTH__c  + &apos; &apos; +  MailingDistrictTH__c  + &apos; &apos; +  MailingProvinceTH__c  + &apos; &apos; +  MailingZipCodeTH__c  + &apos; &apos; + Text( MailingCountryTH__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address TH</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PassportNo__c.field-meta.xml
<CustomField>
    <fullName>PassportNo__c</fullName>
    <description>หมายเลขหนังสือเดินทาง</description>
    <label>Passport Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxID__c.field-meta.xml
<CustomField>
    <fullName>TaxID__c</fullName>
    <description>เลขที่ภาษี</description>
    <label>Tax ID</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Co_Owner_Corporate.recordType-meta.xml
<RecordType>
    <fullName>Co_Owner_Corporate</fullName>
    <active>true</active>
    <label>Co-Owner - Corporate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Co_Owner_Individual.recordType-meta.xml
<RecordType>
    <fullName>Co_Owner_Individual</fullName>
    <active>true</active>
    <label>Co-Owner - Individual</label>
</RecordType>

force-app/main/default/classes/CreateCustomerApiCalloutBatch.cls
public class CreateCustomerApiCalloutBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public CreateCustomerApiCalloutBatch() {
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    AccountCode__c,
                    Name,
                    AccountNameTH__c,
                    AddressEN__c,
                    AddressTH__c,
                    RecordType.DeveloperName,
                    MailingAddressEN__c,
                    MailingAddressTH__c,
                    Phone,
                    Fax,
                    FaxExt__c,
                    Email__c,
                    TaxID__c,
                    IDCardNumber__c,
                    PassportNo__c,
					Nationality__c,
                    CountryEN__c,
                    CountryTH__c,
                    CustomerStatus__c,
                    Interest__c,
                    Active__c,
                    ResponseCode__c,
                    ResponseMessage__c,
                    LastIntegrationDateTime__c,
                    LastModifiedDate,
					LastContactIntegrationStatus__c,
                    (
                        SELECT
                            Id,
                            FirstName,
                            LastName,
                            Email,
                            MobilePhone,
                            Position__c,
                            IsPrimaryContact__c,
                            Active__c,
                            ResponseCode__c,
                            ResponseMessage__c,
                            LastIntegrationDateTime__c,
                            LastModifiedDate,
							LastCreatedStatusInPojjaman__c
                        FROM Contacts
                    )
                FROM Account
                WHERE
                    (RecordType.DeveloperName = 'Co_Owner_Corporate'
                    OR RecordType.DeveloperName = 'Co_Owner_Individual')
                    AND (ResponseCode__c != 'SC'
                    OR LastModifiedDate = TODAY
					OR LastContactIntegrationStatus__c = 'Fail')
					AND Name != 'Dummy for send Email'
				ORDER BY CreatedDate ASC
            ]
        );
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        CreateCustomerApiCallout callout = new CreateCustomerApiCallout(scope);
        callout.execute();
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch processing finished.');
        // execute next batch
		CreateInvoiceApiCalloutBatch createInvoiceApiCalloutBatch = new CreateInvoiceApiCalloutBatch();
        Database.executeBatch(createInvoiceApiCalloutBatch, 25);
    }
}