force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GLDate__c.field-meta.xml
<CustomField>
    <fullName>GLDate__c</fullName>
    <formula>Opportunity__r.ClosedLostDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GLKey__c.field-meta.xml
<CustomField>
    <fullName>GLKey__c</fullName>
    <formula>TRIM(&quot;IV_GL_&quot;&amp; Opportunity__r.Account.AccountCode__c + &quot;_&quot; + Opportunity__r.Project__r.ProjectCode__c + &quot;_&quot; + Opportunity__r.Unit__r.ProductCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastGLStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastGLStatusInPojjaman__c</fullName>
    <label>Last GL Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>running ของการ item ใน invoice</description>
    <label>Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastGLStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastGLStatusInPojjaman__c</fullName>
    <label>Last GL Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/GLDate__c.field-meta.xml
<CustomField>
    <fullName>GLDate__c</fullName>
    <description>For send to Pojjaman</description>
    <formula>Opportunity__r.ClosedLostDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/GLKey__c.field-meta.xml
<CustomField>
    <fullName>GLKey__c</fullName>
    <formula>TRIM(&quot;RP_GL_&quot;&amp;  Opportunity__r.Account.AccountCode__c + &quot;_&quot; +  Opportunity__r.Project__r.ProjectCode__c +  &quot;_&quot;  +  Opportunity__r.Unit__r.ProductCode  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <formula>if( ISBLANK(Text(CancelReason__c)),false,True)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GLApiCallout.cls
public with sharing class GLApiCallout extends b8int_BaseHttpCallout {
	private List<Opportunity> opportunities = new List<Opportunity>();

	public GLApiCallout(List<Opportunity> opportunities) {
		super('GL');
		this.opportunities = opportunities;
		this.setCalloutType(b8int_BaseHttpCallout.HttpCalloutType.REALTIME);
		this.setIsRequireRetry(false);
		this.setMethod(b8int_BaseHttpRequest.HttpMethod.POST);
		this.setClient(new GLApiClient());
		this.setContentType(b8int_BaseHttpRequest.ContentType.JSON);
		this.setEndpoint('api/CityDynamic/CreateFN_GL');
		this.setRequestDataModelClass(PojjamanDataModel.FNGLDocRequest.class);
		this.setResponseDataModelClass(PojjamanDataModel.ResponseDataModel.class);
	}

	public override Object buildRequestDataModel() {
		List<PojjamanDataModel.FNGLDocRequest> requestDataModels = new List<PojjamanDataModel.FNGLDocRequest>();
		PaymentReceiptSelector receiptSelector = PaymentReceiptSelector.getInstance();
		InvoiceSelector invoiceSelector = InvoiceSelector.getInstance();
		Set<Id> receiptIds = new Set<Id>();
		Set<Id> invoiceIds = new Set<Id>();
		Set<Id> oppIds = new Set<Id>();
		for (Opportunity opportunity : opportunities) {
			oppIds.add(opportunity.Id);
			List<PaymentReceipt__c> paymentReceipts = opportunity.PaymentReceipt__r;
			for (PaymentReceipt__c paymentReceipt : paymentReceipts) {
				if (
					paymentReceipt.IsCancel__c &&
					(paymentReceipt.CancelReason__c == GlobalConstants.RECEIPT_LOST_REASON_CANCELREFUND ||
					paymentReceipt.CancelReason__c == GlobalConstants.RECEIPT_LOST_REASON_CANCELFORFEIT ||
					paymentReceipt.CancelReason__c == GlobalConstants.RECEIPT_LOST_REASON_TERMINATIONREFUND ||
					paymentReceipt.CancelReason__c == GlobalConstants.RECEIPT_LOST_REASON_TERMINATIONFORFEIT) &&
					(paymentReceipt.LastGLStatusInPojjaman__c == null ||
					paymentReceipt.LastGLStatusInPojjaman__c == 'Fail')
				) {
					receiptIds.add(paymentReceipt.Id);
				}
			}
			List<Invoice__c> invoices = opportunity.Invoices__r;
			for (Invoice__c invoice : invoices) {
				if (invoice.LastGLStatusInPojjaman__c == null || invoice.LastGLStatusInPojjaman__c == 'Fail') {
					invoiceIds.add(invoice.Id);
				}
			}
		}
		// add invoice which still has remaining > 0 to GL
		Map<Id, Invoice__c> invoiceWithInvoiceLineItemsMapById = invoiceSelector.getInvoiceWithInvoiceLineItemsMapById(
			invoiceIds
		);
		List<Invoice__c> invoices = invoiceWithInvoiceLineItemsMapById.values() == null ? new List<Invoice__c>() : invoiceWithInvoiceLineItemsMapById.values();
		for (Invoice__c invoice : invoices) {
			InvoiceLineItem__c invoiceLineItem = invoice.InvoiceLineItems__r[0];
			if (invoiceLineItem.OpportunityPayment__r.Remaining__c > 0) {
				PojjamanDataModel.FNGLDocRequest requestDataModel = new PojjamanDataModel.FNGLDocRequest();
				requestDataModel.CustomerCode = invoice.Opportunity__r.Account.AccountCode__c;
				requestDataModel.ProjectCode = invoice.Opportunity__r.Project__r.ProjectCode__c;
				requestDataModel.SFDocId = invoice.Id;
				requestDataModel.DocDate = invoice.CreatedDate.date();
				requestDataModel.DocType = 'GL';
				requestDataModel.InvoiceCode = invoice.InvoiceNo__c;
				requestDataModel.Indicator = 2;
				requestDataModel.GroupKey = invoice.GLKey__c;
				System.debug('** test **: ' + invoice.GLKey__c);
				requestDataModel.GLDate = invoice.GLDate__c;
				List<PojjamanDataModel.FNGLDocLineRequest> docLines = new List<PojjamanDataModel.FNGLDocLineRequest>();
				PojjamanDataModel.FNGLDocLineRequest docLine = new PojjamanDataModel.FNGLDocLineRequest();
				docLine.LineNumber = Integer.valueOf(invoiceLineItem.LineNumber__c);
				docLine.UnitCode = invoiceLineItem.Invoice__r.Opportunity__r.Unit__r.ProductCode;
				docLine.Type = invoiceLineItem.Term__c;
				docLine.Amount = invoiceLineItem.Amount__c;
				docLine.SFDocLineId = invoiceLineItem.Id;
				docLine.Status = invoiceLineItem.Status__c;
				docLine.DueDate = invoiceLineItem.DueDate__c;
				docLines.add(docLine);
				requestDataModel.DocLine = docLines;
				requestDataModels.add(requestDataModel);
			}
		}
		// add receipts to GL
		Map<Id, PaymentReceipt__c> receiptWithReceiptLineItemsMapById = receiptSelector.getPaymentReceiptWithLineItemMapById(
			receiptIds
		);
		List<PaymentReceipt__c> receipts = receiptWithReceiptLineItemsMapById.values() == null ? new List<PaymentReceipt__c>() : receiptWithReceiptLineItemsMapById.values();
		for (PaymentReceipt__c receipt : receipts) {
			if (receipt.ReceiptType__c != GlobalConstants.RECEIPT_TYPE_REFUND_FORFEIT ){
				PojjamanDataModel.FNGLDocRequest requestDataModel = new PojjamanDataModel.FNGLDocRequest();
				requestDataModel.CustomerCode = receipt.Opportunity__r.Account.AccountCode__c;
				requestDataModel.ProjectCode = receipt.Opportunity__r.Project__r.ProjectCode__c;
				requestDataModel.SFDocId = receipt.Id;
				requestDataModel.DocDate = receipt.CreatedDate.date();
				requestDataModel.DocType = 'GL';
				requestDataModel.ReceiptCode = receipt.ReceiptNo__c;
				requestDataModel.Indicator = 0;
				requestDataModel.GroupKey = receipt.GLKey__c;
				System.debug('** test **: ' + receipt.GLKey__c);
				requestDataModel.GLDate = receipt.GLDate__c;
				List<PaymentReceiptLineItem__c> receiptLineItems = receipt.Payment_Transactions__r;
				List<PojjamanDataModel.FNGLDocLineRequest> docLines = new List<PojjamanDataModel.FNGLDocLineRequest>();
				Integer lineNumber = 1;
				for (PaymentReceiptLineItem__c receiptLineItem : receiptLineItems) {
					PojjamanDataModel.FNGLDocLineRequest docLine = new PojjamanDataModel.FNGLDocLineRequest();
					docLine.LineNumber = lineNumber;
					docLine.UnitCode = receiptLineItem.PaymentReceipt__r.Opportunity__r.Unit__r.ProductCode;
					docLine.Type = receiptLineItem.OpportunityPayment__r.Term__c;
					docLine.Amount = receiptLineItem.ReceivedAmount__c;
					docLine.isDebit = true;
					docLine.SFDocLineId = receiptLineItem.Id;
					docLine.Status = receiptLineItem.Status__c;
					docLine.RefInvoiceId = receiptLineItem.InvoiceLineItem__r.Invoice__c;
					docLines.add(docLine);
					lineNumber++;
				}
				requestDataModel.DocLine = docLines;
				requestDataModels.add(requestDataModel);
			}
		}
		// add refund/forfeit detail
		Map<Id, List<PaymentReceipt__c>> refundForfeitPaymentReceiptByOppIdMapByOppId = receiptSelector.getRefundForfeitPaymentReceiptByOppIdMapByOppId(oppIds);
		for (Id oppId : oppIds){
			List<PaymentReceipt__c> refundForfeitPaymentReceipt = refundForfeitPaymentReceiptByOppIdMapByOppId.get(oppId) == null ? new List<PaymentReceipt__c>() : refundForfeitPaymentReceiptByOppIdMapByOppId.get(oppId);
			for (PaymentReceipt__c receipt : refundForfeitPaymentReceipt) {
				PojjamanDataModel.FNGLDocRequest requestDataModel = new PojjamanDataModel.FNGLDocRequest();
				requestDataModel.CustomerCode = receipt.Opportunity__r.Account.AccountCode__c;
				requestDataModel.ProjectCode = receipt.Opportunity__r.Project__r.ProjectCode__c;
				requestDataModel.SFDocId = receipt.Id;
				requestDataModel.DocDate = receipt.CreatedDate.date();
				requestDataModel.DocType = 'GL';
				requestDataModel.ReceiptCode = receipt.ReceiptNo__c;
				requestDataModel.Indicator = 0;
				requestDataModel.GroupKey = receipt.GLKey__c;
				System.debug('** test refund forfeit**: ' + receipt.GLKey__c);
				requestDataModel.GLDate = receipt.GLDate__c;
				List<PaymentReceiptLineItem__c> receiptLineItems = receipt.Payment_Transactions__r;
				List<PojjamanDataModel.FNGLDocLineRequest> docLines = new List<PojjamanDataModel.FNGLDocLineRequest>();
				Integer lineNumber = 1;
				for (PaymentReceiptLineItem__c receiptLineItem : receiptLineItems) {
					// NOT Include Operation line item
					if (receiptLineItem.ReceiptLineItemType__c != 'Operation'){
						PojjamanDataModel.FNGLDocLineRequest docLine = new PojjamanDataModel.FNGLDocLineRequest();
						docLine.LineNumber = lineNumber;
						docLine.UnitCode = receiptLineItem.PaymentReceipt__r.Opportunity__r.Unit__r.ProductCode;
						docLine.Type = receiptLineItem.ReceiptLineItemType__c;
						docLine.Amount = receiptLineItem.ReceivedAmount__c;
						docLine.isDebit = false;
						docLine.SFDocLineId = receiptLineItem.Id;
						docLine.Status = receiptLineItem.Status__c;
						docLine.RefInvoiceId = null;
						docLines.add(docLine);
						lineNumber++;
					}
				}
				requestDataModel.DocLine = docLines;
				requestDataModels.add(requestDataModel);
			}
		}
		return requestDataModels;
	}

	public override Boolean processFailedResponse() {
		b8int_BaseHttpRequest request = this.getRequestModel();
		b8int_BaseHttpResponse response = this.getResponseModel();
		List<PojjamanDataModel.FNGLDocRequest> targetRequests = (List<PojjamanDataModel.FNGLDocRequest>) request.getRequestBody();
		String errorDescription = response.getDescription();
		PaymentReceiptSelector receiptSelector = PaymentReceiptSelector.getInstance();
		InvoiceSelector invoiceSelector = InvoiceSelector.getInstance();
		List<Invoice__c> updatedInvoices = new List<Invoice__c>();
		List<InvoiceLineItem__c> updatedInvoiceLineItems = new List<InvoiceLineItem__c>();
		List<PaymentReceipt__c> updatedReceipts = new List<PaymentReceipt__c>();
		List<PaymentReceiptLineItem__c> updatedReceiptLineItems = new List<PaymentReceiptLineItem__c>();
		Set<Id> docIds = new Set<Id>();
		for (PojjamanDataModel.FNGLDocRequest eachRequest : targetRequests) {
			docIds.add(eachRequest.SFDocId);
		}
		Map<Id, Invoice__c> invoiceWithInvoiceLineItemsMapById = invoiceSelector.getInvoiceWithInvoiceLineItemsMapById(
			docIds
		);
		Map<Id, PaymentReceipt__c> receiptWithReceiptLineItemsMapById = receiptSelector.getPaymentReceiptWithLineItemMapById(
			docIds
		);
		Set<Id> oppIds = new Set<Id>();
		for (PojjamanDataModel.FNGLDocRequest eachRequest : targetRequests) {
			if (invoiceWithInvoiceLineItemsMapById.containsKey(eachRequest.SFDocId)) {
				Invoice__c targetInvoice = invoiceWithInvoiceLineItemsMapById.get(eachRequest.SFDocId);
				oppIds.add(targetInvoice.Opportunity__c);
				// response for invoice
				Invoice__c invoice = new Invoice__c(
					Id = eachRequest.SFDocId,
					ResponseCode__c = 'ERR',
					ResponseMessage__c = errorDescription,
					LastIntegrationDateTime__c = System.now(),
					LastGLStatusInPojjaman__c = 'Fail'
				);
				updatedInvoices.add(invoice);
				List<PojjamanDataModel.FNGLDocLineRequest> docLines = eachRequest.DocLine;
				for (PojjamanDataModel.FNGLDocLineRequest docLine : docLines) {
					InvoiceLineItem__c invoiceLineItem = new InvoiceLineItem__c(
						Id = docLine.SFDocLineId,
						ResponseCode__c = 'ERR',
						ResponseMessage__c = errorDescription,
						LastIntegrationDateTime__c = System.now()
					);
					updatedInvoiceLineItems.add(invoiceLineItem);
				}
			} else if (receiptWithReceiptLineItemsMapById.containsKey(eachRequest.SFDocId)) {
				PaymentReceipt__c targetReceipt = receiptWithReceiptLineItemsMapById.get(eachRequest.SFDocId);
				oppIds.add(targetReceipt.Opportunity__c);
				// response for receipt
				PaymentReceipt__c receipt = new PaymentReceipt__c(
					Id = eachRequest.SFDocId,
					ResponseCode__c = 'ERR',
					ResponseMessage__c = errorDescription,
					LastIntegrationDateTime__c = System.now(),
					LastGLStatusInPojjaman__c = 'Fail'
				);
				updatedReceipts.add(receipt);
				List<PojjamanDataModel.FNGLDocLineRequest> docLines = eachRequest.DocLine;
				for (PojjamanDataModel.FNGLDocLineRequest docLine : docLines) {
					PaymentReceiptLineItem__c receiptLineItem = new PaymentReceiptLineItem__c(
						Id = docLine.SFDocLineId,
						ResponseCode__c = 'ERR',
						ResponseMessage__c = errorDescription,
						LastIntegrationDateTime__c = System.now()
					);
					updatedReceiptLineItems.add(receiptLineItem);
				}
			}
		}
		List<Opportunity> updatedOpportunities = new List<Opportunity>();
		for (Id eachOppId : oppIds) {
			Opportunity updatedOpportunity = new Opportunity(
				Id = eachOppId,
				LastGLStatusInPojjaman__c = 'Fail'
			);
			updatedOpportunities.add(updatedOpportunity);
		}
		if(!updatedOpportunities.isEmpty()){
			update updatedOpportunities;
		}
		if (!updatedInvoices.isEmpty()) {
			update updatedInvoices;
		}
		if (!updatedInvoiceLineItems.isEmpty()) {
			update updatedInvoiceLineItems;
		}
		if (!updatedReceipts.isEmpty()) {
			update updatedReceipts;
		}
		if (!updatedReceiptLineItems.isEmpty()) {
			update updatedReceiptLineItems;
		}
		return true;
	}

	public override Boolean processSuccessResponse() {
		OpportunityTriggerHandler oppHandler = OpportunityTriggerHandler.getInstance();
		b8int_BaseHttpResponse response = this.getResponseModel();
		PojjamanDataModel.ResponseDataModel targetResponse = (PojjamanDataModel.ResponseDataModel) response.getResponseDataModel();
		List<PojjamanDataModel.FNGLDocResponse> glResponses = targetResponse.responses;
		PaymentReceiptSelector receiptSelector = PaymentReceiptSelector.getInstance();
		InvoiceSelector invoiceSelector = InvoiceSelector.getInstance();
		List<Invoice__c> updatedInvoices = new List<Invoice__c>();
		List<InvoiceLineItem__c> updatedInvoiceLineItems = new List<InvoiceLineItem__c>();
		List<PaymentReceipt__c> updatedReceipts = new List<PaymentReceipt__c>();
		List<PaymentReceiptLineItem__c> updatedReceiptLineItems = new List<PaymentReceiptLineItem__c>();
		Set<Id> docIds = new Set<Id>();
		for (PojjamanDataModel.FNGLDocResponse glResponse : glResponses) {
			docIds.add(glResponse.SFDocId);
		}
		Map<Id, Invoice__c> invoiceWithInvoiceLineItemsMapById = invoiceSelector.getInvoiceWithInvoiceLineItemsMapById(
			docIds
		);
		Map<Id, PaymentReceipt__c> receiptWithReceiptLineItemsMapById = receiptSelector.getPaymentReceiptWithLineItemMapById(
			docIds
		);

		Set<Id> failedOppIds = new Set<Id>();
		Set<Id> successOppIds = new Set<Id>();
		Datetime lastIntegrationDateTime;
		for (PojjamanDataModel.FNGLDocResponse glResponse : glResponses) {
			lastIntegrationDateTime = glResponse.Timestamp;
			if (invoiceWithInvoiceLineItemsMapById.containsKey(glResponse.SFDocId)) {
				Invoice__c targetInvoice = invoiceWithInvoiceLineItemsMapById.get(glResponse.SFDocId);
				if (glResponse.ResponseCode != 'SC'){
					failedOppIds.add(targetInvoice.Opportunity__c);
				} else {
					successOppIds.add(targetInvoice.Opportunity__c);
				}
				// response for invoice
				Invoice__c invoice = new Invoice__c(
					Id = glResponse.SFDocId,
					ResponseCode__c = glResponse.ResponseCode,
					ResponseMessage__c = glResponse.Message,
					LastIntegrationDateTime__c = glResponse.Timestamp,
					LastGLStatusInPojjaman__c = glResponse.ResponseCode == 'SC' ? 'Success' : 'Fail'
				);
				updatedInvoices.add(invoice);
				List<PojjamanDataModel.FNGLDocLineItemResponse> glLineItemResponses = glResponse.DocLine;
				for (PojjamanDataModel.FNGLDocLineItemResponse glLineItemResponse : glLineItemResponses) {
					InvoiceLineItem__c invoiceLineItem = new InvoiceLineItem__c(
						Id = glLineItemResponse.SFDocLineId,
						ResponseCode__c = glLineItemResponse.ResponseCode,
						ResponseMessage__c = glLineItemResponse.Message,
						LastIntegrationDateTime__c = glLineItemResponse.Timestamp
					);
					updatedInvoiceLineItems.add(invoiceLineItem);
				}
			} else if (receiptWithReceiptLineItemsMapById.containsKey(glResponse.SFDocId)) {
				PaymentReceipt__c targetReceipt = receiptWithReceiptLineItemsMapById.get(glResponse.SFDocId);
				if (glResponse.ResponseCode != 'SC'){
					failedOppIds.add(targetReceipt.Opportunity__c);
				} else {
					successOppIds.add(targetReceipt.Opportunity__c);
				}
				// response for receipt
				PaymentReceipt__c receipt = new PaymentReceipt__c(
					Id = glResponse.SFDocId,
					ResponseCode__c = glResponse.ResponseCode,
					ResponseMessage__c = glResponse.Message,
					LastIntegrationDateTime__c = glResponse.Timestamp,
					LastGLStatusInPojjaman__c = glResponse.ResponseCode == 'SC' ? 'Success' : 'Fail'
				);
				updatedReceipts.add(receipt);
				List<PojjamanDataModel.FNGLDocLineItemResponse> glLineItemResponses = glResponse.DocLine;
				for (PojjamanDataModel.FNGLDocLineItemResponse glLineItemResponse : glLineItemResponses) {
					PaymentReceiptLineItem__c receiptLineItem = new PaymentReceiptLineItem__c(
						Id = glLineItemResponse.SFDocLineId,
						ResponseCode__c = glLineItemResponse.ResponseCode,
						ResponseMessage__c = glLineItemResponse.Message,
						LastIntegrationDateTime__c = glLineItemResponse.Timestamp
					);
					updatedReceiptLineItems.add(receiptLineItem);
				}
			}
		}
		oppHandler.setBypass();
		List<Opportunity> updatedOpportunitites = new List<Opportunity>();
		if (!successOppIds.isEmpty()){
			for (Id successOppId : successOppIds){
				Opportunity updatedOpportunity = new Opportunity(
					Id = successOppId,
					LastGLStatusInPojjaman__c = 'Success'
				);
				updatedOpportunitites.add(updatedOpportunity);
			}
		}
		if (!failedOppIds.isEmpty()){
			for (Id failOppId : failedOppIds){
				Opportunity updatedOpportunity = new Opportunity(
					Id = failOppId,
					LastGLStatusInPojjaman__c = 'Fail'
				);
				updatedOpportunitites.add(updatedOpportunity);
			}
		}
		if (!updatedOpportunitites.isEmpty()){
			update updatedOpportunitites;
		}
		oppHandler.clearBypass();
		if (!updatedInvoices.isEmpty()) {
			update updatedInvoices;
		}
		if (!updatedInvoiceLineItems.isEmpty()) {
			update updatedInvoiceLineItems;
		}
		if (!updatedReceipts.isEmpty()) {
			update updatedReceipts;
		}
		if (!updatedReceiptLineItems.isEmpty()) {
			update updatedReceiptLineItems;
		}
		return true;
	}
}