force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <formula>AddressNoTH__c + &apos; &apos; +   SubDistrictTH__c  + &apos; &apos; +  DistrictTH__c + &apos;   &apos; +  ProvinceTH__c + &apos; &apos; +  ZipCodeTH__c  + &apos; &apos; +  Text(CountryTH__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address TH</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxID__c.field-meta.xml
<CustomField>
    <fullName>TaxID__c</fullName>
    <description>เลขที่ภาษี</description>
    <label>Tax ID</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <label>Account Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GLDate__c.field-meta.xml
<CustomField>
    <fullName>GLDate__c</fullName>
    <formula>Opportunity__r.ClosedLostDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GLKey__c.field-meta.xml
<CustomField>
    <fullName>GLKey__c</fullName>
    <formula>TRIM(&quot;IV_GL_&quot;&amp; Opportunity__r.Account.AccountCode__c + &quot;_&quot; + Opportunity__r.Project__r.ProjectCode__c + &quot;_&quot; + Opportunity__r.Unit__r.ProductCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>เทียบเท่ากับ DueDate__c ของ OpportunityPayment__c ในรอบนั้นๆ</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastCreatedStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastCreatedStatusInPojjaman__c</fullName>
    <label>Last Created Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastGLStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastGLStatusInPojjaman__c</fullName>
    <label>Last GL Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>running ของการ item ใน invoice</description>
    <label>Line Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>OpportunityPayment__r.Term__c</formula>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceSelector.cls
public with sharing class InvoiceSelector {
	public static InvoiceSelector instance;
	public static InvoiceSelector getInstance() {
		if (instance == null) {
			instance = new InvoiceSelector();
		}
		return instance;
	}

	public List<Invoice__c> getForSendEmail(Date dueDate) {
		return [
			SELECT Id, Opportunity__c, InvoiceDate__c, DueDate__c, DoNotSendInvoice__c, Opportunity__r.ContactPerson__r.Email,
				Opportunity__r.Account.Email__c
			FROM Invoice__c
			WHERE DueDate__c =: dueDate
				AND DoNotSendInvoice__c = false
		];
	}

	public List<Invoice__c> getByOppIdSet(Set<Id> oppIdSet) {
		return [
			SELECT Id, Opportunity__c
			FROM Invoice__c
			WHERE Opportunity__c IN: oppIdSet
		];
	}

	public Invoice__c getById(Id invoiceId) {
		return [
			SELECT Id, Opportunity__c, InvoiceNo__c, AccountAddress__c, IsCancel__c, InvoiceDate__c, DueDate__c,
				Opportunity__r.Name, Opportunity__r.NetPrice__c, Opportunity__r.UnitPrice__c, Opportunity__r.UnitPricePerSqm__c,
				Opportunity__r.NetPricePerSqm__c, Opportunity__r.AreaSqm__c, Opportunity__r.CoBuyerName__c,
				Opportunity__r.Account.Name, Opportunity__r.Account.Phone, Opportunity__r.Account.Email__c,
				Opportunity__r.Account.AddressEN__c, Opportunity__r.Account.AddressTH__c, Opportunity__r.Account.TaxID__c,
				Opportunity__r.ContactPerson__c, Opportunity__r.ContactPerson__r.MobilePhone, Opportunity__r.ContactPerson__r.Email,
				Opportunity__r.Unit__r.Name, Opportunity__r.Unit__r.AreaSqm__c,
				Opportunity__r.Unit__r.UnitType__r.Name,
				Opportunity__r.Project__r.Name, Opportunity__r.Project__r.ProjectLogo__c, Opportunity__r.Project__r.CompanyName__c,
				Opportunity__r.Project__r.CompanyAddress__c, Opportunity__r.Project__r.CompanyPhone__c,
				Opportunity__r.Project__r.CompanyTaxID__c,
				Opportunity__r.Project__r.CompanyAccountNameForInvoice__c, Opportunity__r.Project__r.CompanyAccountNameForInvoice__r.Name,
				Opportunity__r.Project__r.BankAccountNumberForInvoice__c, Opportunity__r.Project__r.CompanyBankNameForInvoice__c,
				Opportunity__r.Project__r.BankBranchForInvoice__c, Opportunity__r.Project__r.BankAddressForInvoice__c,
				Opportunity__r.Project__r.SWIFTCodeForInvoice__c
			FROM Invoice__c
			WHERE Id =: invoiceId
		];
	}

	public Map<Id,Invoice__c> getInvoiceWithInvoiceLineItemsMapById(Set<Id> invoiceIds){
		return new Map<Id,Invoice__c>([
			SELECT
				Id,
				Opportunity__r.Account.AccountCode__c,
				Opportunity__r.Project__r.ProjectCode__c,
				CreatedDate,
				InvoiceNo__c,
				GLKey__c,
				GLDate__c,
				ResponseCode__c,
				ResponseMessage__c,
				LastIntegrationDateTime__c,
				LastCreatedStatusInPojjaman__c,
				LastGLStatusInPojjaman__c,
				(
					SELECT
						Id,
						Invoice__r.Opportunity__r.Unit__r.ProductCode,
						OpportunityPayment__r.Remaining__c,
						Term__c,
						Amount__c,
						Status__c,
						DueDate__c,
						ResponseCode__c,
						ResponseMessage__c,
						LastIntegrationDateTime__c,
						LineNumber__c
					FROM InvoiceLineItems__r
				)
			FROM Invoice__c
			WHERE Id IN: invoiceIds
		]);
	}

	public Map<String, Invoice__c> getInvoiceMapByTerm(Id oppId) {
		Map<String, Invoice__c> invoiceMapByTerm = new Map<String, Invoice__c>();
        List<Invoice__c> invoices = [
            SELECT
                Id,
                Opportunity__r.Account.AccountCode__c,
                Opportunity__r.Project__r.ProjectCode__c,
                CreatedDate,
                InvoiceNo__c,
                GLKey__c,
                ResponseCode__c,
                ResponseMessage__c,
                LastIntegrationDateTime__c,
                LastCreatedStatusInPojjaman__c,
                LastGLStatusInPojjaman__c,
                (
                    SELECT
                        Id,
                        Invoice__r.Opportunity__r.Unit__r.ProductCode,
                        OpportunityPayment__r.Remaining__c,
                        Term__c,
                        Amount__c,
                        Status__c,
                        DueDate__c,
                        ResponseCode__c,
                        ResponseMessage__c,
                        LastIntegrationDateTime__c
                    FROM InvoiceLineItems__r
                )
            FROM Invoice__c
			WHERE Opportunity__c =: oppId
        ];
		for (Invoice__c invoice : invoices){
			InvoiceLineItem__c invoiceLineItem = invoice.InvoiceLineItems__r[0];
			invoiceMapByTerm.put(invoiceLineItem.Term__c , invoice);
		}
		return invoiceMapByTerm;
    }
}