force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/AccountNameTH__c.field-meta.xml
<CustomField>
    <fullName>AccountNameTH__c</fullName>
    <label>Account Name (TH)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <formula>AddressNoTH__c + &apos; &apos; +   SubDistrictTH__c  + &apos; &apos; +  DistrictTH__c + &apos;   &apos; +  ProvinceTH__c + &apos; &apos; +  ZipCodeTH__c  + &apos; &apos; +  Text(CountryTH__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address TH</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FaxExt__c.field-meta.xml
<CustomField>
    <fullName>FaxExt__c</fullName>
    <label>Fax Ext.</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IDCardNumber__c.field-meta.xml
<CustomField>
    <fullName>IDCardNumber__c</fullName>
    <label>Identification Card No.</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastContactIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>LastContactIntegrationStatus__c</fullName>
    <label>Last Contact Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingAddressEN__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(MailingAddressNoEN__c)), MailingAddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MaillingSubDistrictEN__c)), MaillingSubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingDistrictEN__c)), MailingDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingProvinceEN__c)), MailingProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(MailingZipCodeEN__c)), MailingZipCodeEN__c &amp; &quot;  &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(MailingCountryEN__c))), TEXT(MailingCountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingAddressTH__c.field-meta.xml
<CustomField>
    <fullName>MailingAddressTH__c</fullName>
    <formula>MailingAddressNoTH__c  + &apos; &apos; +  MaillingSubDistrictTH__c  + &apos; &apos; +  MailingDistrictTH__c  + &apos; &apos; +  MailingProvinceTH__c  + &apos; &apos; +  MailingZipCodeTH__c  + &apos; &apos; + Text( MailingCountryTH__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address TH</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PassportNo__c.field-meta.xml
<CustomField>
    <fullName>PassportNo__c</fullName>
    <description>หมายเลขหนังสือเดินทาง</description>
    <label>Passport Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxID__c.field-meta.xml
<CustomField>
    <fullName>TaxID__c</fullName>
    <description>เลขที่ภาษี</description>
    <label>Tax ID</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Co_Owner_Corporate.recordType-meta.xml
<RecordType>
    <fullName>Co_Owner_Corporate</fullName>
    <active>true</active>
    <label>Co-Owner - Corporate</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IDCardNumber__c.field-meta.xml
<CustomField>
    <fullName>IDCardNumber__c</fullName>
    <description>หมายเลขบัตรประชาชน</description>
    <label>ID Card Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsPrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastCreatedStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastCreatedStatusInPojjaman__c</fullName>
    <label>Last Created Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastIntegrationDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastIntegrationDateTime__c</fullName>
    <label>Last Integration Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>ResponseMessage__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CreateCustomerApiCallout.cls
public with sharing class CreateCustomerApiCallout extends b8int_BaseHttpCallout {

	private List<Account> accounts = new List<Account>();

    public CreateCustomerApiCallout(List<Account> accounts) {
        super('Customer');
		this.accounts = accounts;
        this.setCalloutType(b8int_BaseHttpCallout.HttpCalloutType.REALTIME);
        this.setIsRequireRetry(false);
        this.setMethod(b8int_BaseHttpRequest.HttpMethod.POST);
        this.setClient(new CreateCustomerApiClient());
        this.setContentType(b8int_BaseHttpRequest.ContentType.JSON);
        this.setEndpoint('api/CityDynamic/CreateCustomer');
        this.setRequestDataModelClass(RequestDataModel.class);
        this.setResponseDataModelClass(ResponseDataModel.class);
    }

	public override Object buildRequestDataModel() {
		Date todayDate = Date.today();
        List<RequestDataModel> requestDataModels = new List<RequestDataModel>();
		for (Account account : accounts){
			RequestDataModel requestDataModel = new RequestDataModel();
			requestDataModel.SFCustomerId = account.Id;
			requestDataModel.CustomerCode = account.AccountCode__c;
			requestDataModel.CustomerNameEN = account.Name;
			requestDataModel.CustomerNameTH = account.AccountNameTH__c;
			requestDataModel.CustomerType = account.RecordType.DeveloperName == 'Co_Owner_Corporate' ? 'Corporate' : 'Individual' ;
			requestDataModel.AddressEN = account.AddressEN__c;
			requestDataModel.AddressTH = account.AddressTH__c;
			requestDataModel.MailingAddressEN = account.MailingAddressEN__c;
			requestDataModel.MailingAddressTH = account.MailingAddressTH__c;
			requestDataModel.MobilePhone = account.Phone;
			if (account.Fax != null) {
				if (account.FaxExt__c != null){
					requestDataModel.Fax = account.Fax + '-' + account.FaxExt__c;
				}else{
					requestDataModel.Fax = account.Fax;
				}
			} else {
				requestDataModel.Fax = null;
			}
			requestDataModel.Email = account.Email__c;
			requestDataModel.TaxId = requestDataModel.CustomerType == 'Corporate' ? account.TaxID__c : account.Nationality__c == 'Thai' ? account.IDCardNumber__c : account.PassportNo__c ;
			requestDataModel.IDType = requestDataModel.CustomerType == 'Corporate' ? 3 : account.Nationality__c == 'Thai' ? 1 : 2 ;
			requestDataModel.CustomerIndicator = account.AccountCode__c == null ? 0 : 1;
			requestDataModel.IsActiveCustomer = account.Active__c ? 1 : 0;
			List<Contact> contacts = account.Contacts;
			List<ContactRequest> contactRequests = new List<ContactRequest>();
			if (contacts != null){
				for (Contact contact : contacts){
					// if (account.Active__c && !contact.Active__c){
					// 	continue;
					// }
					if (contact.LastModifiedDate.date() == todayDate || contact.ResponseCode__c != 'SCC'){
						ContactRequest contactRequest = new ContactRequest();
						contactRequest.SFContactId = contact.Id;
						contactRequest.Name = contact.FirstName != null ? contact.FirstName + ' ' + contact.LastName : contact.LastName;
						contactRequest.Email = contact.Email;
						contactRequest.MobilePhone = contact.MobilePhone;
						contactRequest.Position = contact.Position__c;
						contactRequest.IsPrimaryContact = contact.IsPrimaryContact__c;
						contactRequest.ContactIndicator = contact.LastCreatedStatusInPojjaman__c == null || contact.LastCreatedStatusInPojjaman__c == 'Fail'  ? 0 : 1;
						contactRequest.IsActiveContact = contact.Active__c ? 1 : 0;
						contactRequests.add(contactRequest);
					}
				}
			}
			requestDataModel.Contacts = contactRequests;
			requestDataModels.add(requestDataModel);
		}
        return requestDataModels;
    }

	public override Boolean processFailedResponse() {
		// stamp server error
		b8int_BaseHttpRequest request = this.getRequestModel();
		b8int_BaseHttpResponse response = this.getResponseModel();
		System.debug('** test ** response: ' + this.getResponseModel());
		List<RequestDataModel> targetRequests = (List<RequestDataModel>)request.getRequestBody();
		String errorDescription = response.getDescription();
		System.debug('** test ** errorDescription:' + errorDescription);
		List<Account> updatedAccounts = new List<Account>();
		List<Contact> updatedContacts = new List<Contact>();
		for (RequestDataModel eachRequest : targetRequests){
			System.debug('** test ** eachRequest:' + eachRequest);
			Account updatedAccount = new Account(
				Id = eachRequest.SFCustomerId,
				ResponseCode__c = 'ERR',
				ResponseMessage__c = errorDescription,
				LastIntegrationDateTime__c = System.now(),
				LastContactIntegrationStatus__c = 'Fail'
			);
			updatedAccounts.add(updatedAccount);
			List<ContactRequest> contactRequests = eachRequest.Contacts;
			if (contactRequests != null){
				for (ContactRequest contactRequest : contactRequests){
					Contact updatedContact = new Contact(
						Id = contactRequest.SFContactId,
						ResponseCode__c = 'ERR',
						ResponseMessage__c = errorDescription,
						LastIntegrationDateTime__c = System.now()
					);
					updatedContacts.add(updatedContact);
				}
			}
		}
		if (!updatedAccounts.isEmpty()){
			update updatedAccounts;
		}
		if (!updatedContacts.isEmpty()){
			update updatedContacts;
		}
        return true;
    }

    public override Boolean processSuccessResponse() {
		AccountSelector accountSelector = AccountSelector.getInstance();
		b8int_BaseHttpResponse response = this.getResponseModel();
		ResponseDataModel targetResponse = (ResponseDataModel)response.getResponseDataModel();
		System.debug('** test **: ' + targetResponse);
		Set<Id> accountIds = new Set<Id>();
		List<AccountResponse> accountResponses = targetResponse.responses;
		for (AccountResponse accountResponse : accountResponses){
			accountIds.add(accountResponse.SFCustomerId);
		}
		Map<Id, Account> accountWithContactsMapById = accountSelector.getAccountWithContactsMapById(accountIds);
		List<Account> updatedAccounts = new List<Account>();
		List<Contact> updatedContacts = new List<Contact>();
		for (AccountResponse accountResponse : accountResponses){
			Account targetAccount = accountWithContactsMapById.get(accountResponse.SFCustomerId);
			Boolean allContactSuccess = true;
			Account updatedAccount = new Account(
				Id = accountResponse.SFCustomerId,
				ResponseCode__c = accountResponse.ResponseCode,
				ResponseMessage__c = accountResponse.Message,
				LastIntegrationDateTime__c = accountResponse.Timestamp
			);
			if (accountResponse.ResponseCode == 'SC'){
				updatedAccount.AccountCode__c = accountResponse.CustomerCode;
			}
			List<Contact> contacts = targetAccount.Contacts;
			Map<Id,Contact> contactMapById = new Map<Id,Contact>();
			if (contacts != null){
				for (Contact contact : contacts){
					contactMapById.put(contact.Id , contact);
				}
			}
			List<ContactResponse> contactResponses = accountResponse.Contacts;
			for (ContactResponse contactResponse : contactResponses){
				Contact targetContact = contactMapById.get(contactResponse.SFContactId);
				targetContact.ResponseCode__c = contactResponse.ResponseCode;
				targetContact.ResponseMessage__c = contactResponse.Message;
				targetContact.LastIntegrationDateTime__c = contactResponse.Timestamp;
				if (targetContact.LastCreatedStatusInPojjaman__c == null){
					targetContact.LastCreatedStatusInPojjaman__c = contactResponse.ResponseCode == 'SCC' ? 'Success' : 'Fail';
				}
				updatedContacts.add(targetContact);
				if (contactResponse.ResponseCode != 'SCC'){
					if (contactResponse.ResponseCode != 'SC') {
						allContactSuccess = false;
					}
				}
			}
			if (!allContactSuccess){
				updatedAccount.LastContactIntegrationStatus__c = 'Fail';
			} else {
				updatedAccount.LastContactIntegrationStatus__c = 'Success';
			}
			updatedAccounts.add(updatedAccount);
		}
		if (!updatedAccounts.isEmpty()){
			update updatedAccounts;
		}
		if (!updatedContacts.isEmpty()){
			update updatedContacts;
		}
        return true;
    }

    public class RequestDataModel extends b8int_BaseRequestDataModel {
		public String SFCustomerId;
		public String CustomerCode;
		public String CustomerNameEN;
		public String CustomerNameTH;
		public String CustomerType;
		public String AddressEN;
		public String AddressTH;
		public String MailingAddressEN;
		public String MailingAddressTH;
		public String MobilePhone;
		public String Fax;
		public String Email;
		public String TaxID;
		public Integer IDType;
		public Integer CustomerIndicator;
		public Integer IsActiveCustomer;
		public List<ContactRequest> Contacts;
    }

	public class ContactRequest{
		public String SFContactId;
		public String Name;
		public String Email;
		public String MobilePhone;
		public String Position;
		public Boolean IsPrimaryContact;
		public Integer ContactIndicator;
		public Integer IsActiveContact;
	}

    public class ResponseDataModel extends b8int_BaseResponseDataModel {
        public Boolean isSuccess;
        public String description;
		public List<AccountResponse> responses;

        public override Boolean isValid() {
            return isSuccess;
        }

        public override String getErrorDescription() {
            return this.description;
        }

    }

	public class AccountResponse{
		public String SFCustomerId;
		public String CustomerCode;
		public Integer ResponseId;
		public String ResponseCode;
		public String Message;
		public Datetime Timestamp;
		public List<ContactResponse> Contacts;
	}

	public class ContactResponse{
		public String SFContactId;
		public Integer ResponseId;
		public String ResponseCode;
		public String Message;
		public Datetime Timestamp;
	}
}