force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <label>Account Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>เทียบเท่ากับ DueDate__c ของ OpportunityPayment__c ในรอบนั้นๆ</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NameFormattingMasterData__c/NameFormattingMasterData__c.object-meta.xml
<CustomObject>
    <description>สำหรับเก็บข้อมูล Backend value ต่างๆ เช่น Running Number</description>
    <label>Name Formatting Master Data</label>
    <nameField>
        <displayFormat>NFMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Formatting Master Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ใช้เพื่อบอกว่า Opportunity นี้จะส่ง Invoice ให้ลูกค้าหรือไม่
ถ้า field นี้ เป็น True จะไม่มีการ Generate เอกสาร Invoice
ถ้า field นี้ เป็น False จะมีการ Generate เอกสาร Invoice และส่ง email ไปให้ลูกค้า
แต่ไม่ว่า field นี้จะเป็น True หรือ Fales จะมีการสร้าง record ที่ Object Invoice เสมอ</description>
    <label>Do Not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceService.cls
public with sharing class InvoiceService {
	public static InvoiceService instance;
	public static InvoiceService getInstance() {
		if (instance == null) {
			instance = new InvoiceService();
		}
		return instance;
	}

	private final String OBJECT_API_NAME = 'Invoice__c';
	private final String PDF_FORM_INVOICE = 'InvoiceForm';
	private final String PDF_FORM_PAYMENT_SUMMARY = 'PaymentSummaryForm';

	public void insertInvoiceAndRelatedRecords(List<OpportunityPayment__c> oppPayments, Date dueDate, Date invoiceDate) {
		Map<Id, List<OpportunityPayment__c>> oppPaymentMapByOppId = getOppPaymentsMapByOppId(oppPayments);

		if (oppPaymentMapByOppId.isEmpty()) {
			return;
		}

		Map<Id, Opportunity> opportunityMapById = OpportunitySelector.getInstance().getOpportunityMapById(oppPaymentMapByOppId.keySet());
		Map<Id, Invoice__c> invoiceMapByOppId = getInvoiceMapByOppId(opportunityMapById, dueDate, invoiceDate);
		insertInvoices(invoiceMapByOppId.values());
		updateInvoiceNo(invoiceMapByOppId.values());

		List<InvoiceLineItem__c> invoiceLineItems = InvoiceLineItemService.getInstance().getNewInvoiceLineItems(invoiceMapByOppId, oppPaymentMapByOppId);
		InvoiceLineItemService.getInstance().insertInvoiceLineItems(invoiceLineItems);
	}

	public void insertInvoiceAndPaymentSummaryFiles(List<Invoice__c> invoices) {
		List<Id> oppIds = new List<Id>();
		List<Id> invoiceIds = new List<Id>();
		Map<Id, Id> invoiceIdMapByOppId = new Map<Id, Id>();
		for (Invoice__c invoice : invoices) {
			invoiceIds.add(invoice.Id);
			oppIds.add(invoice.Opportunity__c);
			invoiceIdMapByOppId.put(invoice.Opportunity__c, invoice.Id);
		}

		// query 2
		Map<Id, String> invoiceNameMapWithInvoiceId = getFormatNameMapWithRecordId(OBJECT_API_NAME, 'Document', 'Invoice', invoiceIds);
		// query 2
		Map<Id, String> paymentSummaryNameMapWithOppId = getFormatNameMapWithRecordId('Opportunity', 'Document', 'Payment Summary', oppIds);

		// query 2N + 1
		// ต้องการ save file ที่ record ของตัวเองเลย(invoice)
		// ทุกครั้งที่ createPdfFileToRecord จะแตก async ออกมาเป็น 1 task
		// เอกสาร invoice
		PDFUtility.getInstance().createPdfFileToRecord(PDF_FORM_INVOICE, invoiceNameMapWithInvoiceId, invoiceIds, null);

		// query 3N + อีก 1
		// ต้องการ save file ที่ record ของ invoice
		// ทุกครั้งที่ createPdfFileToRecord จะแตก async ออกมาเป็น 1 task
		// เอกสาร payment summary
		PDFUtility.getInstance().createPdfFileToRecord(PDF_FORM_PAYMENT_SUMMARY, paymentSummaryNameMapWithOppId, oppIds, invoiceIdMapByOppId);
	}

	// ทำการสร้างเอกสาร Invoice และ Payment Summary และทำการส่ง email ไปหาลูกค้าโดยการแนบเอกสาร Invoice และ Payment Summary ไปท้าย email
	public Messaging.SendEmailResult[] sendEmailWithAttachment(List<Invoice__c> invoices) {
		// List<Invoice__c> invoiceForSendEmails = InvoiceSelector.getInstance().getForSendEmail(dueDate);
		List<Invoice__c> invoiceForSendEmails = new List<Invoice__c>();
		for (Invoice__c invoice : invoices) {
			if(!invoice.DoNotSendInvoice__c){
				invoiceForSendEmails.add(invoice);
			}
		}

		List<Id> invoiceIds = new List<Id>();
		List<Id> oppIds = new List<Id>();
		Set<Id> invoiceIdAndOppIdset = new Set<Id>();
		setInitailValuesFromInvoices(invoiceForSendEmails, invoiceIds, oppIds, invoiceIdAndOppIdset);

		Map<Id, String> invoiceNoMapWithInvoiceId = getFormatNameMapWithRecordId(OBJECT_API_NAME, 'Document', 'Invoice', invoiceIds);
		Map<Id, String> paymentSummaryNameMapWithInvoiceId = getFormatNameMapWithRecordId('Opportunity', 'Document', 'Payment Summary', oppIds);
		Map<Id, List<Id>> recordContentVerIdsMapByRecordId = ContentVersionService.getInstance().getRecordContentVerIdsMapByRecordIdForInvoice(
			invoiceIdAndOppIdset,
			invoiceNoMapWithInvoiceId,
			paymentSummaryNameMapWithInvoiceId
		);

		List<Messaging.SingleEmailMessage> singleEmails = new List<Messaging.SingleEmailMessage>();
		Id orgWideId = OrgWideEmailAddressSelector.getInstance().getByAddress(EmailUtility.getInstance().emailForOrgWide).get(0).Id;

		List<EmailTemplate> emailTemplates = EmailTemplateSelector.getInstance().getByDeveloperName(
			new Set<String>{'SendInvoiceToCustomer'}
		);

		EmailUtility emailUtility = EmailUtility.getInstance();
		EmailTemplate emailTemplate = emailTemplates.get(0);
		Contact dummyContact = ContactSelector.getInstance().getDummy();
		List<Messaging.SingleEmailMessage> tempEmails = new List<Messaging.SingleEmailMessage>();
		for (Invoice__c invoiceForSendEmail : invoiceForSendEmails) {
			List<String> toAddresses = new List<String>();
			List<Messaging.EmailFileAttachment> emailFileAttachments = new List<Messaging.EmailFileAttachment>();

			if(String.isBlank(invoiceForSendEmail.Opportunity__r.ContactPerson__r.Email)){
				if(String.isNotBlank(invoiceForSendEmail.Opportunity__r.Account.Email__c)){
					toAddresses.add(invoiceForSendEmail.Opportunity__r.Account.Email__c);
				}
			}
			else{
				toAddresses.add(invoiceForSendEmail.Opportunity__r.ContactPerson__r.Email);
			}

			if(toAddresses.isEmpty()){
				continue;
			}

			List<Id> ctVersionIds = new List<Id>();
			Messaging.SingleEmailMessage tempEmail = emailUtility.getSingleEmail(
				orgWideId,
				emailTemplate,
				toAddresses,
				null,
				emailFileAttachments,
				recordContentVerIdsMapByRecordId.get(invoiceForSendEmail.Id),
				invoiceForSendEmail.Id,
				dummyContact.Id
			);

			tempEmails.add(tempEmail);
		}

		if(!tempEmails.isEmpty()){
			emailUtility.fakeSendEmails(tempEmails);

			List<Messaging.SingleEmailMessage> actualEmails = new List<Messaging.SingleEmailMessage>();
			for (Messaging.SingleEmailMessage tempEmail : tempEmails) {
				Messaging.SingleEmailMessage actualEmail = emailUtility.getSingleEmailFromTempEmail(tempEmail);
				actualEmails.add(actualEmail);
			}

			return emailUtility.sendAllEmailMessage(actualEmails);
		}

		return null;
	}

	public Database.SaveResult[] insertInvoices(List<Invoice__c> invoices) {
		Database.SaveResult[] insertResults;

		if (!invoices.isEmpty()) {
			insertResults = Database.insert(invoices, false);
		}

		return insertResults;
	}

	public Database.SaveResult[] updateInvoices(List<Invoice__c> invoices) {
		Database.SaveResult[] updateResults;

		if (!invoices.isEmpty()) {
			updateResults = Database.update(invoices, false);
		}

		return updateResults;
	}

	public List<Invoice__c> getCancelInvoiceByOppIdSet(Set<Id> oppIdSet){
		List<Invoice__c> invoiceForCancels = new List<Invoice__c>();

		List<Invoice__c> invoices = InvoiceSelector.getInstance().getByOppIdSet(oppIdSet);
		for (Invoice__c invoice : invoices) {
			invoiceForCancels.add(
				new Invoice__c(
					Id = invoice.Id,
					IsCancel__c = true,
					CancelReason__c = 'Closed Lost'
				)
			);
		}

		return invoiceForCancels;
	}

	// ----- Start Private Service -----
	@TestVisible
	private Map<Id, List<OpportunityPayment__c>> getOppPaymentsMapByOppId(List<OpportunityPayment__c> oppPayments) {
		Map<Id, List<OpportunityPayment__c>> oppPaymentsMapByOppId = new Map<Id, List<OpportunityPayment__c>>();
		for (OpportunityPayment__c oppPayment : oppPayments) {
			List<OpportunityPayment__c> opportunityPayments = oppPaymentsMapByOppId.get(oppPayment.Opportunity__c);

			if (opportunityPayments == null) {
				oppPaymentsMapByOppId.put(oppPayment.Opportunity__c, new List<OpportunityPayment__c>{ oppPayment });
			} else {
				opportunityPayments.add(oppPayment);
			}
		}
		return oppPaymentsMapByOppId;
	}

	@TestVisible
	private Map<Id, Invoice__c> getInvoiceMapByOppId(Map<Id, Opportunity> opportunityMapById, Date dueDate, Date invoiceDate) {
		Map<Id, Invoice__c> invoiceMapByOppId = new Map<Id, Invoice__c>();
		for (Id oppId : opportunityMapById.keySet()) {
			Opportunity opportunity = opportunityMapById.get(oppId);
			invoiceMapByOppId.put(
				oppId,
				new Invoice__c(
					Opportunity__c = oppId,
					InvoiceDate__c = invoiceDate,
					DueDate__c = dueDate,
					DoNotSendInvoice__c = opportunity.DoNotSendInvoice__c,
					AccountAddress__c = opportunity.Account.AddressEN__c
				)
			);
		}
		return invoiceMapByOppId;
	}

	@TestVisible
	private void updateInvoiceNo(List<Invoice__c> invoices) {
		List<Id> invoiceIds = new List<Id>();
		for (Invoice__c invoice : invoices) {
			invoiceIds.add(invoice.Id);
		}

		Map<Id, String> invoiceNoMapWithInvoiceId = getFormatNameMapWithRecordId(OBJECT_API_NAME, 'Object', null, invoiceIds);

		List<Invoice__c> invoiceForUpdates = new List<Invoice__c>();
		for (Id invoiceId : invoiceNoMapWithInvoiceId.keySet()) {
			String invoiceNo = invoiceNoMapWithInvoiceId.get(invoiceId);
			invoiceForUpdates.add(
				new Invoice__c(
					Id = invoiceId,
					InvoiceNo__c = invoiceNoMapWithInvoiceId.get(invoiceId)
				)
			);
		}

		updateInvoices(invoiceForUpdates);

	}

	@TestVisible
	private void setInitailValuesFromInvoices(List<Invoice__c> invoiceForSendEmails, List<Id> invoiceIds, List<Id> oppIds, Set<Id> invoiceIdAndOppIdset) {
		for (Invoice__c invoiceForSendEmail : invoiceForSendEmails) {
			invoiceIds.add(invoiceForSendEmail.Id);
			oppIds.add(invoiceForSendEmail.Opportunity__c);

			invoiceIdAndOppIdset.add(invoiceForSendEmail.Id);
			invoiceIdAndOppIdset.add(invoiceForSendEmail.Opportunity__c);
		}
	}

	@TestVisible
	private Map<Id, String> getFormatNameMapWithRecordId(String objectApiName, String purpose, String documentTemplate, List<Id> recordIds) {
		List<NameFormattingMasterData__c> nameFormattingMasterDatas = NameFormattingMasterDataSelector.getInstance()
			.getByObjTypePurposeDocTemplate(objectApiName, 'Format', purpose, documentTemplate);

		if(nameFormattingMasterDatas.isEmpty()){
			return new Map<Id, String>();
		}

		return RunningNumberUtility.getInstance()
			.generateReplacedFormatName(nameFormattingMasterDatas.get(0), recordIds, objectApiName);
	}
	// ----- End Private Service -----
}