force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <label>Address EN</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastCreatedStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastCreatedStatusInPojjaman__c</fullName>
    <label>Last Created Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ใช้เพื่อบอกว่า Opportunity นี้จะส่ง Invoice ให้ลูกค้าหรือไม่
ถ้า field นี้ เป็น True จะไม่มีการ Generate เอกสาร Invoice
ถ้า field นี้ เป็น False จะมีการ Generate เอกสาร Invoice และส่ง email ไปให้ลูกค้า
แต่ไม่ว่า field นี้จะเป็น True หรือ Fales จะมีการสร้าง record ที่ Object Invoice เสมอ</description>
    <label>Do Not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceApiCalloutBatchTest.cls
@isTest
public with sharing class CreateInvoiceApiCalloutBatchTest {

	public static String succesDocId;
	public static String succesDocLineId;
	public static String succesDocId2;
	public static String succesDocLineId2;
	public static String targetFailDocId;

    public class SuccessInvoiceMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateInvoiceApiCallout.RequestDataModel>.class);
            List<CreateInvoiceApiCallout.RequestDataModel> requestData = ( List<CreateInvoiceApiCallout.RequestDataModel>)requestDataObj;
			// START MOCK RESPONSE
            List<CreateInvoiceApiCallout.InvoiceResponse> responseInvoiceData = new List<CreateInvoiceApiCallout.InvoiceResponse>();
			CreateInvoiceApiCallout.InvoiceResponse invoiceResponse = new CreateInvoiceApiCallout.InvoiceResponse();
			invoiceResponse.DocLine = new List<CreateInvoiceApiCallout.InvoiceLineItemResponse>();
			invoiceResponse.SFDocId = succesDocId;
			invoiceResponse.ResponseCode = 'SC';
			invoiceResponse.Message = 'Success';
			CreateInvoiceApiCallout.InvoiceLineItemResponse invoiceLineItemResponse = new CreateInvoiceApiCallout.InvoiceLineItemResponse();
			invoiceLineItemResponse.ResponseCode = 'SC';
			invoiceLineItemResponse.SFDocLineId = succesDocLineId;
			invoiceLineItemResponse.Message = 'Success';
			invoiceResponse.DocLine.add(invoiceLineItemResponse);
			responseInvoiceData.add(invoiceResponse);
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseInvoiceData));
            res.setStatusCode(200);
            return res;
        }
    }

	@isTest
	static void craeteInvoiceCalloutTestSuccess(){
		Test.setMock(HttpCalloutMock.class, new CreateInvoiceApiCalloutBatchTest.SuccessInvoiceMockResp());
		DataMaker dataMaker = DataMaker.getInstance();
		// CREATE PROJECT
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// CREATE FLOOR
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// CREATE UNIT TYPE
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// CREATE UNIT
		Product2 unit1 = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert unit1;
		// CREATE ACCOUNT
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'BE8');
		insert account;
		// CREATE OPPORTUNITY
		Opportunity opp = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.newInstance(2024, 10, 1),
			'Open',
			unit1.Id,
			'Foreign',
			null,
			testProject.Id
		);
		opp.DoNotSendInvoice__c = true;
		insert opp;
		// CREATE OPP PAYMENT
		OpportunityPayment__c reservationOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opp.Id,
			'opp',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		insert reservationOppPaymentOpp1;
		Date dueDate = Date.newInstance(2024, 11, 1);
		Date invoiceDate = Date.newInstance(2024, 10, 27);
		// CREATE INVOICE
		Invoice__c invoice = dataMaker.createInvoice(opp.Id, dueDate, invoiceDate, opp.DoNotSendInvoice__c, opp.Account.AddressEN__c);
		insert invoice;
		succesDocId = invoice.Id;
		// CREATE INVOICE LINE ITEM
		InvoiceLineItem__c ivline = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPaymentOpp1.Id,50000,dueDate,'');
		insert ivline;
		succesDocLineId = ivline.Id;
		Test.startTest();
		// EXECUTE BATCH
		CreateInvoiceApiCalloutBatch batch = new CreateInvoiceApiCalloutBatch();
		Database.executeBatch(batch, 2000);
		Test.stopTest();
		Invoice__c targetInvoice = [SELECT Id,ResponseMessage__c,ResponseCode__c,LastCreatedStatusInPojjaman__c FROM Invoice__c WHERE Id =: invoice.Id LIMIT 1];
		InvoiceLineItem__c targetInvoiceLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM InvoiceLineItem__c WHERE Id =: ivline.Id LIMIT 1];
		System.assertEquals('Success', targetInvoice.ResponseMessage__c);
		System.assertEquals('Success', targetInvoice.LastCreatedStatusInPojjaman__c);
		System.assertEquals('SC', targetInvoice.ResponseCode__c);
		System.assertEquals('Success', targetInvoiceLineItem.ResponseMessage__c);
		System.assertEquals('SC', targetInvoiceLineItem.ResponseCode__c);
	}

	public class SuccessInvoiceRetryMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateInvoiceApiCallout.RequestDataModel>.class);
            List<CreateInvoiceApiCallout.RequestDataModel> requestData = ( List<CreateInvoiceApiCallout.RequestDataModel>)requestDataObj;
			// START MOCK RESPONSE
            List<CreateInvoiceApiCallout.InvoiceResponse> responseInvoiceData = new List<CreateInvoiceApiCallout.InvoiceResponse>();
			CreateInvoiceApiCallout.InvoiceResponse invoiceResponse = new CreateInvoiceApiCallout.InvoiceResponse();
			invoiceResponse.DocLine = new List<CreateInvoiceApiCallout.InvoiceLineItemResponse>();
			invoiceResponse.SFDocId = succesDocId;
			invoiceResponse.ResponseCode = 'SC';
			invoiceResponse.Message = 'Success';
			CreateInvoiceApiCallout.InvoiceLineItemResponse invoiceLineItemResponse = new CreateInvoiceApiCallout.InvoiceLineItemResponse();
			invoiceLineItemResponse.ResponseCode = 'SC';
			invoiceLineItemResponse.SFDocLineId = succesDocLineId;
			invoiceLineItemResponse.Message = 'Success';
			invoiceResponse.DocLine.add(invoiceLineItemResponse);

			CreateInvoiceApiCallout.InvoiceResponse invoiceResponse2 = new CreateInvoiceApiCallout.InvoiceResponse();
			invoiceResponse2.DocLine = new List<CreateInvoiceApiCallout.InvoiceLineItemResponse>();
			invoiceResponse2.SFDocId = succesDocId2;
			invoiceResponse2.ResponseCode = 'SC';
			invoiceResponse2.Message = 'Success';
			CreateInvoiceApiCallout.InvoiceLineItemResponse invoiceLineItemResponse2 = new CreateInvoiceApiCallout.InvoiceLineItemResponse();
			invoiceLineItemResponse2.ResponseCode = 'SC';
			invoiceLineItemResponse2.SFDocLineId = succesDocLineId2;
			invoiceLineItemResponse2.Message = 'Success';
			invoiceResponse.DocLine.add(invoiceLineItemResponse2);

			responseInvoiceData.add(invoiceResponse);
			responseInvoiceData.add(invoiceResponse2);
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseInvoiceData));
            res.setStatusCode(200);
            return res;
        }
    }

	@isTest
	static void craeteInvoiceCalloutTestRetrySuccess(){
		Test.setMock(HttpCalloutMock.class, new CreateInvoiceApiCalloutBatchTest.SuccessInvoiceRetryMockResp());
		DataMaker dataMaker = DataMaker.getInstance();
		// CREATE PROJECT
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// CREATE FLOOR
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// CREATE UNIT TYPE
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// CREATE UNIT
		Product2 unit1 = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert unit1;
		// CREATE ACCOUNT
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'BE8');
		insert account;
		// CREATE OPPORTUNITY
		Opportunity opp = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.newInstance(2024, 10, 1),
			'Open',
			unit1.Id,
			'Foreign',
			null,
			testProject.Id
		);
		opp.DoNotSendInvoice__c = true;
		insert opp;
		// CREATE OPP PAYMENT
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opp.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opp.Id,
			'Contract',
			50000,
			Date.newInstance(2024, 11, 15),
			2
		);
		insert new List<OpportunityPayment__c>{reservationOppPayment , contractOppPayment};

		Date dueDate = Date.newInstance(2024, 11, 1);
		Date invoiceDate = Date.newInstance(2024, 10, 27);
		// CREATE INVOICE
		Invoice__c reservationInvoice = dataMaker.createInvoice(opp.Id, dueDate, invoiceDate, opp.DoNotSendInvoice__c, opp.Account.AddressEN__c);
		reservationInvoice.LastCreatedStatusInPojjaman__c = 'Fail';
		Invoice__c contractInvoice = dataMaker.createInvoice(opp.Id, dueDate, invoiceDate, opp.DoNotSendInvoice__c, opp.Account.AddressEN__c);
		insert new List<Invoice__c>{reservationInvoice,contractInvoice};
		succesDocId = reservationInvoice.Id;
		succesDocId2 = contractInvoice.Id;
		// CREATE INVOICE LINE ITEM
		InvoiceLineItem__c ivline = dataMaker.createInvoiceLineItem(reservationInvoice.Id,reservationOppPayment.Id,50000,dueDate,'');
		InvoiceLineItem__c ivline2 = dataMaker.createInvoiceLineItem(contractInvoice.Id,contractOppPayment.Id,50000,dueDate,'');
		insert new List<InvoiceLineItem__c>{ivline,ivline2};
		succesDocLineId = ivline.Id;
		succesDocLineId2 = ivline2.Id;
		Test.startTest();
		// EXECUTE BATCH
		CreateInvoiceApiCalloutBatch batch = new CreateInvoiceApiCalloutBatch();
		Database.executeBatch(batch, 2000);
		Test.stopTest();
		Invoice__c targetInvoice = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM Invoice__c WHERE Id =: reservationInvoice.Id LIMIT 1];
		Invoice__c targetInvoice2 = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM Invoice__c WHERE Id =: contractInvoice.Id LIMIT 1];
		InvoiceLineItem__c targetInvoiceLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM InvoiceLineItem__c WHERE Id =: ivline.Id LIMIT 1];
		System.assertEquals('Success', targetInvoice.ResponseMessage__c);
		System.assertEquals('SC', targetInvoice.ResponseCode__c);
		System.assertEquals('Success', targetInvoice2.ResponseMessage__c);
		System.assertEquals('SC', targetInvoice2.ResponseCode__c);
		System.assertEquals('Success', targetInvoiceLineItem.ResponseMessage__c);
		System.assertEquals('SC', targetInvoiceLineItem.ResponseCode__c);
	}

	public class SystemFailInvoiceMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateInvoiceApiCallout.RequestDataModel>.class);
            List<CreateInvoiceApiCallout.RequestDataModel> requestData = ( List<CreateInvoiceApiCallout.RequestDataModel>)requestDataObj;
			// START MOCK RESPONSE
            List<CreateInvoiceApiCallout.InvoiceResponse> responseInvoiceData = new List<CreateInvoiceApiCallout.InvoiceResponse>();
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseInvoiceData));
            res.setStatusCode(500);
            return res;
        }
    }

	@isTest
	static void craeteAccountAndContactCalloutTestSystemFail(){
		Test.setMock(HttpCalloutMock.class, new CreateInvoiceApiCalloutBatchTest.SystemFailInvoiceMockResp());
		DataMaker dataMaker = DataMaker.getInstance();
		// CREATE PROJECT
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// CREATE FLOOR
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// CREATE UNIT TYPE
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// CREATE UNIT
		Product2 unit1 = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert unit1;
		// CREATE ACCOUNT
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'BE8');
		insert account;
		// CREATE OPPORTUNITY
		Opportunity opp = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.newInstance(2024, 10, 1),
			'Open',
			unit1.Id,
			'Foreign',
			null,
			testProject.Id
		);
		opp.DoNotSendInvoice__c = true;
		insert opp;
		// CREATE OPP PAYMENT
		OpportunityPayment__c reservationOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opp.Id,
			'opp',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		insert reservationOppPaymentOpp1;
		Date dueDate = Date.newInstance(2024, 11, 1);
		Date invoiceDate = Date.newInstance(2024, 10, 27);
		// CREATE INVOICE
		Invoice__c invoice = dataMaker.createInvoice(opp.Id, dueDate, invoiceDate, opp.DoNotSendInvoice__c, opp.Account.AddressEN__c);
		insert invoice;
		succesDocId = invoice.Id;
		// CREATE INVOICE LINE ITEM
		InvoiceLineItem__c ivline = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPaymentOpp1.Id,50000,dueDate,'');
		insert ivline;
		succesDocLineId = ivline.Id;
		Test.startTest();
		// EXECUTE BATCH
		CreateInvoiceApiCalloutBatch batch = new CreateInvoiceApiCalloutBatch();
		Database.executeBatch(batch, 2000);
		Test.stopTest();
		Invoice__c targetInvoice = [SELECT Id,ResponseMessage__c,ResponseCode__c,LastCreatedStatusInPojjaman__c FROM Invoice__c WHERE Id =: invoice.Id LIMIT 1];
		InvoiceLineItem__c targetInvoiceLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM InvoiceLineItem__c WHERE Id =: ivline.Id LIMIT 1];
		System.assertEquals('ERR', targetInvoice.ResponseCode__c);
		System.assertEquals('ERR', targetInvoiceLineItem.ResponseCode__c);
	}

}