force-app/main/default/objects/Account/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <formula>TRIM(
  IF(NOT(ISBLANK(AddressNoEN__c)), AddressNoEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(SubDistrictEN__c)), SubDistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(DistrictEN__c)), DistrictEN__c &amp; &quot;, &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ProvinceEN__c)), ProvinceEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(ZipCodeEN__c)), ZipCodeEN__c &amp; &quot; &quot;, &quot;&quot;) +
  IF(NOT(ISBLANK(TEXT(CountryEN__c))), TEXT(CountryEN__c), &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address EN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <formula>Unit__r.AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CoBuyerName__c.field-meta.xml
<CustomField>
    <fullName>CoBuyerName__c</fullName>
    <label>Co-Buyer Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <formula>(  BLANKVALUE(UnitPrice__c, 0.00)  -( BLANKVALUE(UnitPrice__c, 0.00) *BLANKVALUE(TotalDiscountPercent__c, 0.00) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPricePerSqm__c.field-meta.xml
<CustomField>
    <fullName>NetPricePerSqm__c</fullName>
    <formula>IF( AreaSqm__c &gt; 0,  NetPrice__c / AreaSqm__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price/Sq.m</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <formula>PaymentMethod__r.PaymentDate__c</formula>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/RemainingAmount__c.field-meta.xml
<CustomField>
    <fullName>RemainingAmount__c</fullName>
    <label>RemainingAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Not for Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CompanyAddress__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress__c</fullName>
    <label>Company Address</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <description>Developer name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyPhone__c.field-meta.xml
<CustomField>
    <fullName>CompanyPhone__c</fullName>
    <label>Company Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyTaxID__c.field-meta.xml
<CustomField>
    <fullName>CompanyTaxID__c</fullName>
    <label>Company Tax ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectLogo__c.field-meta.xml
<CustomField>
    <fullName>ProjectLogo__c</fullName>
    <label>Project Logo</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>สถานะของ Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentSummaryFormController.cls
public with sharing class PaymentSummaryFormController {
	private final Id opportunityId;
	public PaymentSummaryWrapper paymentSummaryInstance { get; set; }

	public static PaymentSummaryFormController instance {get; set;}

	public static PaymentSummaryFormController getInstanceCtrl() {
		if (instance == null) {
			instance = new PaymentSummaryFormController();
		}
		return instance;
	}

	public PaymentSummaryFormController() {
		if(opportunityId == null){
			opportunityId = ApexPages.currentPage().getParameters().get('id');
		}
	}

	public PaymentSummaryWrapper getPaymentSummary() {
		if(paymentSummaryInstance == null){
			Opportunity opportunity = OpportunitySelector.getInstance().getById(opportunityId);
			List<OpportunityPayment__c> oppPayments = OpportunityPaymentSelector.getInstance().getForPaymentSummaryForm(opportunityId);
			List<PaymentReceiptLineItem__c> receiptLineItems = PaymentReceiptLineItemSelector.getInstance().getByOpportunityId(opportunityId);

			paymentSummaryInstance = new PaymentSummaryWrapper(opportunity, oppPayments, receiptLineItems);
		}
		return paymentSummaryInstance;
	}

	public class PaymentSummaryWrapper {
		public OppDetailWrapper oppDetail {get; set;}
		public PaymentItemWrapper paymentItem {get; set;}
		public PaymentFooterWrapper paymentFooter {get; set;}

		public PaymentSummaryWrapper(
			Opportunity opportunity,
			List<OpportunityPayment__c> oppPayments,
			List<PaymentReceiptLineItem__c> receiptLineItems
		){
			oppDetail = new OppDetailWrapper(opportunity);
			paymentItem = new PaymentItemWrapper(opportunity, oppPayments, receiptLineItems);
			paymentFooter = new PaymentFooterWrapper();
		}
	}

	public class OppDetailWrapper {
		public String projectLogoUrl {get; set;}
		public String companyName {get; set;}
		public String companyAddress {get; set;}
		public String companyPhone {get; set;}
		public String companyTaxId {get; set;}
		public String printDate {get; set;}
		public String unitName {get; set;}
		public String projectName {get; set;}
		public String paymentSummaryDate {get; set;}

		public String customerName {get; set;}
		public String customerAddress {get; set;}
		public String customerContact {get; set;}
		public String netPrice {get; set;}
		public String netPricePerSqm {get; set;}
		public String unitSize {get; set;}
		public String unitType {get; set;}

		public OppDetailWrapper(Opportunity opportunity){
			projectLogoUrl = PDFUtility.getInstance().getImageSrc(opportunity.Project__r.ProjectLogo__c);
			companyName = opportunity.Project__r.CompanyName__c;
			companyAddress = opportunity.Project__r.CompanyAddress__c;
			companyPhone = opportunity.Project__r.CompanyPhone__c;
			companyTaxId = opportunity.Project__r.CompanyTaxID__c;
			printDate = DateUtility.getInstance().toDateString('d MMM yyyy', System.today());
			unitName = opportunity.Unit__r.Name;
			projectName = opportunity.Project__r.Name;

			customerName = opportunity.CoBuyerName__c;
			customerAddress = opportunity.Account.AddressEN__c;
			netPrice = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(opportunity.NetPrice__c);
			netPricePerSqm = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(opportunity.NetPricePerSqm__c);
			unitSize = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(opportunity.AreaSqm__c);
			unitType = opportunity.Unit__r.UnitType__r.Name;

			customerContact = getCustomerContact(opportunity);
		}

		private String getCustomerContact(Opportunity opportunity){
			String contact = '';
			if(opportunity.ContactPerson__c != null){
				return PDFUtility.getInstance().getContactText(opportunity.ContactPerson__r.MobilePhone, opportunity.ContactPerson__r.Email);
			}
			else{
				return PDFUtility.getInstance().getContactText(opportunity.Account.Phone, opportunity.Account.Email__c);
			}
		}
	}

	public class PaymentItemWrapper {
		public String totalReceiveAmount {get; set;}
		public String totalReceivePercent {get; set;}
		public List<PaymentItemDetailWrapper> paymentItemDetails {get; set;}

		public PaymentItemWrapper(
			Opportunity opportunity,
			List<OpportunityPayment__c> oppPayments,
			List<PaymentReceiptLineItem__c> receiptLineItems
		){
			paymentItemDetails = new List<PaymentItemDetailWrapper>();
			Decimal sumReceiveAmount = 0;

			Map<Id, OpportunityPayment__c> oppPaymentMapById = new Map<Id, OpportunityPayment__c>(oppPayments);
			Map<Id, List<PaymentReceiptLineItem__c>> receiptLinesMapByOppPaymentId = getReceiptLineItemsMapByOppPaymentId(receiptLineItems);

			Integer lineNumber = 1;
			for (Id oppPaymentId : oppPaymentMapById.keySet()) {
				OpportunityPayment__c oppPayment = oppPaymentMapById.get(oppPaymentId);
				List<PaymentReceiptLineItem__c> receiptLines = receiptLinesMapByOppPaymentId.get(oppPaymentId);

				if(receiptLines == null){
					paymentItemDetails.add(new PaymentItemDetailWrapper(oppPayment, lineNumber));
				}
				else{
					for (Integer i = 0; i < receiptLines.size(); i++) {
						PaymentReceiptLineItem__c receiptLine = receiptLines.get(i);
						paymentItemDetails.add(
							new PaymentItemDetailWrapper(
								oppPayment,
								receiptLine,
								lineNumber,
								i == 0
							)
						);

						sumReceiveAmount += receiptLine.ReceivedAmount__c;
					}
				}

				lineNumber++;
			}

			totalReceiveAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(sumReceiveAmount);
			if(sumReceiveAmount == 0){
				totalReceivePercent = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(0.00);
			}
			else {
				totalReceivePercent = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(
					(sumReceiveAmount / opportunity.NetPrice__c *100 )
				);
			}
		}

		private Map<Id, List<PaymentReceiptLineItem__c>> getReceiptLineItemsMapByOppPaymentId(List<PaymentReceiptLineItem__c> receiptLineItems){
			Map<Id, List<PaymentReceiptLineItem__c>> receiptLinesMapByOppPaymentId = new Map<Id, List<PaymentReceiptLineItem__c>>();
			for (PaymentReceiptLineItem__c receiptLineItem : receiptLineItems) {
				List<PaymentReceiptLineItem__c> receiptLines = receiptLinesMapByOppPaymentId.get(receiptLineItem.OpportunityPayment__c);

				if(receiptLines == null){
					receiptLinesMapByOppPaymentId.put(
						receiptLineItem.OpportunityPayment__c,
						new List<PaymentReceiptLineItem__c>{ receiptLineItem }
					);
				}
				else{
					receiptLines.add(receiptLineItem);
				}
			}
			return receiptLinesMapByOppPaymentId;
		}
	}

	public class PaymentItemDetailWrapper {
		public String no {get; set;}
		public String description {get; set;}
		public String dueDate {get; set;}
		public String paymentAmount {get; set;}
		public String paymentStatus {get; set;}
		public String receiveDate {get; set;}
		public String receiveAmount {get; set;}
		public String remainingBalanceAmount {get; set;}

		public PaymentItemDetailWrapper(OpportunityPayment__c oppPayment, Integer lineNumber){
			no = String.valueOf(lineNumber);
			description = oppPayment.Term__c;
			dueDate = DateUtility.getInstance().toDateString('dd MMM yyyy', oppPayment.DueDate__c);
			paymentAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(oppPayment.Amount__c);
			paymentStatus = oppPayment.PaymentStatus__c;
			receiveDate = DateUtility.getInstance().toDateString('dd MMM yyyy', oppPayment.ReceivedDate__c);

			if(String.isBlank(paymentStatus)){
				receiveAmount = '';
				remainingBalanceAmount = '';
			}
			else {
				receiveAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(oppPayment.ReceivedAmount__c);
				remainingBalanceAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(oppPayment.Remaining__c);
			}
		}

		public PaymentItemDetailWrapper(
			OpportunityPayment__c oppPayment,
			PaymentReceiptLineItem__c receiptLine,
			Integer lineNumber,
			Boolean isSetPaymentDescription
		){
			if(isSetPaymentDescription){
				no = String.valueOf(lineNumber);
				description = oppPayment.Term__c;
				dueDate = DateUtility.getInstance().toDateString('dd MMM yyyy', oppPayment.DueDate__c);
				paymentAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(oppPayment.Amount__c);
			}
			paymentStatus = receiptLine.Status__c;
			receiveDate = DateUtility.getInstance().toDateString('dd MMM yyyy', receiptLine.ReceivedDate__c);
			receiveAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(receiptLine.ReceivedAmount__c);
			remainingBalanceAmount = NumberUtility.getInstance().setDecToFormatCommaTwoDigits(receiptLine.RemainingAmount__c);
		}
	}

	public class PaymentFooterWrapper {
		public String issuedBy {get; set;}
		public String printDate {get; set;}

		public PaymentFooterWrapper(){
			issuedBy = UserInfo.getName();
			printDate = DateUtility.getInstance().toDateString('dd MMM yyyy', System.today());
		}
	}

}