force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>เทียบเท่ากับ DueDate__c ของ OpportunityPayment__c ในรอบนั้นๆ</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateRelatedInvFilesAndSendEmailBatch.cls
public with sharing class CreateRelatedInvFilesAndSendEmailBatch implements Database.Batchable<sObject> {
    private Date dueDate;

    public CreateRelatedInvFilesAndSendEmailBatch(Date invoiceDueDate) {
        dueDate = invoiceDueDate;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> queryStringList = new List<String> {
            'SELECT Id, Name, Opportunity__c, InvoiceDate__c, DueDate__c, DoNotSendInvoice__c, Opportunity__r.ContactPerson__r.Email, Opportunity__r.Account.Email__c',
			'FROM Invoice__c',
			'WHERE DueDate__c = ' + String.valueOf(dueDate)
        };

        String queryString = String.join(queryStringList, ' ');

        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext BC, List<Invoice__c> invoices) {
        InvoiceService.getInstance().insertInvoiceAndPaymentSummaryFiles(invoices);
        InvoiceService.getInstance().sendEmailWithAttachment(invoices);
    }

    public void finish(Database.BatchableContext BC) {
    }
}