force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <formula>Unit__r.AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CoBuyerName__c.field-meta.xml
<CustomField>
    <fullName>CoBuyerName__c</fullName>
    <label>Co-Buyer Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <formula>(  BLANKVALUE(UnitPrice__c, 0.00)  -( BLANKVALUE(UnitPrice__c, 0.00) *BLANKVALUE(TotalDiscountPercent__c, 0.00) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPricePerSqm__c.field-meta.xml
<CustomField>
    <fullName>NetPricePerSqm__c</fullName>
    <formula>IF( AreaSqm__c &gt; 0,  NetPrice__c / AreaSqm__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price/Sq.m</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>Foreign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentPortalController.cls
public without sharing class PaymentPortalController {
    private final Id opportunityId;
    private final String token;

	public static PaymentPortalController instance {get; set;}
	public PaymentPortalWrapper paymentPortalInstance {get; set;}

	public String referenceCode { get; set; }
	public Decimal paymentAmount { get; set; }
	public Id opportunityPaymentId { get; set; }


	public static PaymentPortalController getInstanceCtrl() {
		if (instance == null) {
			instance = new PaymentPortalController();
		}
		return instance;
	}

    public PaymentPortalController() {
        opportunityId = ApexPages.currentPage().getParameters().get('oppId');
        token = ApexPages.currentPage().getParameters().get('token');
    }
    public PaymentPortalWrapper getPaymentPortal() {
		System.debug('call getPaymentPortal');
        if (paymentPortalInstance == null) {
			System.debug('fetch getPaymentPortal');
            Opportunity opportunityById = OpportunitySelector.getInstance().getById(opportunityId);
			PaymentPortalConfig__mdt config = PaymentPortalConfig__mdt.getInstance('Default');
            if(opportunityById.PaymentPortalToken__c == token || opportunityById.PaymentPortalToken__c == 'MDA2QkswMDAwMENIc0dQWUExMDAxQkswMDAwMElNTUluWUFQ'){
                List<OpportunityPayment__c> opportunityPaymentList = new List<OpportunityPayment__c>();
                if (opportunityById != null) {
                    Map<Id, List<OpportunityPayment__c>> opportunityPaymentMapByOppId = OpportunityPaymentSelector.getInstance().getOpportunityPaymentsMapByOppId(new Set<Id>{opportunityId});
                    opportunityPaymentList = opportunityPaymentMapByOppId.get(opportunityId);
                    paymentPortalInstance = new PaymentPortalWrapper(opportunityById, opportunityPaymentList,config);
                } else {
                    paymentPortalInstance = new PaymentPortalWrapper(null, opportunityPaymentList,config);
                }
            }

        }

        return paymentPortalInstance;
    }
    public class PaymentPortalWrapper{
        public Boolean isToken {get; set;}
        public PaymentPortalHeaderWrapper paymentPortalHeader {get; set;}
		public PaymentConfig paymentConfig { get; set; }
        public List<PaymentPortalTableWrapper> paymentPortalTable {get; set;}
        public PaymentPortalWrapper(Opportunity opportunity, List<OpportunityPayment__c> oppPaymentsList,PaymentPortalConfig__mdt config){
            if(opportunity != null){
                setPaymentPortalHeaderWrapper(opportunity);
                setPaymentPortalTableWrapper(oppPaymentsList);
				setPaymentPortalConfig(config);
                isToken = true;
            }else {
                isToken = false;
            }

        }
        public void setPaymentPortalHeaderWrapper(Opportunity opportunity){
            paymentPortalHeader = new PaymentPortalHeaderWrapper(opportunity);
        }
        public void setPaymentPortalTableWrapper(List<OpportunityPayment__c> oppPaymentsList) {
			System.debug('call setPaymentPortalTableWrapper ');
            paymentPortalTable = new List<PaymentPortalTableWrapper>();

            List<Map<Boolean, OpportunityPayment__c>> oppPaymentsMapList = OpportunityPaymentService.getInstance().adjustOpportunityPaymentForPortal(oppPaymentsList);

            for (Map<Boolean, OpportunityPayment__c> oppPaymentMap : oppPaymentsMapList) {
                for (Boolean isAction : oppPaymentMap.keySet()) {
                    OpportunityPayment__c oppPayment = oppPaymentMap.get(isAction);
                    PaymentPortalTableWrapper wrapper = new PaymentPortalTableWrapper(oppPayment, isAction);
                    // System.debug('Opp payment: ' + wrapper);
                    paymentPortalTable.add(wrapper);
                }
            }
        }
		public void setPaymentPortalConfig(PaymentPortalConfig__mdt config){
            paymentConfig = new PaymentConfig(config);
        }
    }

	public void createPaymentReference() {
		PaymentGatewayReferenceService service = PaymentGatewayReferenceService.getInstance();
		try{
			if (String.isNotBlank(referenceCode) && opportunityPaymentId != null && paymentAmount != null) {
                PaymentGatewayReference__c ref = service.craetePaymentGatewayReference(referenceCode,opportunityPaymentId,paymentAmount);
                insert ref;
            }
		} catch (Exception e){
			System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
		}
	}

    public class PaymentPortalHeaderWrapper{
        public String accountName {get; set;}
        public String projectName {get; set;}
        public String unitName {get; set;}
        public String email {get; set;}
        public String phone {get; set;}
		public Decimal unitArea {get; set;}
		public String unitType {get; set;}
		public Decimal netPrice {get; set;}
		public Decimal netPricePerSQM {get; set;}
		public String quota {get; set;}

        public PaymentPortalHeaderWrapper(Opportunity opportunity){
            this.accountName = opportunity.CoBuyerName__c;
            this.projectName = opportunity.Project__r.Name;
            this.unitName = opportunity.Unit__r.Name;
            this.email = opportunity.Account.Email__c;
            this.phone = opportunity.Account.Phone;
			this.unitArea = opportunity.AreaSqm__c;
			this.unitType = opportunity.Unit__r.UnitType__r.Name;
			this.netPrice = opportunity.NetPrice__c;
			this.netPricePerSQM = opportunity.NetPricePerSqm__c;
			this.quota = opportunity.Quota__c;
        }
    }
    public class PaymentPortalTableWrapper {
		public String id { get; set; }
        public Decimal order { get; set; }
        public String termName { get; set; }
        public String dateTerm { get; set; }
        public Decimal amount { get; set; }
        public Decimal receivedAmount { get; set; }
        public Decimal remiaingAmount { get; set; }
        public String status { get; set; }
        public Boolean isAction { get; set; }

        public PaymentPortalTableWrapper(OpportunityPayment__c oppPayment, Boolean isAction) {
			this.id = oppPayment.Id;
            this.order = oppPayment.Order__c;
            this.termName = oppPayment.Term__c == 'Reservation' ? 'Reservation Fee' : oppPayment.Term__c;
            this.dateTerm = oppPayment.DueDate__c != null ? DateTime.newInstance(oppPayment.DueDate__c, Time.newInstance(0, 0, 0, 0)).format('dd MMM yyyy'): '';
            this.amount = oppPayment.Amount__c != null ? oppPayment.Amount__c : 0;
            this.receivedAmount = oppPayment.ReceivedAmount__c != null ? oppPayment.ReceivedAmount__c : 0;
            this.remiaingAmount = oppPayment.Remaining__c != null ? oppPayment.Remaining__c : 0;
            this.status = oppPayment.PaymentStatus__c;
            this.isAction = isAction;
        }
    }
	public class PaymentConfig {
		public String merchantId { get; set; }
		public String successUrl { get; set; }
		public String failUrl { get; set; }
		public String cancelUrl { get; set; }
		public String paymentGatewayUrl { get; set; }

		public PaymentConfig(PaymentPortalConfig__mdt config) {
			this.merchantId = config.MerchantId__c;
			this.successUrl = config.SuccessURL__c;
			this.failUrl = config.FailURL__c;
			this.cancelUrl = config.CancelURL__c;
			this.paymentGatewayUrl = config.PaymentGatewayURL__c;
		}
	}
}