force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>อีเมล</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxID__c.field-meta.xml
<CustomField>
    <fullName>TaxID__c</fullName>
    <description>เลขที่ภาษี</description>
    <label>Tax ID</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CoBuyerName__c.field-meta.xml
<CustomField>
    <fullName>CoBuyerName__c</fullName>
    <label>Co-Buyer Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__c</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/TotalReceiveAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalReceiveAmount__c</fullName>
    <label>Total Receive Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <formula>if( ISBLANK(Text(CancelReason__c)),false,True)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/ReceiptNo__c.field-meta.xml
<CustomField>
    <fullName>ReceiptNo__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>เลขที่ใบเสร็จ</description>
    <externalId>true</externalId>
    <label>Receipt no.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/TotalReceiveAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalReceiveAmount__c</fullName>
    <label>Total Receive Amount</label>
    <summarizedField>PaymentReceiptLineItem__c.ReceivedAmount__c</summarizedField>
    <summaryForeignKey>PaymentReceiptLineItem__c.PaymentReceipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/RemainingAmount__c.field-meta.xml
<CustomField>
    <fullName>RemainingAmount__c</fullName>
    <label>RemainingAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CompanyAddress__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress__c</fullName>
    <label>Company Address</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <description>Developer name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyPhone__c.field-meta.xml
<CustomField>
    <fullName>CompanyPhone__c</fullName>
    <label>Company Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompanyTaxID__c.field-meta.xml
<CustomField>
    <fullName>CompanyTaxID__c</fullName>
    <label>Company Tax ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectLogo__c.field-meta.xml
<CustomField>
    <fullName>ProjectLogo__c</fullName>
    <label>Project Logo</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptFormController.cls
public without sharing class PaymentReceiptFormController {
	private final Id paymentReceiptId;


	public static PaymentReceiptFormController instance {get; set;}
	public PaymentReceiptWrapper paymentReceiptInstance {get; set;}
	public static PaymentReceiptFormController getInstanceCtrl() {
		if (instance == null) {
			instance = new PaymentReceiptFormController();
		}
		return instance;
	}
	public PaymentReceiptFormController() {
		paymentReceiptId = ApexPages.currentPage().getParameters().get('Id');

	}
	public PaymentReceiptWrapper getPaymentReceipt(){
		if(paymentReceiptInstance == null){
			Map<Id, PaymentReceipt__c> paymentReceiptMapById = PaymentReceiptSelector.getInstance().getPaymentReceiptWithLineItemMapById(new Set<Id>{paymentReceiptId});
			Map<Id, List<PaymentMethod__c>> paymentMethodMapById = PaymentMathodSelector.getInstance().getPaymentMethodMapByPaymentReceiptId(new Set<Id>{paymentReceiptId});
			List<PaymentMethod__c> paymentMethods = paymentMethodMapById.get(paymentReceiptId);
			PaymentReceipt__c paymentReceipt = paymentReceiptMapById.get(paymentReceiptId);
			Opportunity opportunity = OpportunitySelector.getInstance().getById(paymentReceipt.Opportunity__c);
			Map<Id,Project__c> projectMapById = ProjectSelector.getInstance().getProjectById(new Set<Id>{opportunity.Project__c});
			Project__c getProject = projectMapById.get(opportunity.Project__c);
			// String imageUrl = PDFUtility.getInstance().getImageSrc(getProject.ProjectLogo__c);
			String imageUrl = getProject.ProjectLogoPublicURL__c;
			List<PaymentReceiptLineItem__c> paymentReceiptLineItems = paymentReceipt.Payment_Transactions__r;
			List<PaymentReceiptLineItem__c> updatePaymentReceiptLineItems = PaymentReceiptService.getInstance().aggregatePaymentReceiptLineItems(paymentReceiptLineItems);
			paymentReceiptInstance = new PaymentReceiptWrapper(paymentReceipt,opportunity,updatePaymentReceiptLineItems,paymentMethods,imageUrl);
		}
		return paymentReceiptInstance;
	}

	public class PaymentReceiptWrapper{
		public Boolean isCash {get; set;}
		public Boolean isCreditCard {get; set;}
		public Boolean isDebitCard {get; set;}
		public Boolean isCheque  {get; set;}
		public Boolean isBankTransferLocal {get; set;}
		public Boolean isBankTransferInter {get; set;}
		public Boolean isBankDraft {get; set;}
		// Phase2: add new variable
		public Boolean isUpgrade {get; set;}
		public Boolean isDowngrade {get; set;}
		public Boolean isMovePayment {get; set;}
		public PaymentReceiptHeaderWrapper paymentReceiptHeader {get; set;}
		public OpportunityWrapper oppWrapper {get; set;}
		public List<PaymentReceiptLineItemWrapper> paymentReceiptLineItemWrapper {get; set;}
		public Map<String , PaymentMethodWrapper> paymentMethodWrapperMap {get; set;}
		public PaymentReceiptWrapper(){

		}
		/**
		 * Phase2
		 * Details:
		 * - Modify logic to send PaymentReceipt__c.CoBuyerName__c to constructor
		 */
		public PaymentReceiptWrapper(PaymentReceipt__c paymentReceipt, Opportunity opportunity,List<PaymentReceiptLineItem__c> paymentReceiptLineItems,  List<PaymentMethod__c> paymentMethods, String imgUrl){
			setPaymentReceiptHeader(paymentReceipt.ReceiptNo__c, paymentReceipt.AccountAddress__c, paymentReceiptLineItems[0].PaymentReceipt__r.TotalReceiveAmount__c, imgUrl, paymentReceipt.IsCancel__c , paymentReceipt.CoBuyerName__c);
			setOpportunity(opportunity);
			setPaymentReceiptLineItem(paymentReceiptLineItems);
			setPaymentMethod(paymentMethods);
		}
		/**
		 * Phase2
		 * Details:
		 * - Modify logic to send PaymentReceipt__c.CoBuyerName__c to constructor
		 */
		public void setPaymentReceiptHeader(String receiptNo, String accountAddress, Decimal totalReceiveAmount,String imageUrl , Boolean isCancelled , String coBuyerName){
			paymentReceiptHeader = new PaymentReceiptHeaderWrapper(receiptNo,accountAddress,totalReceiveAmount,imageUrl,isCancelled,coBuyerName);
		}
		public void setOpportunity(Opportunity opportunity){
			oppWrapper = new OpportunityWrapper(opportunity);
		}
		public void setPaymentReceiptLineItem(List<PaymentReceiptLineItem__c> paymentReceiptLineItems){
			paymentReceiptLineItemWrapper = new List<PaymentReceiptLineItemWrapper>();
			Integer count = 1;
			for(PaymentReceiptLineItem__c paymentReceiptLineItem : paymentReceiptLineItems){
				PaymentReceiptLineItemWrapper lineItemWrapper = new PaymentReceiptLineItemWrapper(paymentReceiptLineItem,count);
				paymentReceiptLineItemWrapper.add(lineItemWrapper);
				count++;
			}
		}
		/**
		 * Phase2
		 * Details:
		 * - Modify logic to mapping new PaymentType__c
		 */
		public void setPaymentMethod(List<PaymentMethod__c> paymentMethods){
			paymentMethodWrapperMap = new Map<String, PaymentMethodWrapper>();

			for(PaymentMethod__c paymentMethod : paymentMethods){
				PaymentMethodWrapper paymentMethodWrapper = paymentMethodWrapperMap.get(paymentMethod.PaymentType__c);
				if(paymentMethodWrapper == null){
					paymentMethodWrapperMap.put(paymentMethod.PaymentType__c, new PaymentMethodWrapper(paymentMethod));
				}
				else{
					paymentMethodWrapper.addPaymentMethodList(paymentMethod);
				}
				PaymentMethodItemWrapper paymentMethodDetail = new PaymentMethodItemWrapper(paymentMethod);
			}
			isCash = paymentMethodWrapperMap.get('Cash') != null;
			isCreditCard =  paymentMethodWrapperMap.get('Credit Card') != null;
			isDebitCard = paymentMethodWrapperMap.get('Debit Card') != null;
			isCheque = paymentMethodWrapperMap.get('Cashier Cheque') != null;
			isBankTransferLocal = paymentMethodWrapperMap.get('Bank Transfer (Local)') != null;
			isBankTransferInter = paymentMethodWrapperMap.get('Bank Transfer (International)') != null;
			isBankDraft = paymentMethodWrapperMap.get('Bank Draft') != null;
			isUpgrade = paymentMethodWrapperMap.get('Upgrade') != null;
			isDowngrade = paymentMethodWrapperMap.get('Downgrade') != null;
			isMovePayment = paymentMethodWrapperMap.get('Move Payment') != null;
		}

	}
	public class OpportunityWrapper {
		public String companyName {get; set;}
		public String companyAddress {get; set;}
		public String companyPhone{get; set;}
		public String companyTaxID{get; set;}
		public String unitName{get; set;}
		public String towerName{get; set;}
		public String projectName{get; set;}
		public String coBuyerName{get; set;}
		public String accountTaxID{get; set;}
		public String customerContact{get; set;}
		public Boolean isTaxId {get; set;}
		public OpportunityWrapper(){ }

		public OpportunityWrapper(Opportunity opportunity){
			companyName = opportunity.Project__r.CompanyName__c;
			companyAddress = opportunity.Project__r.CompanyAddress__c;
			companyPhone = opportunity.Project__r.CompanyPhone__c;
			companyTaxID = opportunity.Project__r.CompanyTaxID__c;
			unitName = opportunity.Unit__r.Name;
			projectName = opportunity.Project__r.Name;
			coBuyerName = opportunity.CoBuyerName__c;
			/**
			 * Phase2
			 * Details:
			 * - Modify method to show Tower Name
			 */
			towerName = opportunity.Tower__c;
			if(opportunity.Account.TaxID__c != null){
				accountTaxID = opportunity.Account.TaxID__c;
				isTaxId = true;
			}else{
				isTaxId = false;
			}

			customerContact = getCustomerContact(opportunity);
		}

		private String getCustomerContact(Opportunity opportunity){
			String contact = '';
			if(opportunity.ContactPerson__c != null){
				return PDFUtility.getInstance().getContactText(opportunity.ContactPerson__r.MobilePhone, opportunity.ContactPerson__r.Email);
			}
			else{
				return PDFUtility.getInstance().getContactText(opportunity.Account.Phone, opportunity.Account.Email__c);
			}
		}
	}


	public class PaymentReceiptLineItemWrapper {
		public String order{get;set;}
		public String oppPaymentTerm{get; set;}
		public String oppPaymentDueDate{get; set;}
		public String oppPaymentRemainingAmount{get; set;}
		public String status{get; set;}
		public String oppPaymentReceiptAmount{get; set;}

		public PaymentReceiptLineItemWrapper(){

		}

		/**
		 * Phase2
		 * Details:
		 * - Modify method to show detail for Novation Receipt
		 */
		public PaymentReceiptLineItemWrapper(PaymentReceiptLineItem__c paymentReceiptLineItem,Integer orderInt){
			DateUtility dateUtility = DateUtility.getInstance();
			NumberUtility numberUtility = NumberUtility.getInstance();
			Boolean isNovatedReceipt = paymentReceiptLineItem.PaymentReceipt__r.ReceiptType__c == GlobalConstants.RECEIPT_TYPE_NOVATION;
			order = String.valueOf(orderInt);
			oppPaymentTerm =  isNovatedReceipt ? GlobalConstants.RECEIPT_TYPE_NOVATION : paymentReceiptLineItem.OpportunityPayment__r.Term__c;
			oppPaymentDueDate = isNovatedReceipt ? dateUtility.toDateString('dd MMM yyyy', paymentReceiptLineItem.PaymentReceipt__r.NovationDate__c) : dateUtility.toDateString('dd MMM yyyy', paymentReceiptLineItem.OpportunityPayment__r.DueDate__c);
			oppPaymentRemainingAmount = numberUtility.setDecToFormatCommaTwoDigits(paymentReceiptLineItem.RemainingAmount__c);
			status = isNovatedReceipt? GlobalConstants.OPP_PAYMENT_STATUS_FULLYPAID : paymentReceiptLineItem.Status__c;
			oppPaymentReceiptAmount = numberUtility.setDecToFormatCommaTwoDigits(paymentReceiptLineItem.ReceivedAmount__c);

		}
	}
	public class PaymentMethodWrapper{
		public List<PaymentMethodItemWrapper> paymentMethodList {get; set;}

		public PaymentMethodWrapper(PaymentMethod__c paymentMethod){
			if(paymentMethodList == null){
				paymentMethodList = new List<PaymentMethodItemWrapper>{
					new PaymentMethodItemWrapper(paymentMethod)
				};
			}
		}

		public void addPaymentMethodList(PaymentMethod__c paymentMethod){
			paymentMethodList.add(new PaymentMethodItemWrapper(paymentMethod));
		}
	}

	public class PaymentMethodItemWrapper{
		public String paymentType{get; set;}
		public String creditCardNo{get; set;}
		public String bankName{get; set;}
		public String debitCardNo{get; set;}
		public String chequeNo{get; set;}
		public String intelBankName{get; set;}
		public String bankBranch{get; set;}
		public String paymentDate{get; set;}
		public String bankAccountNo{get; set;}
		public String bankDraftNo{get; set;}
		public String receiedAmount{get; set;}

		public PaymentMethodItemWrapper(PaymentMethod__c paymentMethod){
			DateUtility dateUtility = DateUtility.getInstance();
			NumberUtility numberUtility = NumberUtility.getInstance();
			receiedAmount = numberUtility.setDecToFormatCommaTwoDigits(paymentMethod.ReceivedAmount__c);
			paymentType = paymentMethod.PaymentType__c;
			creditCardNo =  String.valueOf(paymentMethod.CreditCardNo__c);
			bankName = paymentMethod.PaymentReceipt__r.ReceiptType__c == GlobalConstants.RECEIPT_TYPE_PAYMENTGATEWAY ? 'Payment Gateway' : paymentMethod.BankName__c;
			intelBankName = paymentMethod.InternationalBankName__c;
			debitCardNo = String.valueOf(paymentMethod.DebitCardNo__c);
			chequeNo = String.valueOf(paymentMethod.ChequeNo__c);
			bankBranch = paymentMethod.BankBranch__c;
			bankAccountNo = paymentMethod.BankAccountNo__c;
			paymentDate = dateUtility.toDateString('dd MMM yyyy',paymentMethod.PaymentDate__c);
			bankDraftNo = String.valueOf(paymentMethod.BankDraftNo__c);
		}
	}

	/**
	 * Phase2
	 * Details:
	 * - Modify wrapper to receive PaymentReceipt__c.CoBuyerName__c
	 */
	public class PaymentReceiptHeaderWrapper{

		public String coBuyerName {get; set;}
		public String receiptNo {get; set;}
		public String accountAddress {get; set;}
		public String dateReceipt {get; set;}
		public String totalReceiveAmount{get; set;}
		public String imageUrl {get; set;}
		public Boolean isCancelled {get; set;}

		public PaymentReceiptHeaderWrapper(String receiptNo, String accountAddress, Decimal totalReceiveAmount,String imageUrl , Boolean isCancelled , String coBuyerName){
			DateUtility dateUtility = DateUtility.getInstance();
			NumberUtility numberUtility = NumberUtility.getInstance();
			this.coBuyerName = coBuyerName;
			this.receiptNo = receiptNo;
			this.accountAddress = accountAddress;
			this.dateReceipt = dateUtility.toDateString('dd MMM yyyy', System.today());
			this.totalReceiveAmount = numberUtility.setDecToFormatCommaTwoDigits(totalReceiveAmount);
			this.imageUrl = imageUrl;
			this.isCancelled = isCancelled;
		}
	}
}