force-app/main/default/objects/Account/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancelReasonforCRM__c.field-meta.xml
<CustomField>
    <fullName>CancelReasonforCRM__c</fullName>
    <label>Cancel Reason for CRM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <label>Response Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>ResponseMessage__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <description>Developer name</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateReceiptApiCalloutBatchTest.cls
@isTest
public with sharing class CreateReceiptApiCalloutBatchTest {
    public static String targetSuccessReceiptId;
    public static String targetSuccessReceiptLienItemId;
    public static String targetSuccessPaymentMethodId;

	public class SuccessReceiptMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateReceiptApiCallout.RequestDataModel>.class);
            List<CreateReceiptApiCallout.RequestDataModel> requestData = ( List<CreateReceiptApiCallout.RequestDataModel>)requestDataObj;

            List<CreateReceiptApiCallout.ReceiptLineItemResponse> responseReceiptLineItemData = new List<CreateReceiptApiCallout.ReceiptLineItemResponse>();
			CreateReceiptApiCallout.ReceiptLineItemResponse responseReceiptLineItem = new CreateReceiptApiCallout.ReceiptLineItemResponse();
            responseReceiptLineItem.Message = 'Success';
            responseReceiptLineItem.ResponseCode = 'SC';
            responseReceiptLineItem.SFDocLineId = targetSuccessReceiptLienItemId;
            responseReceiptLineItem.Timestamp = System.now();
            responseReceiptLineItemData.add(responseReceiptLineItem);

            List<CreateReceiptApiCallout.PaymentMethodResponse> responsePaymentMethodData = new List<CreateReceiptApiCallout.PaymentMethodResponse>();
			CreateReceiptApiCallout.PaymentMethodResponse responsePaymentMethod = new CreateReceiptApiCallout.PaymentMethodResponse();
            responsePaymentMethod.Message = 'Success';
            responsePaymentMethod.ResponseCode = 'SC';
            responsePaymentMethod.ResponseId = 123456;
            responsePaymentMethod.SFPaymentMethodId = targetSuccessPaymentMethodId;
            responsePaymentMethod.Timestamp = System.now();
            responsePaymentMethodData.add(responsePaymentMethod);

            // START MOCK RECEIPT RESPONSE
            List<CreateReceiptApiCallout.ReceiptResponse> responseReceiptData = new List<CreateReceiptApiCallout.ReceiptResponse>();
			CreateReceiptApiCallout.ReceiptResponse receiptResponse = new CreateReceiptApiCallout.ReceiptResponse();
            receiptResponse.SFDocId = targetSuccessReceiptId;
            receiptResponse.ResponseId = 123456;
            receiptResponse.ResponseCode = 'SC';
            receiptResponse.Message = 'Success';
            receiptResponse.Timestamp = System.now();
			receiptResponse.DocLine = responseReceiptLineItemData;
            receiptResponse.PaymentMethod = responsePaymentMethodData;
            responseReceiptData.add(receiptResponse);
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseReceiptData));
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void createReceiptApiSuccess(){
        Test.setMock(HttpCalloutMock.class, new CreateReceiptApiCalloutBatchTest.SuccessReceiptMockResp());
        DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		testProject.CompanyName__c ='Test Company Name';
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(testProduct.Id, 15000000, 20000000,10000000);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Thai',
			null,
			testProject.Id
		);
		insert opportunity;
		// Create Opp Payments
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPayment,
			contractOppPayment,
			installmentOppPayment,
			transferOppPayment
		};
		insert oppPayments;
		// Create Invoice
		Invoice__c invoice = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 10, 6), Date.newInstance(2024, 10, 1), true, 'Address');
		List<Invoice__c> invoices = new List<Invoice__c>{ invoice };
		insert invoices;
		// Create Invoice Line Item
		InvoiceLineItem__c invoiceLineItem1 = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPayment.Id,50000,Date.newInstance(2024, 12, 1),'');
		List<InvoiceLineItem__c> invoiceLineItems = new List<InvoiceLineItem__c>{ invoiceLineItem1 };
		insert invoiceLineItems;
		// Create Receipt
		PaymentReceipt__c receipt = dataMaker.craeteReceipt(opportunity.Id , Date.newInstance(2024, 10, 10));
		List<PaymentReceipt__c> receipts = new List<PaymentReceipt__c>{receipt};
		insert receipts;
        targetSuccessReceiptId = receipt.Id;
		System.debug('Payment Receipt: '+receipt);
		// Create Receipt Line Item
		PaymentReceiptLineItem__c receiptItemReservation = dataMaker.createReceiptLineItem(receipt.Id,reservationOppPayment.Id,invoiceLineItem1.Id,50000,'Fully Paid');
		PaymentReceiptLineItem__c receiptItemContract = dataMaker.createReceiptLineItem(receipt.Id,contractOppPayment.Id,null,50000,'Partially Paid');
		List<PaymentReceiptLineItem__c> receiptItems = new List<PaymentReceiptLineItem__c>{receiptItemReservation,receiptItemContract};
		insert receiptItems;
        targetSuccessReceiptLienItemId = receiptItemReservation.Id;
		PaymentMethod__c receiptMethod = dataMaker.createPaymentMethod(receipt.Id,'KBANK',Decimal.valueOf(1000000),'Cash','Reservation',Date.today());
		List<PaymentMethod__c> receiptMethods = new List<PaymentMethod__c>{receiptMethod};
		insert receiptMethods;
        targetSuccessPaymentMethodId = receiptMethod.Id;
        Test.startTest();
        CreateReceiptApiCalloutBatch batch = new CreateReceiptApiCalloutBatch();
        Database.executeBatch(batch, 200);
		Test.stopTest();
        PaymentReceipt__c targetPaymentReceipt = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceipt__c WHERE Id =: receipt.Id LIMIT 1];
        PaymentReceiptLineItem__c targetPaymentReceiptLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceiptLineItem__c WHERE Id =: receiptItemReservation.Id LIMIT 1];
		PaymentMethod__c targetPaymentMethod = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentMethod__c WHERE Id =: receiptMethod.Id LIMIT 1];
		System.assertEquals('Success', targetPaymentReceipt.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceipt.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentReceiptLineItem.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceiptLineItem.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentMethod.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentMethod.ResponseCode__c);
       
    }
	public class SuccessReceiptCancelMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateReceiptApiCallout.RequestDataModel>.class);
            List<CreateReceiptApiCallout.RequestDataModel> requestData = ( List<CreateReceiptApiCallout.RequestDataModel>)requestDataObj;

            List<CreateReceiptApiCallout.ReceiptLineItemResponse> responseReceiptLineItemData = new List<CreateReceiptApiCallout.ReceiptLineItemResponse>();
			CreateReceiptApiCallout.ReceiptLineItemResponse responseReceiptLineItem = new CreateReceiptApiCallout.ReceiptLineItemResponse();
            responseReceiptLineItem.Message = 'Success';
            responseReceiptLineItem.ResponseCode = 'SC';
            responseReceiptLineItem.SFDocLineId = targetSuccessReceiptLienItemId;
            responseReceiptLineItem.Timestamp = System.now();
            responseReceiptLineItemData.add(responseReceiptLineItem);

            List<CreateReceiptApiCallout.PaymentMethodResponse> responsePaymentMethodData = new List<CreateReceiptApiCallout.PaymentMethodResponse>();
			CreateReceiptApiCallout.PaymentMethodResponse responsePaymentMethod = new CreateReceiptApiCallout.PaymentMethodResponse();
            responsePaymentMethod.Message = 'Success';
            responsePaymentMethod.ResponseCode = 'SC';
            responsePaymentMethod.ResponseId = 123456;
            responsePaymentMethod.SFPaymentMethodId = targetSuccessPaymentMethodId;
            responsePaymentMethod.Timestamp = System.now();
            responsePaymentMethodData.add(responsePaymentMethod);

            // START MOCK RECEIPT RESPONSE
            List<CreateReceiptApiCallout.ReceiptResponse> responseReceiptData = new List<CreateReceiptApiCallout.ReceiptResponse>();
			CreateReceiptApiCallout.ReceiptResponse receiptResponse = new CreateReceiptApiCallout.ReceiptResponse();
            receiptResponse.SFDocId = targetSuccessReceiptId;
            receiptResponse.ResponseId = 123456;
            receiptResponse.ResponseCode = 'SC';
            receiptResponse.Message = 'Success';
            receiptResponse.Timestamp = System.now();
			receiptResponse.DocLine = responseReceiptLineItemData;
            receiptResponse.PaymentMethod = responsePaymentMethodData;
            responseReceiptData.add(receiptResponse);
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseReceiptData));
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void createReceiptApiSuccessAndIsCancel(){
        Test.setMock(HttpCalloutMock.class, new CreateReceiptApiCalloutBatchTest.SuccessReceiptCancelMockResp());
        DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		testProject.CompanyName__c ='Test Company Name';
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(testProduct.Id, 15000000, 20000000,10000000);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Thai',
			null,
			testProject.Id
		);
		insert opportunity;
		// Create Opp Payments
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPayment,
			contractOppPayment,
			installmentOppPayment,
			transferOppPayment
		};
		insert oppPayments;
		// Create Invoice
		Invoice__c invoice = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 10, 6), Date.newInstance(2024, 10, 1), true, 'Address');
		List<Invoice__c> invoices = new List<Invoice__c>{ invoice };
		insert invoices;
		// Create Invoice Line Item
		InvoiceLineItem__c invoiceLineItem1 = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPayment.Id,50000,Date.newInstance(2024, 12, 1),'');
		List<InvoiceLineItem__c> invoiceLineItems = new List<InvoiceLineItem__c>{ invoiceLineItem1 };
		insert invoiceLineItems;
		// Create Receipt
		PaymentReceipt__c receipt = dataMaker.craeteReceipt(opportunity.Id , Date.newInstance(2024, 10, 10));
		receipt.CancelReason__c ='Cancel by CRM';
		receipt.CancelReasonforCRM__c ='Test';
		List<PaymentReceipt__c> receipts = new List<PaymentReceipt__c>{receipt};
		insert receipts;
        targetSuccessReceiptId = receipt.Id;
		System.debug('Payment Receipt: '+receipt);
		// Create Receipt Line Item
		PaymentReceiptLineItem__c receiptItemReservation = dataMaker.createReceiptLineItem(receipt.Id,reservationOppPayment.Id,invoiceLineItem1.Id,50000,'Fully Paid');
		PaymentReceiptLineItem__c receiptItemContract = dataMaker.createReceiptLineItem(receipt.Id,contractOppPayment.Id,null,50000,'Partially Paid');
		List<PaymentReceiptLineItem__c> receiptItems = new List<PaymentReceiptLineItem__c>{receiptItemReservation,receiptItemContract};
		insert receiptItems;
        targetSuccessReceiptLienItemId = receiptItemReservation.Id;
		PaymentMethod__c receiptMethod = dataMaker.createPaymentMethod(receipt.Id,'KBANK',Decimal.valueOf(1000000),'Cash','Reservation',Date.today());
		List<PaymentMethod__c> receiptMethods = new List<PaymentMethod__c>{receiptMethod};
		insert receiptMethods;
        targetSuccessPaymentMethodId = receiptMethod.Id;
        Test.startTest();
        CreateReceiptApiCalloutBatch batch = new CreateReceiptApiCalloutBatch();
        Database.executeBatch(batch, 200);
		Test.stopTest();
        PaymentReceipt__c targetPaymentReceipt = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceipt__c WHERE Id =: receipt.Id LIMIT 1];
        PaymentReceiptLineItem__c targetPaymentReceiptLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceiptLineItem__c WHERE Id =: receiptItemReservation.Id LIMIT 1];
		PaymentMethod__c targetPaymentMethod = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentMethod__c WHERE Id =: receiptMethod.Id LIMIT 1];
		System.assertEquals('Success', targetPaymentReceipt.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceipt.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentReceiptLineItem.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceiptLineItem.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentMethod.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentMethod.ResponseCode__c);
       
    }
	public class SuccessReceiptCancelStatusInPojjamanFailMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateReceiptApiCallout.RequestDataModel>.class);
            List<CreateReceiptApiCallout.RequestDataModel> requestData = ( List<CreateReceiptApiCallout.RequestDataModel>)requestDataObj;

            List<CreateReceiptApiCallout.ReceiptLineItemResponse> responseReceiptLineItemData = new List<CreateReceiptApiCallout.ReceiptLineItemResponse>();
			CreateReceiptApiCallout.ReceiptLineItemResponse responseReceiptLineItem = new CreateReceiptApiCallout.ReceiptLineItemResponse();
            responseReceiptLineItem.Message = 'Success';
            responseReceiptLineItem.ResponseCode = 'SC';
            responseReceiptLineItem.SFDocLineId = targetSuccessReceiptLienItemId;
            responseReceiptLineItem.Timestamp = System.now();
            responseReceiptLineItemData.add(responseReceiptLineItem);

            List<CreateReceiptApiCallout.PaymentMethodResponse> responsePaymentMethodData = new List<CreateReceiptApiCallout.PaymentMethodResponse>();
			CreateReceiptApiCallout.PaymentMethodResponse responsePaymentMethod = new CreateReceiptApiCallout.PaymentMethodResponse();
            responsePaymentMethod.Message = 'Success';
            responsePaymentMethod.ResponseCode = 'SC';
            responsePaymentMethod.ResponseId = 123456;
            responsePaymentMethod.SFPaymentMethodId = targetSuccessPaymentMethodId;
            responsePaymentMethod.Timestamp = System.now();
            responsePaymentMethodData.add(responsePaymentMethod);

            // START MOCK RECEIPT RESPONSE
            List<CreateReceiptApiCallout.ReceiptResponse> responseReceiptData = new List<CreateReceiptApiCallout.ReceiptResponse>();
			CreateReceiptApiCallout.ReceiptResponse receiptResponse = new CreateReceiptApiCallout.ReceiptResponse();
            receiptResponse.SFDocId = targetSuccessReceiptId;
            receiptResponse.ResponseId = 123456;
            receiptResponse.ResponseCode = 'SC';
            receiptResponse.Message = 'Success';
            receiptResponse.Timestamp = System.now();
			receiptResponse.DocLine = responseReceiptLineItemData;
            receiptResponse.PaymentMethod = responsePaymentMethodData;
            responseReceiptData.add(receiptResponse);
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseReceiptData));
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void createReceiptApiSuccessAndIsCancelCloseLost(){
        Test.setMock(HttpCalloutMock.class, new CreateReceiptApiCalloutBatchTest.SuccessReceiptCancelStatusInPojjamanFailMockResp());
        DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		testProject.CompanyName__c ='Test Company Name';
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(testProduct.Id, 15000000, 20000000,10000000);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Thai',
			null,
			testProject.Id
		);
		insert opportunity;
		// Create Opp Payments
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPayment,
			contractOppPayment,
			installmentOppPayment,
			transferOppPayment
		};
		insert oppPayments;
		// Create Invoice
		Invoice__c invoice = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 10, 6), Date.newInstance(2024, 10, 1), true, 'Address');
		List<Invoice__c> invoices = new List<Invoice__c>{ invoice };
		insert invoices;
		// Create Invoice Line Item
		InvoiceLineItem__c invoiceLineItem1 = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPayment.Id,50000,Date.newInstance(2024, 12, 1),'');
		List<InvoiceLineItem__c> invoiceLineItems = new List<InvoiceLineItem__c>{ invoiceLineItem1 };
		insert invoiceLineItems;
		// Create Receipt
		PaymentReceipt__c receipt = dataMaker.craeteReceipt(opportunity.Id , Date.newInstance(2024, 10, 10));
		receipt.CancelReason__c ='Cancel by CRM';
		receipt.CancelReasonforCRM__c ='Test';
		receipt.LastCancelledStatusInPojjaman__c = 'Test';
		receipt.LastCreatedStatusInPojjaman__c = 'Test';
		List<PaymentReceipt__c> receipts = new List<PaymentReceipt__c>{receipt};
		insert receipts;
        targetSuccessReceiptId = receipt.Id;
		System.debug('Payment Receipt: '+receipt);
		// Create Receipt Line Item
		PaymentReceiptLineItem__c receiptItemReservation = dataMaker.createReceiptLineItem(receipt.Id,reservationOppPayment.Id,invoiceLineItem1.Id,50000,'Fully Paid');
		PaymentReceiptLineItem__c receiptItemContract = dataMaker.createReceiptLineItem(receipt.Id,contractOppPayment.Id,null,50000,'Partially Paid');
		List<PaymentReceiptLineItem__c> receiptItems = new List<PaymentReceiptLineItem__c>{receiptItemReservation,receiptItemContract};
		insert receiptItems;
        targetSuccessReceiptLienItemId = receiptItemReservation.Id;
		PaymentMethod__c receiptMethod = dataMaker.createPaymentMethod(receipt.Id,'KBANK',Decimal.valueOf(1000000),'Cash','Reservation',Date.today());
		List<PaymentMethod__c> receiptMethods = new List<PaymentMethod__c>{receiptMethod};
		insert receiptMethods;
        targetSuccessPaymentMethodId = receiptMethod.Id;
        Test.startTest();
        CreateReceiptApiCalloutBatch batch = new CreateReceiptApiCalloutBatch();
        Database.executeBatch(batch, 200);
		Test.stopTest();
        PaymentReceipt__c targetPaymentReceipt = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceipt__c WHERE Id =: receipt.Id LIMIT 1];
        PaymentReceiptLineItem__c targetPaymentReceiptLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceiptLineItem__c WHERE Id =: receiptItemReservation.Id LIMIT 1];
		PaymentMethod__c targetPaymentMethod = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentMethod__c WHERE Id =: receiptMethod.Id LIMIT 1];
		System.assertEquals('Success', targetPaymentReceipt.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceipt.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentReceiptLineItem.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentReceiptLineItem.ResponseCode__c);
       
        System.assertEquals('Success', targetPaymentMethod.ResponseMessage__c);
		System.assertEquals('SC', targetPaymentMethod.ResponseCode__c);
       
    }
    ////////////////////////////////////////////////////////////////
    public class FailReceiptMockResp implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            Object requestDataObj = JSON.deserialize(req.getBody(), List<CreateReceiptApiCallout.RequestDataModel>.class);
            List<CreateReceiptApiCallout.RequestDataModel> requestData = ( List<CreateReceiptApiCallout.RequestDataModel>)requestDataObj;

            // START MOCK RECEIPT RESPONSE
            List<CreateReceiptApiCallout.ReceiptResponse> responseReceiptData = new List<CreateReceiptApiCallout.ReceiptResponse>();
			
			// END MOCK RESPONSE
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(json.serialize(responseReceiptData));
            res.setStatusCode(500);
            return res;
        }
    }
    @isTest
    static void createReceiptApiFail(){
        Test.setMock(HttpCalloutMock.class, new CreateReceiptApiCalloutBatchTest.FailReceiptMockResp());
        DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		testProject.CompanyName__c ='Test Company Name';
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 testProduct = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert testProduct;
		// Create Pricebook Entry
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry testPricebookEntry1 = dataMaker.createPricebookEntries(testProduct.Id, 15000000, 20000000,10000000);
		testPricebookEntry1.Pricebook2Id = pricebookId;
		testPricebookEntry1.UseStandardPrice = false;
		insert testPricebookEntry1;
		// Creat Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'Test Account');
		insert account;
		// Create Opportunity
		Opportunity opportunity = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.today(),
			'Open',
			testProduct.Id,
			'Thai',
			null,
			testProject.Id
		);
		insert opportunity;
		// Create Opp Payments
		OpportunityPayment__c reservationOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPayment = dataMaker.createOpportunityPayment(
			opportunity.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPayment,
			contractOppPayment,
			installmentOppPayment,
			transferOppPayment
		};
		insert oppPayments;
		// Create Invoice
		Invoice__c invoice = dataMaker.createInvoice(opportunity.Id, Date.newInstance(2024, 10, 6), Date.newInstance(2024, 10, 1), true, 'Address');
		List<Invoice__c> invoices = new List<Invoice__c>{ invoice };
		insert invoices;
		// Create Invoice Line Item
		InvoiceLineItem__c invoiceLineItem1 = dataMaker.createInvoiceLineItem(invoice.Id,reservationOppPayment.Id,50000,Date.newInstance(2024, 12, 1),'');
		List<InvoiceLineItem__c> invoiceLineItems = new List<InvoiceLineItem__c>{ invoiceLineItem1 };
		insert invoiceLineItems;
		// Create Receipt
		PaymentReceipt__c receipt = dataMaker.craeteReceipt(opportunity.Id , Date.newInstance(2024, 10, 10));
		List<PaymentReceipt__c> receipts = new List<PaymentReceipt__c>{receipt};
		insert receipts;
        targetSuccessReceiptId = receipt.Id;
		System.debug('Payment Receipt: '+receipt);
		// Create Receipt Line Item
		PaymentReceiptLineItem__c receiptItemReservation = dataMaker.createReceiptLineItem(receipt.Id,reservationOppPayment.Id,invoiceLineItem1.Id,50000,'Fully Paid');
		PaymentReceiptLineItem__c receiptItemContract = dataMaker.createReceiptLineItem(receipt.Id,contractOppPayment.Id,null,50000,'Partially Paid');
		List<PaymentReceiptLineItem__c> receiptItems = new List<PaymentReceiptLineItem__c>{receiptItemReservation,receiptItemContract};
		insert receiptItems;
        targetSuccessReceiptLienItemId = receiptItemReservation.Id;
		PaymentMethod__c receiptMethod = dataMaker.createPaymentMethod(receipt.Id,'KBANK',Decimal.valueOf(1000000),'Cash','Reservation',Date.today());
		List<PaymentMethod__c> receiptMethods = new List<PaymentMethod__c>{receiptMethod};
		insert receiptMethods;
        targetSuccessPaymentMethodId = receiptMethod.Id;
        Test.startTest();
        CreateReceiptApiCalloutBatch batch = new CreateReceiptApiCalloutBatch();
        Database.executeBatch(batch, 200);
		Test.stopTest();
        PaymentReceipt__c targetPaymentReceipt = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceipt__c WHERE Id =: receipt.Id LIMIT 1];
        PaymentReceiptLineItem__c targetPaymentReceiptLineItem = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentReceiptLineItem__c WHERE Id =: receiptItemReservation.Id LIMIT 1];
		PaymentMethod__c targetPaymentMethod = [SELECT Id,ResponseMessage__c,ResponseCode__c FROM PaymentMethod__c WHERE Id =: receiptMethod.Id LIMIT 1];
        System.assertEquals('ERR', targetPaymentReceipt.ResponseCode__c);
        System.assertEquals('ERR', targetPaymentReceiptLineItem.ResponseCode__c);
        System.assertEquals('ERR', targetPaymentMethod.ResponseCode__c);
        
        
    }

}