force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <formula>if( ISBLANK(Text(CancelReason__c)),false,True)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TriggerActivation__mdt/TriggerActivation__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to configure to acitvatate/deactivate trigger execution</description>
    <label>Trigger Activation</label>
    <pluralLabel>Trigger Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean to check to activate/deactivate Trigger</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptTriggerHandler.cls
public with sharing class PaymentReceiptTriggerHandler {
	public static PaymentReceiptTriggerHandler instance;
	public static PaymentReceiptTriggerHandler getInstance() {
		if (instance == null) {
			instance = new PaymentReceiptTriggerHandler();
		}
		return instance;
	}

	public Boolean isActive = true;
	public List<PaymentReceipt__c> newRecords;
	public Map<Id, PaymentReceipt__c> oldMap;

	public Boolean isTriggerActivated() {
		if (TriggerActivation__mdt.getInstance('PaymentReceiptTrigger') != null) {
			return this.isActive && TriggerActivation__mdt.getInstance('PaymentReceiptTrigger').isActive__c;
		}
		return this.isActive;
	}
	public void setParams(List<PaymentReceipt__c> newRecords, Map<Id, PaymentReceipt__c> oldMap) {
		this.newRecords = newRecords;
		this.oldMap = oldMap;
	}
	public void setBypass() {
		this.isActive = false;
	}

	public void clearBypass() {
		this.isActive = true;
	}

	public void executeBeforeUpdate() {
		this.validateIsLastReceiptBeforeCancel();
		this.validateInvoiceBeforeCancel();
	}

	public void executeAfterUpdate() {
		this.cancelReceivedAmountInOpportunityPayment();
	}

	private void validateIsLastReceiptBeforeCancel(){
		PaymentReceiptSelector paymentReceiptSelector = PaymentReceiptSelector.getInstance();
		PaymentReceipt__c targetPaymentReceipt;
		Id targetOppId;
		for (PaymentReceipt__c paymentReceipt : this.newRecords) {
			PaymentReceipt__c oldPaymentReceipt = this.oldMap.get(paymentReceipt.Id);
			if (
				oldPaymentReceipt.IsCancel__c != paymentReceipt.IsCancel__c &&
				paymentReceipt.IsCancel__c == true &&
				paymentReceipt.CancelReason__c != 'Closed Lost'
			) {
				targetOppId = paymentReceipt.Opportunity__c;
				targetPaymentReceipt = paymentReceipt;
			}
		}
		if (targetPaymentReceipt != null){
			Map<Id, PaymentReceipt__c> orderedPaymentReceiptMapById = PaymentReceiptSelector.getOrderedPaymentReceiptByOppIdMapById(targetOppId);
			List<PaymentReceipt__c> orderedPaymentReceipts = orderedPaymentReceiptMapById.values();
			for (PaymentReceipt__c receipt : orderedPaymentReceipts){
				System.debug('**test** receipt: ' + receipt.Id);
			}
			PaymentReceipt__c lastReceipt = orderedPaymentReceipts[0];
			System.debug('**test** targetPaymentReceipt: ' + targetPaymentReceipt);
			System.debug('**test** lastReceipt: ' + lastReceipt);
			if (targetPaymentReceipt.Id != lastReceipt.Id){
				targetPaymentReceipt.addError('Unable to cancel receipt which is not latest receipt');
			}
		}

	}

	private void validateInvoiceBeforeCancel() {
		PaymentReceiptSelector paymentReceiptSelector = PaymentReceiptSelector.getInstance();
		InvoiceSelector invoiceSelector = InvoiceSelector.getInstance();
		Set<Id> paymentReceiptIds = new Set<Id>();
		Id targetOppId;
		for (PaymentReceipt__c paymentReceipt : this.newRecords) {
			PaymentReceipt__c oldPaymentReceipt = this.oldMap.get(paymentReceipt.Id);
			if (
				oldPaymentReceipt.IsCancel__c != paymentReceipt.IsCancel__c &&
				paymentReceipt.IsCancel__c == true &&
				paymentReceipt.CancelReason__c != 'Closed Lost'
			) {
				paymentReceiptIds.add(paymentReceipt.Id);
				targetOppId = paymentReceipt.Opportunity__c;
			}
		}
		if (!paymentReceiptIds.isEmpty()) {
			// Datetime now = System.now();
			Map<Id, PaymentReceipt__c> paymentReceiptMapWithId = paymentReceiptSelector.getPaymentReceiptWithLineItemMapById(
				paymentReceiptIds
			);
			Map<String, Invoice__c> invoiceMapByTerm = invoiceSelector.getInvoiceMapByTerm(targetOppId);
			for (PaymentReceipt__c paymentReceipt : this.newRecords) {
				PaymentReceipt__c targetPaymentReceipt = paymentReceiptMapWithId.get(paymentReceipt.Id);
				List<PaymentReceiptLineItem__c> paymentReceiptLineItems = targetPaymentReceipt.Payment_Transactions__r ==
					null
					? new List<PaymentReceiptLineItem__c>()
					: targetPaymentReceipt.Payment_Transactions__r;
				for (PaymentReceiptLineItem__c paymentReceiptLineItem : paymentReceiptLineItems) {
					Datetime paymentCreatedDate = paymentReceiptLineItem.CreatedDate;
					Invoice__c targetInvoice = invoiceMapByTerm.get(
						paymentReceiptLineItem.OpportunityPayment__r.Term__c
					);
					if (targetInvoice != null && targetInvoice.CreatedDate > paymentCreatedDate) {
						paymentReceipt.addError('Unable to cancel receipt after invoice is created');
					}
				}
			}
		}
	}

	private void cancelReceivedAmountInOpportunityPayment() {
		OpportunityPaymentService service = OpportunityPaymentService.getInstance();
		PaymentReceiptSelector paymentReceiptSelector = PaymentReceiptSelector.getInstance();
		List<PaymentReceipt__c> filteredPaymentReceipt = new List<PaymentReceipt__c>();
		Set<Id> paymentReceiptIds = new Set<Id>();
		for (PaymentReceipt__c paymentReceipt : this.newRecords) {
			PaymentReceipt__c oldPaymentReceipt = this.oldMap.get(paymentReceipt.Id);
			if (oldPaymentReceipt.IsCancel__c != paymentReceipt.IsCancel__c && paymentReceipt.IsCancel__c == true && paymentReceipt.CancelReason__c != 'Closed Lost') {
				filteredPaymentReceipt.add(paymentReceipt);
				paymentReceiptIds.add(paymentReceipt.Id);
			}
		}
		if (!filteredPaymentReceipt.isEmpty()) {
			Map<Id, PaymentReceipt__c> paymentReceiptWithLineItemsMapById = paymentReceiptSelector.getPaymentReceiptWithLineItemMapById(
				paymentReceiptIds
			);
			List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>();
			for (Id paymentReceiptId : paymentReceiptWithLineItemsMapById.keySet()) {
				List<PaymentReceiptLineItem__c> paymentReceiptLineItems = paymentReceiptWithLineItemsMapById.get(
							paymentReceiptId
						)
						.Payment_Transactions__r == null
					? new List<PaymentReceiptLineItem__c>()
					: paymentReceiptWithLineItemsMapById.get(paymentReceiptId).Payment_Transactions__r;
				if (!paymentReceiptLineItems.isEmpty()) {
					oppPayments.addAll(service.cancelRecievedAmountFromReceiptLineItem(paymentReceiptLineItems));
				}
			}
			if (!oppPayments.isEmpty()) {
				update oppPayments;
			}
		}
	}
}