force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>OpportunityPayment__r.Term__c</formula>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Quota__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Quota__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/IsMasterData__c.field-meta.xml
<CustomField>
    <fullName>IsMasterData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>เพื่อบอกว่า Record นี้ เป็นค่าตั้งต้นใน Opportunity Payment</description>
    <label>Is Master Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <formula>PaymentMethod__r.PaymentDate__c</formula>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/RemainingAmount__c.field-meta.xml
<CustomField>
    <fullName>RemainingAmount__c</fullName>
    <label>RemainingAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/TransactionDateTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTime__c</fullName>
    <description>เวลาและวันที่ที่ชำระเงิน</description>
    <label>Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <inlineHelpText>Date for collecting payments (installment)</inlineHelpText>
    <label>Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
    TODAY() &gt;=  ActiveFrom__c &amp;&amp; TODAY() &lt;=  ActiveTo__c , 
    &quot;Active&quot;, 
    &quot;Inactive&quot;
)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityPaymentSelector.cls
public with sharing class OpportunityPaymentSelector {
	public static OpportunityPaymentSelector instance;
	public OpportunityPaymentSelector() {
	}

	public static OpportunityPaymentSelector getInstance() {
		if (instance == null) {
			instance = new OpportunityPaymentSelector();
		}
		return instance;
	}

	public Map<Id, OpportunityPayment__c> getOpportunityPaymentMapById(Set<Id> oppPaymentIds) {
		return new Map<Id, OpportunityPayment__c>(
			[
				SELECT
					Opportunity__c,
					Amount__c,
					DueDate__c,
					Order__c,
					ReceivedAmount__c,
					ReceivedDate__c,
					Term__c,
					Opportunity__r.PaymentTermMaster__c,
					Remaining__c,
					PaymentStatus__c
				FROM OpportunityPayment__c
				WHERE Id IN :oppPaymentIds
				ORDER BY Order__c
			]
		);
	}

	public Map<Id, OpportunityPayment__c> getOpportunityPaymentWithInvoiceLineItemMapById(Set<Id> oppPaymentIds) {
		return new Map<Id, OpportunityPayment__c>(
			[
				SELECT
					Opportunity__c,
					Amount__c,
					DueDate__c,
					Order__c,
					ReceivedAmount__c,
					ReceivedDate__c,
					Term__c,
					Opportunity__r.PaymentTermMaster__c,
					Remaining__c,
					PaymentStatus__c,
					(
						SELECT Id, Invoice__c, Status__c, PaymentReceiptLineItem__c
						FROM InvoiceLineItems__r
						ORDER BY CreatedDate DESC
					)
				FROM OpportunityPayment__c
				WHERE Id IN :oppPaymentIds
				ORDER BY Order__c
			]
		);
	}

	public Map<Id, OpportunityPayment__c> getOpportunityPaymentWithReceiptLineItemMapById(set<Id> oppPaymentIds) {
		return new Map<Id, OpportunityPayment__c>(
			[
				SELECT
					Opportunity__c,
					Amount__c,
					DueDate__c,
					Order__c,
					ReceivedAmount__c,
					ReceivedDate__c,
					Term__c,
					Opportunity__r.PaymentTermMaster__c,
					Remaining__c,
					PaymentStatus__c,
					(
						SELECT
							Id,
							InvoiceLineItem__c,
							InvoiceLineItem__r.Invoice__c,
							ReceivedAmount__c,
							RemainingAmount__c,
							Status__c,
							TransactionDateTime__c
						FROM Payment_Receipt_Line_Item__r
					)
				FROM OpportunityPayment__c
				WHERE Id IN :oppPaymentIds
				ORDER BY Order__c
			]
		);
	}

	public Map<Id, List<OpportunityPayment__c>> getOpportunityPaymentsMapByOppId(Set<Id> oppIds) {
		Map<Id, List<OpportunityPayment__c>> opportunityPaymentsMapByOppId = new Map<Id, List<OpportunityPayment__c>>();
		List<OpportunityPayment__c> opportunityPayments = [
			SELECT
				Id,
				Opportunity__c,
				Amount__c,
				DueDate__c,
				Order__c,
				ReceivedAmount__c,
				ReceivedDate__c,
				Term__c,
				Opportunity__r.PaymentTermMaster__c,
				Remaining__c,
				PaymentStatus__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c IN :oppIds AND IsMasterData__c = true
			ORDER BY Order__c
		];
		for (OpportunityPayment__c opportunityPayment : opportunityPayments) {
			if (!opportunityPaymentsMapByOppId.containsKey(opportunityPayment.Opportunity__c)) {
				opportunityPaymentsMapByOppId.put(opportunityPayment.Opportunity__c, new List<OpportunityPayment__c>());
			}
			opportunityPaymentsMapByOppId.get(opportunityPayment.Opportunity__c).add(opportunityPayment);
		}
		return opportunityPaymentsMapByOppId;
	}

	public Map<Id, List<OpportunityPayment__c>> getOpportunityPaymentsWithInvoiceLineItemMapByOppId(Set<Id> oppIds) {
		Map<Id, List<OpportunityPayment__c>> opportunityPaymentsMapByOppId = new Map<Id, List<OpportunityPayment__c>>();
		List<OpportunityPayment__c> opportunityPayments = [
			SELECT
				Id,
				Opportunity__c,
				Amount__c,
				DueDate__c,
				Order__c,
				ReceivedAmount__c,
				ReceivedDate__c,
				Term__c,
				Opportunity__r.PaymentTermMaster__c,
				Remaining__c,
				PaymentStatus__c,
				(SELECT Id, Invoice__c, Status__c, PaymentReceiptLineItem__c FROM InvoiceLineItems__r)
			FROM OpportunityPayment__c
			WHERE Opportunity__c IN :oppIds AND IsMasterData__c = true
			ORDER BY Order__c
		];
		for (OpportunityPayment__c opportunityPayment : opportunityPayments) {
			if (!opportunityPaymentsMapByOppId.containsKey(opportunityPayment.Opportunity__c)) {
				opportunityPaymentsMapByOppId.put(opportunityPayment.Opportunity__c, new List<OpportunityPayment__c>());
			}
			opportunityPaymentsMapByOppId.get(opportunityPayment.Opportunity__c).add(opportunityPayment);
		}
		return opportunityPaymentsMapByOppId;
	}

	public List<OpportunityPayment__c> getForPaymentSummaryForm(Id oppId) {
		return [
			SELECT
				Id,
				Opportunity__c,
				Order__c,
				Term__c,
				DueDate__c,
				Amount__c,
				ReceivedDate__c,
				ReceivedAmount__c,
				Remaining__c,
				PaymentStatus__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :oppId
				AND IsMasterData__c = true
				AND Opportunity__r.StageName != 'Closed Lost'
			ORDER BY Order__c
		];
	}

	public List<OpportunityPayment__c> getForInvoiceForm(Id oppId, Date dueDate) {
		return [
			SELECT Id, Opportunity__c, Term__c, DueDate__c, Amount__c, Remaining__c, PaymentStatus__c
			FROM OpportunityPayment__c
			WHERE Opportunity__c = :oppId
				AND Remaining__c > 0
				AND DueDate__c <= :dueDate
				AND IsMasterData__c = true
				AND Opportunity__r.StageName != 'Closed Lost'
				ORDER BY DueDate__c
		];
	}
}