force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteSelector.cls
public with sharing class QuoteSelector {
    public QuoteSelector() {

    }
    public static QuoteSelector instance;
    public static QuoteSelector getInstance(){
        if(instance == null){
            instance = new QuoteSelector();
        }
        return instance;
    }
    public Map<Id,Quote__c> getQuoteById(Set<Id> quoteIds){
        Map<Id, Quote__c> quoteMap = new Map<Id, Quote__c>();
        List<Quote__c> quoteRecords = [SELECT Id, Name, Opportunity__c FROM Quote__c WHERE Id IN :quoteIds];
        for (Quote__c quote : quoteRecords) {
            quoteMap.put(quote.Id, quote);
        }
        return quoteMap;
    }
}