force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>OpportunityPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSyncing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerActivation__mdt/TriggerActivation__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to configure to acitvatate/deactivate trigger execution</description>
    <label>Trigger Activation</label>
    <pluralLabel>Trigger Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean to check to activate/deactivate Trigger</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public with sharing class QuoteTriggerHandler {
    public QuoteTriggerHandler() {

    }
    public static QuoteTriggerHandler instance;
    public static QuoteTriggerHandler getInstance(){
        if (instance == null){
            instance = new QuoteTriggerHandler();
        }
        return instance;
    }

    public Boolean isActive = true;
    public List<Quote__c> newRecords;
    public Map<Id, Quote__c> oldMap;

    public Boolean isTriggerActivated() {
        if (TriggerActivation__mdt.getInstance('QuoteTrigger') != null) {
            return this.isActive && TriggerActivation__mdt.getInstance('QuoteTrigger').isActive__c;
        }
        return this.isActive;
    }
    public void setParams(List<Quote__c> newRecords, Map<Id, Quote__c> oldMap) {
        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }
    public void setBypass() {
        this.isActive = false;
    }

    public void clearBypass() {
        this.isActive = true;
    }

    public void executeAfterInsert(){
        this.cloneOpportunityPaymentFromOpportunity();
    }

    public void executeAfterUpdate() {
        this.stampDiscountToOppAfterSyncQuote();
        this.unsetPreviousSyncedQuote();
    }

    private void stampDiscountToOppAfterSyncQuote(){
        QuoteService service = QuoteService.getInstance();
        List<Quote__c> filteredQuotes = new List<Quote__c>();
        for (Quote__c quote : this.newRecords){
            Quote__c oldQuote = this.oldMap.get(quote.Id);
            if (oldQuote.IsSyncing__c != quote.IsSyncing__c && quote.IsSyncing__c == true){
                filteredQuotes.add(quote);
            }
        }
        if (!filteredQuotes.isEmpty()){
            List<Opportunity> updatedUpportunities = service.stampDiscountFromSyncedQuoteToOpportunity(filteredQuotes);
            update updatedUpportunities;
        }
    }

    private void unsetPreviousSyncedQuote(){
        QuoteService service = QuoteService.getInstance();
        List<Quote__c> filteredQuotes = new List<Quote__c>();
        for (Quote__c quote : this.newRecords){
            Quote__c oldQuote = this.oldMap.get(quote.Id);
            if (oldQuote.IsSyncing__c != quote.IsSyncing__c && quote.IsSyncing__c == true){
                filteredQuotes.add(quote);
            }
        }
        if (!filteredQuotes.isEmpty()){
            List<Quote__c> unsyncedQuote = service.unsetSyncedQuoteFromOthers(filteredQuotes);
            if (!unsyncedQuote.isEmpty()){
                update unsyncedQuote;
            }
        }
    }

    private void cloneOpportunityPaymentFromOpportunity(){
        OpportunityPaymentService oppPaymentService = OpportunityPaymentService.getInstance();
        List<OpportunityPayment__c> oppPayments = oppPaymentService.getClonedOpportunityPaymentByQuote(this.newRecords);
        if (!oppPayments.isEmpty()){
            insert oppPayments;
        }
    }

    
}