force-app/main/default/objects/PricebookEntry/fields/FQUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>FQUnitPrice__c</fullName>
    <label>FQ Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/FQUnitPricesqm__c.field-meta.xml
<CustomField>
    <fullName>FQUnitPricesqm__c</fullName>
    <formula>FQUnitPrice__c / AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FQ Unit Price/sq.m.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/TQUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>TQUnitPrice__c</fullName>
    <label>TQ Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/TQUnitPricesqm__c.field-meta.xml
<CustomField>
    <fullName>TQUnitPricesqm__c</fullName>
    <formula>TQUnitPrice__c / AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TQ Unit Price/sq.m.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PricebookEntrySelector.cls
public with sharing class PricebookEntrySelector {
    public PricebookEntrySelector() {

    }
    public static PricebookEntrySelector instance;
    public static PricebookEntrySelector getInstance(){
        if(instance == null){
            instance = new PricebookEntrySelector();
        }
        return instance;
    }
    public Map<Id, PricebookEntry> getPricebookEntiesByProductId(Set<Id> productIds){
        Map<Id, PricebookEntry> productPricebookEntiesMap = new Map<Id, PricebookEntry>();
        List<PricebookEntry> pricebookEntries = [
            SELECT Id, Product2Id, TQUnitPrice__c,FQUnitPrice__c,TQUnitPricesqm__c,FQUnitPricesqm__c
            FROM PricebookEntry
            WHERE Product2Id IN :productIds
        ];
        for (PricebookEntry entry : pricebookEntries) {
            productPricebookEntiesMap.put(entry.Product2Id, entry);
        }
        return productPricebookEntiesMap;
    }
}