force-app/main/default/objects/ClientOffer__c/ClientOffer__c.object-meta.xml
<CustomObject>
    <label>Client Offer</label>
    <nameField>
        <displayFormat>CO-{YY}{MM}{0000}</displayFormat>
        <label>Client Offer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientOffer__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>ClientOffers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClientOffer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClientOffer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <label>Address EN</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <label>Address TH</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FormatContractName__c.field-meta.xml
<CustomField>
    <fullName>FormatContractName__c</fullName>
    <formula>LEFT( Opportunity__r.Name , 80)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Format ContractName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>Stored the discount amount</description>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <description>Stores the discount percentage</description>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsCompletedContract__c.field-meta.xml
<CustomField>
    <fullName>IsCompletedContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCompletedContract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>OpportunityPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <description>ที่อยู่ภาษาไทย</description>
    <label>Address TH</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AddressEN__c.field-meta.xml
<CustomField>
    <fullName>AddressEN__c</fullName>
    <label>Address EN</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/AddressTH__c.field-meta.xml
<CustomField>
    <fullName>AddressTH__c</fullName>
    <label>Address TH</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <defaultValue>(0.00)</defaultValue>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractService.cls
public with sharing class ContractService {
    public static ContractService instance;
    public static ContractService getInstance(){
        if (instance == null){
            instance = new ContractService();
        }
        return instance;
    }

    public List<Contract> generateContractsFromOpportunities(List<Opportunity> opportunities){
        List<Contract> targetContracts = new List<Contract>();
        for (Opportunity opportunity : opportunities){
            Contract targetContract = new Contract();
            targetContract.Status = 'Draft';
            targetContract.Opportunity__c = opportunity.Id;
            targetContract.AccountId = opportunity.AccountId;
            targetContract.Project__c = opportunity.Project__c;
            targetContract.Unit__c = opportunity.Unit__c;
            targetContract.DiscountAmount__c = opportunity.DiscountAmount__c;
            targetContract.DiscountPercent__c = opportunity.DiscountPercent__c;
            List<Quote__c> syncedQuotes = opportunity.Quote__r;
            if (!syncedQuotes.isEmpty()){
                Quote__c syncedQuote = syncedQuotes[0];
                targetContract.AddressEN__c = syncedQuote.AddressEN__c;
                targetContract.AddressTH__c = syncedQuote.AddressTH__c;
            }
            targetContracts.add(targetContract);
        }
        return targetContracts;
    }

    public List<Contract> stampContractName(List<Contract> contracts){
        for (Contract contract : contracts){
            contract.Name = contract.FormatContractName__c;
        }
        return contracts;
    }

    public List<ClientOffer__c> makeRelationshipWithClientOffer(List<Contract> contracts){
        OpportunitySelector oppSelector = OpportunitySelector.getInstance();
        List<ClientOffer__c> updatedClientOffers = new List<ClientOffer__c>();
        Set<Id> oppIds = new Set<Id>();
        for (Contract contract : contracts){
            oppIds.add(contract.Opportunity__c);
        }
        Map<Id, Opportunity> opportunityWithClientOffer = oppSelector.getOpportunityWithClientOfferMapById(oppIds);
        for (Contract contract : contracts){
            Opportunity targetOpp = opportunityWithClientOffer.get(contract.Opportunity__c);
            List<ClientOffer__c> clientOffers = targetOpp.Client_Offers__r;
            if (!clientOffers.isEmpty()){
                for (ClientOffer__c clientOffer : clientOffers){
                    clientOffer.Contract__c = contract.Id;
                    updatedClientOffers.add(clientOffer);
                }
            }
        }
        return updatedClientOffers;
    }
/**
    * UAT Issue: DF-UAT-037
    */
    public Map<Id, Boolean> checkFullyPaidStatusForCompleteContract(List<Contract> contracts){
        OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
        Map<Id, Boolean> checkFullyPaidStatusOppPaymentMapByContractId = new Map<Id, Boolean>();
        Set<Id> oppIds = new Set<Id>();
        for (Contract contract : contracts){
            oppIds.add(contract.Opportunity__c);
        }
        Map<Id, List<OpportunityPayment__c>> opportunityPaymentMapById = oppPaymentSelector.getOpportunityPaymentsMapByOppId(oppIds);
        for(Contract contract : contracts){
            List<OpportunityPayment__c> oppPaymentForCheckStatus = opportunityPaymentMapById.get(contract.Opportunity__c) == null ? new List<OpportunityPayment__c>() : opportunityPaymentMapById.get(contract.Opportunity__c);
            for(OpportunityPayment__c oppPayment : oppPaymentForCheckStatus){
                if(oppPayment.Term__c.contains('Contract') && oppPayment.PaymentStatus__c != 'Fully Paid'){
                    checkFullyPaidStatusOppPaymentMapByContractId.put(contract.Id, false);
                    break;
                }
            }
        }
        return checkFullyPaidStatusOppPaymentMapByContractId;
    }
    public List<Opportunity> stampCompleteContractStatusToOpp(List<Contract> contracts){
        OpportunitySelector oppSelector = OpportunitySelector.getInstance();
        List<Opportunity> updatedOpportunities = new List<Opportunity>();
        Set<Id> oppIds = new Set<Id>();
        for (Contract contract : contracts){
            oppIds.add(contract.Opportunity__c);
        }
        Map<Id, Opportunity> opportunityMapById = oppSelector.getOpportunityMapById(oppIds);
        for (Opportunity opportunity : opportunityMapById.values()){
            opportunity.IsCompletedContract__c = true;
            updatedOpportunities.add(opportunity);
        }
        return updatedOpportunities;
    }

	/**
	 * Phase2
	 * Details:
	 * - Add method to stamp field to Contract after Novation Process
	 */
	public List<Contract> getContractAfterNovationProcess(List<Contract> oldContracts){
		for (Contract oldContract : oldContracts){
			oldContract.Status = 'Cancel';
			oldContract.CancelReason__c = GlobalConstants.OPP_LOST_REASON_NOVATION;
		}
		return oldContracts;
	}

	/**
	 * Phase2
	 * Details:
	 * - Add method to stamp field to Contract after Moving Process
	 */
	public List<Contract> getContractAfterMovingProcess(List<Contract> oldContracts, String action){
		for (Contract oldContract : oldContracts){
			oldContract.Status = 'Cancel';
			oldContract.CancelReason__c = action == 'upgrade' ? GlobalConstants.OPP_LOST_REASON_UPGRADE :
										action == 'downgrade' ? GlobalConstants.OPP_LOST_REASON_DOWNGRADE :
										GlobalConstants.OPP_LOST_REASON_MOVEPAYMENT;
		}
		return oldContracts;
	}

	/**
	 * Phase2
	 * Details:
	 * - Add method to stamp field to Contract after Moving Process
	 */
	public List<Contract> getContractAfterRefundForfeitProcess(List<Contract> oldContracts, String cancelReason){
		for (Contract oldContract : oldContracts){
			oldContract.Status = 'Cancel';
			oldContract.CancelReason__c = cancelReason;
		}
		return oldContracts;
	}
}