force-app/main/default/objects/ClientOffer__c/ClientOffer__c.object-meta.xml
<CustomObject>
    <label>Client Offer</label>
    <nameField>
        <displayFormat>CO-{YY}{MM}{0000}</displayFormat>
        <label>Client Offer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientOffer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CoBuyer__c/CoBuyer__c.object-meta.xml
<CustomObject>
    <label>Co-Buyer</label>
    <nameField>
        <displayFormat>COB-{000000}</displayFormat>
        <label>Co-Buyer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Buyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CoBuyer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Relationship field with opportunity</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Transferred, Closed Won, Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Co-Buyers</relationshipLabel>
    <relationshipName>Co_Borrowers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>OpportunityPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/PromotionOpportunity__c.object-meta.xml
<CustomObject>
    <label>Promotion Opportunity</label>
    <nameField>
        <displayFormat>POP-{000000}</displayFormat>
        <label>Promotion Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PromotionOpportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>promotion นี้อยู่ภายใต้ opportunity(โอกาสการขาย) ใด</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Promotion_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CompleteNovationController.cls
/**
 * Phase2
 * Details:
 * - add new controller for LWC:completeNovation
 */
public with sharing class CompleteNovationController {
    @AuraEnabled
	public static Map<String,List<SObject>> completeNovation(Id opportunityId){
		Savepoint sp = Database.setSavepoint();
		try {
			Map<String,List<SObject>> resultMap = new Map<String,List<SObject>>();
			ContractService contractService = ContractService.getInstance();
			PaymentReceiptService receiptService = PaymentReceiptService.getInstance();
			OpportunityService opportunityService = OpportunityService.getInstance();
			OpportunityAccountChangeLogService oppAccChangeLogService = OpportunityAccountChangeLogService.getInstance();
			OpportunitySelector opportunitySelector = OpportunitySelector.getInstance();
			Set<Id> oppIds = new Set<Id>{opportunityId};
			Map<Id, Opportunity> opportunityWithRelatedRecordForNovationMapById = opportunitySelector.getOpportuntiyWithRelatedRecordForNovationMapById(oppIds);
			List<OpportunityPayment__c> opportunityPayments = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Opportunity_Payments__r;
			List<Quote__c> syncedQuotes = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Quote__r;
			List<ClientOffer__c> clientOffers = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Client_Offers__r;
			List<PromotionOpportunity__c> promotionOpportunities = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Promotion_Transactions__r;
			List<CoBuyer__c> coBuyers = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Co_Borrowers__r;
			List<Contract> contracts = opportunityWithRelatedRecordForNovationMapById.get(opportunityId).Contracts__r;
			Opportunity oldOpporunity = opportunityWithRelatedRecordForNovationMapById.get(opportunityId);
			Opportunity novatedOpportunity = opportunityService.getClonedOpportunityForNovationProcess(oldOpporunity);
			OpportunityTriggerHandler.getInstance().setBypassCreatingPromotionOpportunity();
			OpportunityTriggerHandler.getInstance().setBypassCreatingOpportunityPayment();
			insert novatedOpportunity;
			OpportunityTriggerHandler.getInstance().clearBypassCreatingPromotionOpportunity();
			OpportunityTriggerHandler.getInstance().setBypassCreatingOpportunityPayment();
			oldOpporunity = opportunityService.getOpportunityAfterNovationProcess(oldOpporunity,novatedOpportunity);
			update oldOpporunity;
			List<SObject> clonedOpportunityPayments = opportunityService.clonedRecordRelateWithOpportunity(opportunityPayments,novatedOpportunity.Id);
			List<SObject> clonedSyncedQuotes = opportunityService.clonedRecordRelateWithOpportunity(syncedQuotes,novatedOpportunity.Id);
			List<SObject> clonedClientOffers = opportunityService.clonedRecordRelateWithOpportunity(clientOffers,novatedOpportunity.Id);
			List<SObject> clonedOpportunityPromotions = opportunityService.clonedRecordRelateWithOpportunity(promotionOpportunities,novatedOpportunity.Id);
			List<SObject> clonedCoBuyers = opportunityService.clonedRecordRelateWithOpportunity(coBuyers,novatedOpportunity.Id);
			List<SObject> clonedContracts = opportunityService.clonedRecordRelateWithOpportunity(contracts,novatedOpportunity.Id);
			insert clonedOpportunityPayments;
			insert clonedSyncedQuotes;
			insert clonedClientOffers;
			insert clonedOpportunityPromotions;
			// insert clonedCoBuyers;
			// insert with new status
			for (SObject clonedContract : clonedContracts){
				clonedContract.put('Status','Draft');
			}
			insert clonedContracts;
			// update with Signed Contract
			for (SObject clonedContract : clonedContracts){
				clonedContract.put('Status','Signed Contract');
			}
			update clonedContracts;
			OpportunityAccountChangeLog__c oppAccChangeLog = oppAccChangeLogService.craeteOpportunityAccountChangeLogFromPreviousAndCurrentOpportunity(oldOpporunity,novatedOpportunity);
			insert oppAccChangeLog;
			List<PaymentReceipt__c> snapshotReceipts = receiptService.lookupPaymentReceiptToOpportunityAccountChangeLog(new Set<Id>{oppAccChangeLog.Id});
			update snapshotReceipts;
			List<Contract> updatedContracts = contractService.getContractAfterNovationProcess(contracts);
			update updatedContracts;
			resultMap.put('oldOpportunity',new List<Opportunity>{oldOpporunity});
			resultMap.put('novatedOpportunity', new List<Opportunity>{novatedOpportunity});
			resultMap.put('clonedOpportunityPayments', clonedOpportunityPayments);
			resultMap.put('clonedSyncedQuotes', clonedSyncedQuotes);
			resultMap.put('clonedClientOffers', clonedClientOffers);
			resultMap.put('clonedOpportunityPromotions', clonedOpportunityPromotions);
			resultMap.put('clonedCoBuyers', clonedCoBuyers);
			resultMap.put('clonedContracts', clonedContracts);
			resultMap.put('oppAccChangeLog', new List<OpportunityAccountChangeLog__c>{oppAccChangeLog});
			resultMap.put('snapshotReceipts' , snapshotReceipts);
			return resultMap;
		} catch (Exception e) {
			Database.rollback(sp);
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
		}
	}


}