force-app/main/default/objects/ClientOffer__c/ClientOffer__c.object-meta.xml
<CustomObject>
    <label>Client Offer</label>
    <nameField>
        <displayFormat>CO-{YY}{MM}{0000}</displayFormat>
        <label>Client Offer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientOffer__c/fields/OriginalCost__c.field-meta.xml
<CustomField>
    <fullName>OriginalCost__c</fullName>
    <label>Original Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClientOffer__c/fields/PromotionMaster__c.field-meta.xml
<CustomField>
    <fullName>PromotionMaster__c</fullName>
    <label>Promotion Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PromotionMaster__c.Source__c</field>
            <operation>equals</operation>
            <value>Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromotionMaster__c</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/PromotionCost__c.field-meta.xml
<CustomField>
    <fullName>PromotionCost__c</fullName>
    <description>ต้นทุนของ Promotion</description>
    <label>Promotion Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClientOfferService.cls
public with sharing class ClientOfferService {
    public static ClientOfferService instance;

    public static ClientOfferService getInstance() {
        if (instance == null) {
            instance = new ClientOfferService();
        }
        return instance;
    }

    public List<ClientOffer__c> stampOriginalCostFromPromotionMasters(List<ClientOffer__c> clientOffers) {
        PromotionMasterSelector promotionMasterSelector = PromotionMasterSelector.getInstance();
        Set<Id> promotionMasterIds = new Set<Id>();
        for (ClientOffer__c clientOffer : clientOffers) {
            promotionMasterIds.add(clientOffer.PromotionMaster__c);
        }
        Map<Id, PromotionMaster__c> promotionMasterMapById = promotionMasterSelector.getPromotionMasterMapById(
            promotionMasterIds
        );
        for (ClientOffer__c clientOffer : clientOffers) {
            if (clientOffer.PromotionMaster__c != null) {
                PromotionMaster__c selectedPromotionMaster = promotionMasterMapById.get(clientOffer.PromotionMaster__c);
                clientOffer.OriginalCost__c = selectedPromotionMaster.PromotionCost__c;
            }
        }
        return clientOffers;
    }
}