force-app/main/default/objects/ClientOffer__c/ClientOffer__c.object-meta.xml
<CustomObject>
    <label>Client Offer</label>
    <nameField>
        <displayFormat>CO-{YY}{MM}{0000}</displayFormat>
        <label>Client Offer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientOffer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClientOffer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClientOffer__c/fields/PromotionMaster__c.field-meta.xml
<CustomField>
    <fullName>PromotionMaster__c</fullName>
    <label>Promotion Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PromotionMaster__c.Source__c</field>
            <operation>equals</operation>
            <value>Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromotionMaster__c</referenceTo>
    <relationshipLabel>Client Offers</relationshipLabel>
    <relationshipName>Client_Offers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/IsMasterData__c.field-meta.xml
<CustomField>
    <fullName>IsMasterData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>เพื่อบอกว่า Record นี้ เป็นค่าตั้งต้นใน Opportunity Payment</description>
    <label>Is Master Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__c</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>PaymentReceipt__r.Opportunity__r.Name</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Not for Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>สถานะของ Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion ที่ผูกกับ unit</description>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionOpportunity__c/PromotionOpportunity__c.object-meta.xml
<CustomObject>
    <label>Promotion Opportunity</label>
    <nameField>
        <displayFormat>POP-{000000}</displayFormat>
        <label>Promotion Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PromotionOpportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>promotion นี้อยู่ภายใต้ opportunity(โอกาสการขาย) ใด</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Promotion_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityMoverController.cls
/**
 * Phase2
 * Details:
 * - Init Controller for opportunityMover
 */
public class OpportunityMoverController {

	/**
	 * Phase2
	 * Details:
	 * - add method to return OpportunityDetails to lwc
	 */
    @AuraEnabled
    public static OpportunityDetails getOpportunityDetails(Id opportunityId) {
		try {
			OpportunitySelector oppSelector = OpportunitySelector.getInstance();
			Map<Id, Opportunity> opportunityMapById = oppSelector.getOpportuntiyWithRelatedRecordForNovationMapById(new Set<Id>{opportunityId});
			Opportunity targetOpp = opportunityMapById.get(opportunityId);
			OpportunityDetails oppDetails = new OpportunityDetails(targetOpp);
			return oppDetails;
		} catch (Exception e) {
			System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
		}
	}

	/**
	 * Phase2
	 * Details:
	 * - add method to perform complete
	 */
	@AuraEnabled
	public static MoveOpportunityResult completeAction(
		Id currentOpportunityId,
		String action,
		String moveReason,
		Decimal operationFee,
		Decimal receivedAmount,
		String url,
		String newOpportunityItemJSON,
		PaymentMethod__c paymentMethod,
		List<Id> selectedPromotionAndClientOfferIds,
		Boolean isFirstTime
		)
	{
		Savepoint sp = Database.setSavepoint();
		try {
			MoveOpportunityResult result = new MoveOpportunityResult();
			// ----- SERVICE -----
			OpportunityPaymentService oppPaymentService = OpportunityPaymentService.getInstance();
			PaymentReceiptService paymentReceiptService = PaymentReceiptService.getInstance();
			ContractService contractService = ContractService.getInstance();
			OpportunityService oppService = OpportunityService.getInstance();
			UpgradeDowngradeMovePaymentService upgradeDowngradeMovePaymentService = UpgradeDowngradeMovePaymentService.getInstance();
			// ----- SELECTOR -----
            OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
			OpportunitySelector oppSelector = OpportunitySelector.getInstance();
			// ----- Deserialized -----
			NewOpportunityItem newOpportunityItem =
				(NewOpportunityItem) JSON.deserialize(newOpportunityItemJSON, NewOpportunityItem.class);
			// ----- Get Map -----
			Map<Id, Opportunity> oppMapById = oppSelector.getOpportuntiyWithRelatedRecordForNovationMapById(new Set<Id>{currentOpportunityId,newOpportunityItem.opportunityId});
			Map<Id, List<OpportunityPayment__c>> opportunityPaymentMapByOppId = oppPaymentSelector.getOpportunityPaymentsWithInvoiceLineItemMapByOppId(
                new Set<Id>{newOpportunityItem.opportunityId}
            );
			// ----- STEP 1: Update Old Opp to Close Lost -> Cancel all Invoices and Receipts -> change Unit Status to Block
			Opportunity oldOpp = oppMapById.get(currentOpportunityId);
			Opportunity newOpp = oppMapById.get(newOpportunityItem.opportunityId);
			if (isFirstTime){
				Opportunity closedOldOpp = oppService.getOpportunityAfterMovingProcess(oldOpp,newOpp,action);
				update closedOldOpp;
				result.currentOpportunity = closedOldOpp;
			} else {
				result.currentOpportunity = oldOpp;
			}
			Opportunity updatedNewOpp = oppService.getNewOpportunityAfterMovingProcess(oldOpp,newOpp,action);
			update updatedNewOpp;
			result.newOpportunity = updatedNewOpp;
			// ----- STEP 2: Create Promotion Opportunity and Client Offer
			List<PromotionOpportunity__c> promotionOldOpps = oldOpp.Promotion_Transactions__r;
			List<PromotionOpportunity__c> clonedPromotionOpps = new List<PromotionOpportunity__c>();
			for (PromotionOpportunity__c promotionOldOpp : promotionOldOpps){
				if (selectedPromotionAndClientOfferIds.contains(promotionOldOpp.Id)){
					PromotionOpportunity__c clonedRecord = promotionOldOpp.clone(false,false,false,false);
					clonedRecord.Opportunity__c = updatedNewOpp.Id;
					clonedPromotionOpps.add(clonedRecord);
				}
			}
			List<ClientOffer__c> clientOffersOldOpps = oldOpp.Client_Offers__r;
			List<ClientOffer__c> clonedClientOffersOldOpps = new List<ClientOffer__c>();
			for (ClientOffer__c clientOfferOldOpp : clientOffersOldOpps){
				if (selectedPromotionAndClientOfferIds.contains(clientOfferOldOpp.Id)){
					ClientOffer__c clonedRecord = clientOfferOldOpp.clone(false,false,false,false);
					clonedRecord.Opportunity__c = updatedNewOpp.Id;
					clonedClientOffersOldOpps.add(clonedRecord);
				}
			}
			if (!clonedPromotionOpps.isEmpty()){
				insert clonedPromotionOpps;
			}
			result.clonedPromotionOpps = clonedPromotionOpps;
			if (!clonedClientOffersOldOpps.isEmpty()){
				insert clonedClientOffersOldOpps;
			}
			result.clonedClientOffers = clonedClientOffersOldOpps;
			// ----- STEP 3: Update Contract under old opp to Cancel
			if (isFirstTime){
				List<Contract> contracts = oldOpp.Contracts__r;
				List<Contract> canceledContracts = contractService.getContractAfterMovingProcess(contracts, action);
				update canceledContracts;
				result.contracts = canceledContracts;
			}
			// ----- STEP 4: Generate Receipt from Moving Amount
			PaymentReceipt__c paymentReceipt = paymentReceiptService.generateMovingPaymentReceiptRelatedToOpportunity(newOpportunityItem.opportunityId,currentOpportunityId);
			if (oldOpp.Unit__r.ProductCode == newOpp.Unit__r.ProductCode){
				paymentReceipt.ReceiptType__c = GlobalConstants.RECEIPT_TYPE_MOVEPAYMENTNOOPERATION;
			}
			insert paymentReceipt;
			PaymentReceipt__c paymentReceiptWithRunningNo = paymentReceiptService.generateRunningNo(paymentReceipt);
			update paymentReceiptWithRunningNo;
			result.receipt = paymentReceiptWithRunningNo;
			paymentMethod.PaymentReceipt__c = paymentReceipt.Id;
			insert paymentMethod;
			result.paymentMethod = paymentMethod;
            List<OpportunityPayment__c> oppPayments = opportunityPaymentMapByOppId.get(newOpportunityItem.opportunityId);
			List<PaymentReceiptLineItem__c> paymentReceiptLineItems = paymentReceiptService.generatePaymentReceiptLineItemFromTotalReceivedAmount(receivedAmount,oppPayments,paymentReceipt.Id,paymentMethod.Id);
            insert paymentReceiptLineItems;
			result.receiptLine = paymentReceiptLineItems;
			List<OpportunityPayment__c> updatedOppPayments = oppPaymentService.stampFieldFromReceiptLineItem(paymentReceiptLineItems);
            update updatedOppPayments;
			result.oppPayments = updatedOppPayments;
			// ----- STEP 4.2: Generate Operation Fee Receipt
			if (isFirstTime){
				if (operationFee != null && operationFee != 0){
					PaymentReceipt__c operationPaymentReceipt = paymentReceiptService.generateOperationPaymentReceiptRelatedToOpportunity(currentOpportunityId,'move_payment');
					operationPaymentReceipt.CustomGLKey__c = paymentReceipt.CustomGLKey__c;
					operationPaymentReceipt.CustomGLDate__c = Date.today();
					insert operationPaymentReceipt;
					PaymentReceipt__c operationPaymentReceiptWithRunningNo = paymentReceiptService.generateRunningNo(operationPaymentReceipt);
					update operationPaymentReceiptWithRunningNo;
					List<PaymentReceiptLineItem__c> operationPaymentReceiptLineItems = paymentReceiptService.generateOperationPaymentReceiptLineItem(operationFee,operationPaymentReceipt.Id,null,null);
					insert operationPaymentReceiptLineItems;
				}
			}
			// ----- STEP 5: Generate UpgradeDowngradeMovePayment__c
			UpgradeDowngradeMovePayment__c upgradeDowngradeOppPayment = upgradeDowngradeMovePaymentService.generateUpgradeDowngradeMovePayment(action,oldOpp,updatedNewOpp,url,operationFee,moveReason);
			insert upgradeDowngradeOppPayment;
			result.upgradeDowngradeMovePayment = upgradeDowngradeOppPayment;
			return result;
		} catch (Exception e) {
			Database.rollback(sp);
			System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
			throw new applicationException('You cant do that here: ' + e.getStackTraceString() + ' ' + e.getMessage());
			// throw new AuraHandledException('Error in completeAction: ' + e.getMessage() + ' ' + e.getStackTraceString());
		}
	}

	/**
	 * Phase2
	 * Details:
	 * - add method to insert Task
	 */
	@AuraEnabled
	public static MoveOpportunityResult insertTask(String taskItemJSON) {
		Savepoint sp = Database.setSavepoint();
		try {
			MoveOpportunityResult result = new MoveOpportunityResult();
			TaskService taskService = TaskService.getInstance();
			List<TaskItem> taskItems = (List<TaskItem>) JSON.deserialize(taskItemJSON, List<TaskItem>.class);
			List<Task> tasks = new List<Task>();
			for (TaskItem taskItem : taskItems){
				Task task = taskService.generateTask(taskItem.subject, taskItem.description, taskItem.oppId);
				tasks.add(task);
			}
			insert tasks;
			result.tasks = tasks;
			return result;
		} catch (Exception e) {
			Database.rollback(sp);
			System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
			throw new applicationException('You cant do that here: ' + e.getStackTraceString() + ' ' + e.getMessage());
			// throw new AuraHandledException('Error in completeAction: ' + e.getMessage());
		}
	}

	/**
	 * Phase2
	 * Details:
	 * - add method to check outstanding payment
	 */
	@AuraEnabled
	public static Boolean hasOutstandingPayments(List<Id> opportunityIds) {
		try {
			List<OpportunityPayment__c> unpaidPayments = [
				SELECT Id
				FROM OpportunityPayment__c
				WHERE Opportunity__c IN :opportunityIds
				AND DueDate__c <= :Date.today()
				AND PaymentStatus__c != 'Fully Paid'
				AND IsMasterData__c = TRUE
			];
			return !unpaidPayments.isEmpty();
		} catch (Exception e) {
			throw new AuraHandledException('Error validating payment statuses: ' + e.getMessage());
		}
	}


	public class OpportunityDetails {
		@AuraEnabled public String opportunityName;
		@AuraEnabled public String projectName;
		@AuraEnabled public String unitName;
		@AuraEnabled public String unitCode;
		@AuraEnabled public Decimal netPrice;
		@AuraEnabled public Decimal totalPaidAmount;
		@AuraEnabled public List<PromotionOpportunity> opportunityPromotions;
        @AuraEnabled public List<ClientOffer> clientOffers;
        @AuraEnabled public List<ReceivedPromotion> receivedPromotions;
		@AuraEnabled public String stageName;

		public OpportunityDetails(Opportunity opportunity){
			this.opportunityName = opportunity.Name;
			this.projectName = opportunity.Project__r.Name;
			this.unitName = opportunity.Unit__r.Name;
			this.unitCode = opportunity.Unit__r.ProductCode;
			this.netPrice = opportunity.NetPrice__c;
			this.totalPaidAmount = opportunity.TotalPaidAmount__c;
			this.stageName = opportunity.StageName;
			this.opportunityPromotions = new List<PromotionOpportunity>();
			this.clientOffers = new List<ClientOffer>();
			this.receivedPromotions = new List<ReceivedPromotion>();
			List<PromotionOpportunity__c> targetOppPromotions = opportunity.Promotion_Transactions__r;
			List<ClientOffer__c> targetClientOffers = opportunity.Client_Offers__r;
			for (PromotionOpportunity__c targetOppPromotion : targetOppPromotions){
				this.opportunityPromotions.add(new PromotionOpportunity(targetOppPromotion));
				if (targetOppPromotion.Status__c == 'Received'){
					this.receivedPromotions.add(new ReceivedPromotion(targetOppPromotion.Id, targetOppPromotion.PromotionMaster__r.Name));
				}
			}
			for (ClientOffer__c targetClientOffer : targetClientOffers){
				this.clientOffers.add(new ClientOffer(targetClientOffer));
				if (targetClientOffer.Status__c == 'Received'){
					this.receivedPromotions.add(new ReceivedPromotion(targetClientOffer.Id, targetClientOffer.PromotionMaster__r.Name));
				}
			}
		}
	}

	public class PromotionOpportunity {
		@AuraEnabled public Id id;
        @AuraEnabled public String name;
        @AuraEnabled public String status;
		@AuraEnabled public String type;
		@AuraEnabled public Boolean isReceived;

		public PromotionOpportunity(PromotionOpportunity__c promotionOpportunity){
			this.id = promotionOpportunity.Id;
			this.name = promotionOpportunity.PromotionMaster__r.Name;
			this.status = promotionOpportunity.Status__c;
			this.type = 'Promotion';
			this.isReceived = promotionOpportunity.Status__c == 'Received';
		}
	}

	public class ClientOffer {
		@AuraEnabled public Id id;
        @AuraEnabled public String name;
        @AuraEnabled public String status;
		@AuraEnabled public String type;
		@AuraEnabled public Boolean isReceived;

		public ClientOffer(ClientOffer__c clientOffer){
			this.id = clientOffer.Id;
			this.name = clientOffer.PromotionMaster__r.Name;
			this.status = clientOffer.Status__c;
			this.type = 'ClientOffer';
			this.isReceived = clientOffer.Status__c == 'Received';
		}
	}

	public class ReceivedPromotion {
		@AuraEnabled public Id id;
		@AuraEnabled public String name;

		public ReceivedPromotion(Id promotionId ,String name){
			this.id = promotionId;
			this.name = name;
		}
	}

	public class NewOpportunityItem {
		@AuraEnabled public Id opportunityId;
		@AuraEnabled public Decimal amountToMove;
	}

	public class TaskItem {
		@AuraEnabled public Id oppId;
		@AuraEnabled public String subject;
		@AuraEnabled public String description;
	}

	public class MoveOpportunityResult {
		@AuraEnabled public Opportunity currentOpportunity;
		@AuraEnabled public Opportunity newOpportunity;
		@AuraEnabled public List<PromotionOpportunity__c> clonedPromotionOpps;
		@AuraEnabled public List<ClientOffer__c> clonedClientOffers;
		@AuraEnabled public List<Contract> contracts;
		@AuraEnabled public PaymentReceipt__c receipt;
		@AuraEnabled public List<PaymentReceiptLineItem__c> receiptLine;
		@AuraEnabled public PaymentMethod__c paymentMethod;
		@AuraEnabled public List<OpportunityPayment__c> oppPayments;
		@AuraEnabled public UpgradeDowngradeMovePayment__c upgradeDowngradeMovePayment;
		@AuraEnabled public List<Task> tasks;
	}

	public class applicationException extends Exception {}
}