force-app/main/default/objects/ClientOffer__c/ClientOffer__c.object-meta.xml
<CustomObject>
    <label>Client Offer</label>
    <nameField>
        <displayFormat>CO-{YY}{MM}{0000}</displayFormat>
        <label>Client Offer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/TriggerActivation__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to configure to acitvatate/deactivate trigger execution</description>
    <label>Trigger Activation</label>
    <pluralLabel>Trigger Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean to check to activate/deactivate Trigger</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ClientOfferTriggerHandler.cls
public with sharing class ClientOfferTriggerHandler {
    public static ClientOfferTriggerHandler instance;
    public ClientOfferTriggerHandler() {

    }
    public static ClientOfferTriggerHandler getInstance(){
        if (instance == null) {
            instance = new ClientOfferTriggerHandler();
        }
        return instance;
    }

    public Boolean isActive = true;
    public List<ClientOffer__c> newRecords;
    public Map<Id,ClientOffer__c> oldMap;

    public Boolean isTriggerActivated(){
        if (TriggerActivation__mdt.getInstance('ClientOfferTrigger') != null){
            return this.isActive && TriggerActivation__mdt.getInstance('ClientOfferTrigger').isActive__c;
        }
        return this.isActive;
    }

    public void setBypass(){
        this.isActive = false;
    }

    public void clearBypass(){
        this.isActive = true;
    }

    public void setParams(List<ClientOffer__c> newRecords, Map<Id,ClientOffer__c> oldMap){
        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }

    public void executeBeforeInsert(){
        this.stampOriginalCostFromPromotionMaster();
    }

    private void stampOriginalCostFromPromotionMaster(){
        ClientOfferService service = ClientOfferService.getInstance();
        service.stampOriginalCostFromPromotionMasters(this.newRecords);
    }
}