force-app/main/default/objects/Lead/fields/IsAutoAssingment__c.field-meta.xml
<CustomField>
    <fullName>IsAutoAssingment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Auto Assingment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadCountry__c.field-meta.xml
<CustomField>
    <fullName>LeadCountry__c</fullName>
    <label>Lead Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LeadCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadOrigin__c.field-meta.xml
<CustomField>
    <fullName>LeadOrigin__c</fullName>
    <label>Lead Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key in</fullName>
            </value>
            <value>
                <fullName>Upload</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
public with sharing class LeadSelector {
    public static LeadSelector instance;

    public LeadSelector() {
    }

    public static LeadSelector getInstance() {
        if (instance == null) {
            instance = new LeadSelector();
        }
        return instance;
    }

    // get Leads owned by Queue
    public List<Lead> getLeadsOwnedByQueues() {
        return [
            SELECT Id, OwnerId
            FROM Lead
            WHERE OwnerId IN (SELECT Id FROM Group WHERE Type = 'Queue')
        ];
    }

    // get Leads map by Queue
    public Map<Id, List<Lead>> getLeadsMapByQueueId(Set<Id> queueIds) {
        Map<Id, List<Lead>> leadsMapByQueueId = new Map<Id, List<Lead>>();
        List<Lead> leads = [
            SELECT Id, OwnerId
            FROM Lead
            WHERE OwnerId IN :queueIds
        ];
        for (Lead lead : leads) {
            if (!leadsMapByQueueId.containsKey(lead.OwnerId)) {
                leadsMapByQueueId.put(lead.OwnerId, new List<Lead>());
            }
            leadsMapByQueueId.get(lead.OwnerId).add(lead);
        }
        return leadsMapByQueueId;
    }

    public Map<Id, Lead> getLeadMapById(Set<Id> leadIds) {
        return new Map<Id, Lead>(
            [
                SELECT Id, OwnerId, LeadOrigin__c, LeadCountry__c, IsAutoAssingment__c
                FROM Lead
				WHERE Id IN: leadIds
            ]
        );
    }
}