force-app/main/default/objects/Opportunity/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <formula>Unit__r.AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectService.cls
/**
 * Phase2
 * Details:
 * - Add new class to be service of Project__c
 */
public class ProjectService {

    public static ProjectService instance;

	public static ProjectService getInstance() {
		if (instance == null) {
			instance = new ProjectService();
		}
		return instance;
	}

	/**
	 * Phase2
	 * Details:
	 * - Add new method to calculate Total FQ booked and sold
	 */
	public Map<Id,Decimal> calculateAreaBookedOrSoldAsFQQuota(Set<Id> projectIds){
		Map<Id,Decimal> areaOfBookedOrSoldFQQuotaMapByProjectId = new Map<Id,Decimal>();
		ProjectSelector projectSelector = ProjectSelector.getInstance();
		Map<Id, Project__c> projectWithForeignOppMapById = projectSelector.getProjectWithForeignOppMapById(projectIds);
		for (Id projectId : projectWithForeignOppMapById.keySet()){
			Decimal totalForeignBookAndSoldArea = 0;
			Project__c targetProject = projectWithForeignOppMapById.get(projectId);
			List<Opportunity> foreignOpportunities = targetProject.Opportunities__r;
			for (Opportunity foreignOpportunity : foreignOpportunities){
				totalForeignBookAndSoldArea =  foreignOpportunity.Unit__r.AreaSqm__c == null ? totalForeignBookAndSoldArea : totalForeignBookAndSoldArea + foreignOpportunity.Unit__r.AreaSqm__c;
			}
			areaOfBookedOrSoldFQQuotaMapByProjectId.put(projectId, totalForeignBookAndSoldArea);
		}
		return areaOfBookedOrSoldFQQuotaMapByProjectId;
	}
}