force-app/main/default/objects/Opportunity/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>Stored the discount amount</description>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <description>Stores the discount percentage</description>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DiscountPercentOfAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercentOfAmount__c</fullName>
    <description>Converts the discount amount into a percentage relative to the unit price. [Hide this field from Page Layout]</description>
    <formula>BLANKVALUE(DiscountAmount__c, 0) / UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Percent Of Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <formula>(  BLANKVALUE(UnitPrice__c, 0.00)  -( BLANKVALUE(UnitPrice__c, 0.00) *BLANKVALUE(TotalDiscountPercent__c, 0.00) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Quota__c</field>
            <operation>equals</operation>
            <valueField>PaymentTermMaster__c.Quota__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalDiscountAmount__c</fullName>
    <formula>UnitPrice__c -  NetPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalDiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>TotalDiscountPercent__c</fullName>
    <description>Combining a Discount Percent field and a Discount Amount field</description>
    <formula>BLANKVALUE(DiscountPercent__c, 0.00) + BLANKVALUE(DiscountPercentOfAmount__c, 0.00)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discount Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Total Unit Price (THB) ราคาห้องชุด (บาท)</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The original price before discounts. Get value from &apos;Pricebook2&apos;</description>
    <label>Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PAT-{000000}</displayFormat>
        <label>Payment Terms REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/fields/PaymentTermMaster__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermMaster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Master Name</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Payment Term Line Item</relationshipLabel>
    <relationshipName>Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>PaymentTermMaster__r.Project__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/PaymentTermMaster__c.object-meta.xml
<CustomObject>
    <description>The standard terms and conditions for payments, including due dates, type, no. of installment and payment structure.</description>
    <label>Payment Term Master</label>
    <nameField>
        <label>Payment Term Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Term Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTermMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Term Masters</relationshipLabel>
    <relationshipName>Payment_Term_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentTermMaster__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
    TODAY() &gt;=  ActiveFrom__c &amp;&amp; TODAY() &lt;=  ActiveTo__c , 
    &quot;Active&quot;, 
    &quot;Inactive&quot;
)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>สถานะของ Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <defaultValue>(0.00)</defaultValue>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DiscountPercentOfAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercentOfAmount__c</fullName>
    <label>Discount Percent Of Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>PaymentTermMaster__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalDiscountAmount__c</fullName>
    <label>Total Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalDiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>TotalDiscountPercent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/UnitNo__c.field-meta.xml
<CustomField>
    <fullName>UnitNo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit No.</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteService.cls
public with sharing class QuoteService {
	public static QuoteService instance;
	public static QuoteService getInstance(){
		if (instance == null){
			instance = new QuoteService();
		}
		return instance;
	}

	/**
	 * Phase: 1
	 * UAT Issue: DF-UAT-025
	*/
	public List<Quote__c> generateQuotesFromOpportunities(List<Opportunity> opportunities){
		AccountSelector accountSelector = AccountSelector.getInstance();
		List<Quote__c> targetQuotes = new List<Quote__c>();
		Set<Id> accountIds = new Set<Id>();
		for (Opportunity opportunity : opportunities){
			accountIds.add(opportunity.AccountId);
		}
		Map<Id, Account> accountWithContactsMapById = accountSelector.getAccountWithContactsMapById(accountIds);
		for (Opportunity opportunity : opportunities){
			Account targetAccount = accountWithContactsMapById.get(opportunity.AccountId);
			Quote__c targetQuote = new Quote__c();
			targetQuote.Opportunity__c = opportunity.Id;
			targetQuote.Status__c = 'Open';
			targetQuote.DiscountPercent__c = opportunity.DiscountPercent__c;
			targetQuote.PaymentTerm__c = opportunity.PaymentTermMaster__c;
			targetQuote.DiscountAmount__c = opportunity.DiscountAmount__c;
			targetQuote.DiscountPercentOfAmount__c = opportunity.DiscountPercentOfAmount__c;
			targetQuote.TotalDiscountPercent__c = opportunity.TotalDiscountPercent__c;
			targetQuote.TotalPrice__c = opportunity.NetPrice__c;
			targetQuote.UnitPrice__c = opportunity.UnitPrice__c;
			targetQuote.TotalDiscountAmount__c = opportunity.TotalDiscountAmount__c;
			targetQuote.AccountName__c = opportunity.AccountId;
			targetQuote.ProjectName__c = opportunity.Project__c;
			targetQuote.UnitNo__c = opportunity.Unit__c;
			targetQuote.ExpirationDate__c = opportunity.CloseDate;
			targetQuote.AddressEN__c = opportunity.Account.AddressEN__c;
			targetQuote.AddressTH__c = opportunity.Account.AddressTH__c;
			targetQuote.UnitPricePersqm__c = opportunity.UnitPricePersqm__c;
			targetQuote.NetPricePerSqm__c = opportunity.NetPricePerSqm__c;
			if (targetAccount != null){
				targetQuote.Fax__c = targetAccount.Fax;
				if (targetAccount.RecordType.DeveloperName == 'Co_Owner_Corporate' || targetAccount.RecordType.DeveloperName == 'Prospect_Corporate'){
					List<Contact> contacts = targetAccount.Contacts == null ? new List<Contact>() : targetAccount.Contacts;
					Contact targetContact = contacts.size() > 0 ? contacts[0] : null;
					for (Contact contact : contacts){
						if (contact.IsPrimaryContact__c){
							targetContact = contact;
						}
					}
					if (targetContact != null){
						targetQuote.ContactName__c = targetContact.FirstName + ' ' + targetContact.LastName;
						targetQuote.Phone__c = targetContact.Phone;
						targetQuote.Email__c = targetContact.Email;
					}
				} else {
					targetQuote.ContactName__c = targetAccount.Name;
					targetQuote.Phone__c = targetAccount.Phone;
					targetQuote.Email__c = targetAccount.Email__c;
				}
			}
			targetQuotes.add(targetQuote);
		}
		return targetQuotes;
	}
	public Map<String, SObject> getMapForSyncQuoteToOpp(List<Quote__c> quotes){
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		Map<String, SObject> syncQuoteToOppMap = new Map<String, SObject>();
		List<Quote__c> quoteList = new List<Quote__c>();
		Set<Id> quoteIds = new Set<Id>();
		Set<Id> oppIds = new Set<Id>();
		for (Quote__c quote : quotes){
			oppIds.add(quote.Opportunity__c);
		}
		Map<Id, Opportunity> opportunityMapById = oppSelector.getOpportunityMapById(oppIds);
		for(Quote__c quote : quotes){
			quote.IsSyncing__c = true;
			Opportunity opportunity = opportunityMapById.get(quote.Opportunity__c);
			if(opportunity != null){
				opportunity.SyncedQuoteId__c = quote.Id;
				syncQuoteToOppMap.put('Opportunity', opportunity);
			}
			syncQuoteToOppMap.put('Quote__c', quote);
		}
		return syncQuoteToOppMap;
	}

	public List<Quote__c> unsetSyncedQuoteFromOthers(List<Quote__c> quotes){
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		List<Quote__c> unsyncedQuote = new List<Quote__c>();
		Set<Id> oppIds = new Set<Id>();
		for(Quote__c quote: quotes){
			oppIds.add(quote.Opportunity__c);
		}
		Map<Id, Opportunity> opportunityWithSyncedQuoteMapById = oppSelector.getOpportunityWithSyncedQuotedMapById(oppIds);
		for(Quote__c quote: quotes){
			Opportunity targetOpportunity = opportunityWithSyncedQuoteMapById.get(quote.Opportunity__c);
			List<Quote__c> allSyncedQuotes = targetOpportunity.Quote__r == null ? new List<Quote__c>() : targetOpportunity.Quote__r;
			for (Quote__c syncedQuote : allSyncedQuotes){
				if (syncedQuote.Id != quote.Id){
					syncedQuote.IsSyncing__c = false;
					unsyncedQuote.add(syncedQuote);
				}
			}
		}
		return unsyncedQuote;
	}

	public List<Opportunity> stampDiscountFromSyncedQuoteToOpportunity(List<Quote__c> quotes){
		OpportunitySelector oppSelector = OpportunitySelector.getInstance();
		List<Opportunity> updatedOpportunities = new List<Opportunity>();
		Set<Id> oppIds = new Set<Id>();
		for (Quote__c quote : quotes){
			oppIds.add(quote.Opportunity__c);
		}

		System.debug('oppIds' + oppIds);
		Map<Id, Opportunity> opportunityMapById = oppSelector.getOpportunityMapById(oppIds);
		for (Quote__c quote : quotes){
			Opportunity opportunity = opportunityMapById.get(quote.Opportunity__c);
			if (opportunity != null){
				opportunity.DiscountPercent__c = quote.DiscountPercent__c;
				opportunity.DiscountAmount__c = quote.DiscountAmount__c;
				updatedOpportunities.add(opportunity);
			}
		}
		return updatedOpportunities;
	}


}