force-app/main/default/objects/Opportunity/fields/LastGLStatusInPojjaman__c.field-meta.xml
<CustomField>
    <fullName>LastGLStatusInPojjaman__c</fullName>
    <label>Last GL Status In Pojjaman</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LossReason__c.field-meta.xml
<CustomField>
    <fullName>LossReason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Interest</fullName>
            </value>
            <value>
                <fullName>Budget Constraints</fullName>
            </value>
            <value>
                <fullName>Chose competitor</fullName>
            </value>
            <value>
                <fullName>Unreachable</fullName>
            </value>
            <value>
                <fullName>Extended Decision-Making Time</fullName>
            </value>
            <value>
                <fullName>Changed Requirements</fullName>
            </value>
            <value>
                <fullName>Outdated Opportunities</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/CancelReason__c.field-meta.xml
<CustomField>
    <fullName>CancelReason__c</fullName>
    <label>Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Cancel by CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/IsCancel__c.field-meta.xml
<CustomField>
    <fullName>IsCancel__c</fullName>
    <formula>if( ISBLANK(Text(CancelReason__c)),false,True)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Cancel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>PaymentReceipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GLApiCalloutBatch.cls
public with sharing class GLApiCalloutBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
	public GLApiCalloutBatch() {
	}
	public Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(
			[
				SELECT
					Id,
					LastGLStatusInPojjaman__c,
					TotalOperationFee__c,
					NetAgreedRefundAmount__c,
					NetAgreedForfeitAmount__c,
					(
						SELECT Id, LastGLStatusInPojjaman__c
						FROM Invoices__r
						WHERE (LastGLStatusInPojjaman__c = null OR
						LastGLStatusInPojjaman__c = 'Fail')
						ORDER BY CreatedDate ASC
					),
					(
						SELECT Id,
						IsCancel__c,
						CancelReason__c, LastGLStatusInPojjaman__c
						FROM PaymentReceipt__r
						WHERE
						(CancelReason__c =: GlobalConstants.RECEIPT_LOST_REASON_CANCELREFUND OR
						CancelReason__c =: GlobalConstants.RECEIPT_LOST_REASON_CANCELFORFEIT OR
						CancelReason__c =: GlobalConstants.RECEIPT_LOST_REASON_TERMINATIONREFUND OR
						CancelReason__c =: GlobalConstants.RECEIPT_LOST_REASON_TERMINATIONFORFEIT) AND
						(LastGLStatusInPojjaman__c = null OR
						LastGLStatusInPojjaman__c = 'Fail')
						ORDER BY CreatedDate ASC
					)
				FROM Opportunity
				WHERE StageName =: GlobalConstants.OPP_STAGENAME_CLOSED_LOST AND
				(LastGLStatusInPojjaman__c = 'Fail' OR LastGLStatusInPojjaman__c = null) AND
				(LossReason__c =: GlobalConstants.OPP_LOST_REASON_CANCELFORFEIT OR
				LossReason__c =: GlobalConstants.OPP_LOST_REASON_TERMINATIONFORFEIT OR
				LossReason__c =: GlobalConstants.OPP_LOST_REASON_CANCELREFUND OR
				LossReason__c =: GlobalConstants.OPP_LOST_REASON_TERMINATIONREFUND )
				ORDER BY LastModifiedDate ASC
			]
		);
	}

	public void execute(Database.BatchableContext bc, List<SObject> scope) {
		GLApiCallout callout = new GLApiCallout(scope);
		callout.execute();
	}

	public void finish(Database.BatchableContext bc) {
		// execute next batch
	}
}