force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RecurringTextFileGeneratorScheduler.cls
public class RecurringTextFileGeneratorScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<Project__c> projectList = [
            SELECT Id
            FROM Project__c
        ];

		// There is some query,dml in for loop. However, since Project__c is not bulk object, so it is not a problem.
        for (Project__c project : projectList) {
            try {
                generateRecurringTextFile(project.Id);
            } catch (Exception e) {
                System.debug('Error while generating file for Project ' + project.Id + ': ' + e.getMessage());
            }
        }
    }

    private static void generateRecurringTextFile(Id projectId) {
        String contentRecurring = '';
        Set<Id> opportunityIdSet = new Set<Id>();
        List<ContentVersion> contentVersionToCreate = new List<ContentVersion>();

        Map<Id, Project__c> projectMap = ProjectSelector.getInstance().getProjectWithOppMapById(new Set<Id>{projectId});
        Project__c projectById = projectMap.get(projectId);
        List<Opportunity> opportunityList = projectById.Opportunities__r;

        if (opportunityList == null || opportunityList.isEmpty()) {
            return; // No opportunity, skip this project
        }

        for (Opportunity opp : opportunityList) {
            opportunityIdSet.add(opp.Id);
        }

        Map<Id, Decimal> remainingAmountMapByOppId = OpportunityPaymentService.getInstance().findOpportunityPaymentRemainingAmountMap(opportunityIdSet);
        Map<Id, String> recurringOpportunityTextMapByFieldset = OpportunityService.getInstance().getOpportunityTextMapByFieldset(opportunityList);

        for (Opportunity opp : opportunityList) {
            String remainingAmountText = String.valueOf(remainingAmountMapByOppId.get(opp.Id));
            String recurringText = recurringOpportunityTextMapByFieldset.get(opp.Id);
            contentRecurring += recurringText + remainingAmountText + '\n';
        }

        if (!String.isBlank(contentRecurring)) {
            ContentVersion conVer = new ContentVersion();
            conVer.Origin = 'H';
            conVer.PathOnClient = 'RecurringSummary.txt';
            conVer.Title = 'Recurring Summary';
            conVer.VersionData = Blob.valueOf(contentRecurring);
            contentVersionToCreate.add(conVer);
        }

        if (!contentVersionToCreate.isEmpty()) {
            List<Database.SaveResult> resultContentVersion = ContentVersionService.getInstance().insertContentVersions(contentVersionToCreate);
            Set<Id> cvIdSet = new Set<Id>();

            for (Database.SaveResult sr : resultContentVersion) {
                if (sr.isSuccess()) {
                    cvIdSet.add((Id) sr.getId());
                } else {
                    continue; // Skip this one, already handled in log
                }
            }

            if (!cvIdSet.isEmpty()) {
                List<ContentVersion> contentVersions = ContentVersionSelector.getInstance().getByIdSetNoVersionData(cvIdSet);
                List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();

                for (ContentVersion contentVersion : contentVersions) {
                    contentDocumentLinks.add(
                        new ContentDocumentLink(
                            LinkedEntityId = projectId,
                            ContentDocumentId = contentVersion.ContentDocumentId,
                            ShareType = 'V',
                            Visibility = 'AllUsers'
                        )
                    );
                }

                ContentDocumentLinkService.getInstance().insertContentDocumentLinks(contentDocumentLinks);
            }
        }
    }
}