force-app/main/default/objects/Contact/fields/IsDummy__c.field-meta.xml
<CustomField>
    <fullName>IsDummy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dummy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ floor นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <description>เทียบเท่ากับ DueDate__c ของ OpportunityPayment__c ในรอบนั้นๆ</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No.</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLIT-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>OpportunityPayment__r.Term__c</formula>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DoNotSendInvoice__c.field-meta.xml
<CustomField>
    <fullName>DoNotSendInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ใช้เพื่อบอกว่า Opportunity นี้จะส่ง Invoice ให้ลูกค้าหรือไม่
ถ้า field นี้ เป็น True จะไม่มีการ Generate เอกสาร Invoice
ถ้า field นี้ เป็น False จะมีการ Generate เอกสาร Invoice และส่ง email ไปให้ลูกค้า
แต่ไม่ว่า field นี้จะเป็น True หรือ Fales จะมีการสร้าง record ที่ Object Invoice เสมอ</description>
    <label>Do Not Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Floor__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>UnitType__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/PromotionMaster__c.object-meta.xml
<CustomObject>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionMaster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Project ใด</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion ที่ผูกกับ unit</description>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromotionMaster__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion นี้ถูกใช้ใน Unit Type ใด</description>
    <label>Unit Type</label>
    <referenceTo>UnitType__c</referenceTo>
    <relationshipLabel>Promotion Master</relationshipLabel>
    <relationshipName>Promotion_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceBatchTest.cls
@isTest
public with sharing class CreateInvoiceBatchTest {
	@TestSetup
	static void makeData(){
		DataMaker dataMaker = DataMaker.getInstance();
		// Create Project
		Project__c testProject = dataMaker.createProject('Test Project', 'AA01', 'CD');
		insert testProject;
		// Craete Floor
		Floor__c testFloor = dataMaker.createFloor('Test Floor', 'FF01', testProject.Id);
		insert testFloor;
		// Create Unit Type
		UnitType__c unitType = dataMaker.createUnitType('Test Unit Type', testProject.Id);
		insert unitType;
		// Create Unit
		Product2 unit1 = dataMaker.createUnit(
			'Test Product',
			'PP01',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		Product2 unit2 = dataMaker.createUnit(
			'Test Product 2',
			'PP02',
			testProject.Id,
			testFloor.Id,
			'Available',
			unitType.Id
		);
		insert new List<Product2>{ unit1, unit2 };
		// Create Promotion Master
		PromotionMaster__c promotionMaster = dataMaker.craeteActivePromotionMaster(testProject.Id,unit1.Id,'ส่วนลด','Sales','Discount (ส่วนลด)','Add Detail','Description',500.00);
		insert promotionMaster;
		// Create Account
		Id recordTypeId = Schema.getGlobalDescribe()
			.get('Account')
			.getDescribe()
			.getRecordTypeInfosByName()
			.get('Co-Owner - Corporate')
			.getRecordTypeId();
		Account account = dataMaker.createAccount(recordTypeId, 'United Oil & Gas Corp.');
		insert account;
		// Create Opportunity
		OpportunityTriggerHandler oppTriggerHandler = OpportunityTriggerHandler.getInstance();
		oppTriggerHandler.setBypass();

		Opportunity opportunity1 = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.newInstance(2024, 10, 1),
			'Open',
			unit1.Id,
			'Foreign',
			null,
			testProject.Id
		);
		Opportunity opportunity2 = dataMaker.createOpportunity(
			account.Id,
			'Omitted',
			'Test Opp',
			Date.newInstance(2024, 10, 1),
			'Open',
			unit2.Id,
			'Foreign',
			null,
			testProject.Id
		);
		opportunity2.DoNotSendInvoice__c = true;
		insert new List<Opportunity> { opportunity1, opportunity2 };

		oppTriggerHandler.clearBypass();

		// Create Opp Payments
		// opportunity 1
		OpportunityPayment__c reservationOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opportunity1.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opportunity1.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 27),
			2
		);
		OpportunityPayment__c installmentOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opportunity1.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 27),
			3
		);
		OpportunityPayment__c transferOppPaymentOpp1 = dataMaker.createOpportunityPayment(
			opportunity1.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 27),
			4
		);

		// opportunity 2
		OpportunityPayment__c reservationOppPaymentOpp2 = dataMaker.createOpportunityPayment(
			opportunity2.Id,
			'Reservation',
			50000,
			Date.newInstance(2024, 10, 15),
			1
		);
		OpportunityPayment__c contractOppPaymentOpp2 = dataMaker.createOpportunityPayment(
			opportunity2.Id,
			'Contract',
			100000,
			Date.newInstance(2024, 10, 25),
			2
		);
		OpportunityPayment__c installmentOppPaymentOpp2 = dataMaker.createOpportunityPayment(
			opportunity2.Id,
			'Installment 1',
			10000000,
			Date.newInstance(2024, 10, 25),
			3
		);
		OpportunityPayment__c transferOppPaymentOpp2 = dataMaker.createOpportunityPayment(
			opportunity2.Id,
			'Transfer',
			4850000,
			Date.newInstance(2025, 10, 25),
			4
		);

		// all oppPayments
		List<OpportunityPayment__c> oppPayments = new List<OpportunityPayment__c>{
			reservationOppPaymentOpp1,
			contractOppPaymentOpp1,
			installmentOppPaymentOpp1,
			transferOppPaymentOpp1,
			reservationOppPaymentOpp2,
			contractOppPaymentOpp2,
			installmentOppPaymentOpp2,
			transferOppPaymentOpp2
		};
		insert oppPayments;

		NameFormattingMasterData__c invoiceFormatObject = dataMaker.createNameFormattingMasterData(
			'Invoice__c', 'Format', 'Object', 'IV-{Opportunity__r.Project__r.ProjectCode__c}{InvoiceDate__c:FORMATDATE:yyMM}{RUNNINGNUMBER:000}', 1, null
		);

		NameFormattingMasterData__c invoiceFormatDocument = dataMaker.createNameFormattingMasterData(
			'Invoice__c', 'Format', 'Document', '{InvoiceNo__c}', 1, 'Invoice'
		);

		NameFormattingMasterData__c paymentFormatDocument = dataMaker.createNameFormattingMasterData(
			'Opportunity', 'Format', 'Document', 'Payment Summary-{Project__r.ProjectCode__c}-{Unit__r.ProductCode}', 1, 'Payment Summary'
		);

		insert new List<NameFormattingMasterData__c>{invoiceFormatObject, invoiceFormatDocument, paymentFormatDocument};

		insert dataMaker.createInvoiceSetting();

		Account dummyAccount = dataMaker.createAccount(recordTypeId, 'Dummy Accouny');
		insert dummyAccount;
		Contact dummyContact = dataMaker.createContact(dummyAccount.Id, 'Dummy', 'Contact', 'dummyContact@dummy.com', '0111111111');
		dummyContact.IsDummy__c = true;
		insert dummyContact;
	}

	@isTest
	static void batchTodayTest(){
		Test.startTest();
		CreateInvoiceBatch createInvoiceBatch = new CreateInvoiceBatch();
		Database.executeBatch(createInvoiceBatch);
		Test.stopTest();

		Date dueDate = createInvoiceBatch.dueDate;
		Date invoiceDate = createInvoiceBatch.invoiceDate;

		List<OpportunityPayment__c> oppPayments = [SELECT Id, Opportunity__c, Term__c, DueDate__c, Amount__c, Remaining__c, PaymentStatus__c
			FROM OpportunityPayment__c
			WHERE Remaining__c > 0
			   AND IsMasterData__c = true
			   AND DueDate__c = :dueDate
			AND Opportunity__r.StageName != 'Closed Lost'
			ORDER BY Opportunity__c
		];

		Set<Id> oppIdSet = new Set<Id>();
		for (OpportunityPayment__c oppPayment : oppPayments) {
			oppIdSet.add(oppPayment.Opportunity__c);
		}

		List<Invoice__c> invoiceResults = [SELECT Id, InvoiceNo__c, Opportunity__r.Project__r.ProjectCode__c FROM Invoice__c];
		List<InvoiceLineItem__c> invoiceLineResults = [SELECT Id FROM InvoiceLineItem__c];
		System.assertEquals(oppIdSet.size(), invoiceResults.size());
		System.assertEquals(oppPayments.size(), invoiceLineResults.size());

		DateTime invoiceDT = DateTime.newInstance(invoiceDate.year(), invoiceDate.month(), invoiceDate.day());
		Integer index = 1;
		for (Invoice__c invoiceResult : invoiceResults) {
			String expectedInvNo = 'IV-' + invoiceResult.Opportunity__r.Project__r.ProjectCode__c + invoiceDT.format('yyMM') + '000'.left(3 - String.valueOf(index).length()) + index;
			System.assertEquals(expectedInvNo, invoiceResult.InvoiceNo__c);

			index++;
		}
	}

	@isTest
	static void batchSpecificDateTest(){
		Test.startTest();
		CreateInvoiceBatch createInvoiceBatch = new CreateInvoiceBatch(Date.newInstance(2024, 10, 20));
		Database.executeBatch(createInvoiceBatch);
		Test.stopTest();

		Date dueDate = createInvoiceBatch.dueDate;
		Date invoiceDate = createInvoiceBatch.invoiceDate;

		List<OpportunityPayment__c> oppPayments = [SELECT Id, Opportunity__c, Term__c, DueDate__c, Amount__c, Remaining__c, PaymentStatus__c
			FROM OpportunityPayment__c
			WHERE Remaining__c > 0
			   AND IsMasterData__c = true
			   AND DueDate__c = :dueDate
			AND Opportunity__r.StageName != 'Closed Lost'
			ORDER BY Opportunity__c
		];

		Set<Id> oppIdSet = new Set<Id>();
		for (OpportunityPayment__c oppPayment : oppPayments) {
			oppIdSet.add(oppPayment.Opportunity__c);
		}

		List<Invoice__c> invoiceResults = [SELECT Id, InvoiceNo__c, Opportunity__r.Project__r.ProjectCode__c FROM Invoice__c];
		List<InvoiceLineItem__c> invoiceLineResults = [SELECT Id FROM InvoiceLineItem__c];
		System.assertEquals(oppIdSet.size(), invoiceResults.size());
		System.assertEquals(oppPayments.size(), invoiceLineResults.size());

		DateTime invoiceDT = DateTime.newInstance(invoiceDate.year(), invoiceDate.month(), invoiceDate.day());
		Integer index = 1;
		for (Invoice__c invoiceResult : invoiceResults) {
			String expectedInvNo = 'IV-' + invoiceResult.Opportunity__r.Project__r.ProjectCode__c + invoiceDT.format('yyMM') + '000'.left(3 - String.valueOf(index).length()) + index;
			System.assertEquals(expectedInvNo, invoiceResult.InvoiceNo__c);

			index++;
		}
	}
}