force-app/main/default/objects/RoundRobinAssignment__c/RoundRobinAssignment__c.object-meta.xml
<CustomObject>
    <label>Round Robin Assignment</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Round Robin Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoundRobinAssignment__c/fields/LastAssignedUser__c.field-meta.xml
<CustomField>
    <fullName>LastAssignedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store last assigned user in each Queue</description>
    <label>Last Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RoundRobinAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoundRobinAssignment__c/fields/QueueName__c.field-meta.xml
<CustomField>
    <fullName>QueueName__c</fullName>
    <description>Store Queue name which own Lead assigning to each member in Queue</description>
    <label>Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoundRobinAssignment__c/fields/TargetObject__c.field-meta.xml
<CustomField>
    <fullName>TargetObject__c</fullName>
    <description>Store Object API which is assigned</description>
    <label>Target Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoundRobinAssignmentSelector.cls
public with sharing class RoundRobinAssignmentSelector {
    public static RoundRobinAssignmentSelector instance;

    public RoundRobinAssignmentSelector() {
    }

    public static RoundRobinAssignmentSelector getInstance() {
        if (instance == null) {
            instance = new RoundRobinAssignmentSelector();
        }
        return instance;
    }

    // get Round Robin Assignment for Lead object map by Queue name
    public Map<String, RoundRobinAssignment__c> getLeadRoundRobinAssignmentMapByQueueName(Set<String> queueNames) {
        Map<String, RoundRobinAssignment__c> rrAssignmentMapByQueueName = new Map<String, RoundRobinAssignment__c>();
        List<RoundRobinAssignment__c> rrAssignments = [
            SELECT Id, QueueName__c, LastAssignedUser__c, TargetObject__c
            FROM RoundRobinAssignment__c
            WHERE QueueName__c IN :queueNames AND TargetObject__c = 'Lead'
        ];
        for (RoundRobinAssignment__c rrAssignment : rrAssignments) {
            rrAssignmentMapByQueueName.put(rrAssignment.QueueName__c, rrAssignment);
        }
        return rrAssignmentMapByQueueName;
    }
}