force-app/main/default/objects/CoBuyer__c/CoBuyer__c.object-meta.xml
<CustomObject>
    <label>Co-Buyer</label>
    <nameField>
        <displayFormat>COB-{000000}</displayFormat>
        <label>Co-Buyer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Buyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CoBuyer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Relationship field with opportunity</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Transferred, Closed Won, Closed Lost</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Co-Buyers</relationshipLabel>
    <relationshipName>Co_Borrowers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CoBuyerService.cls
public with sharing class CoBuyerService {
    public static CoBuyerService instance;
    public static CoBuyerService getInstance(){
        if (instance == null){
            instance = new CoBuyerService();
        }
        return instance;
    }

    public List<Opportunity> stampOppCoBuyerNameAndFlag(List<CoBuyer__c> coBuyers){
        OpportunityService oppService = OpportunityService.getInstance();
        List<CoBuyer__c> testCoBuyers = [SELECT Id FROM CoBuyer__c];

        OpportunitySelector oppSelector = OpportunitySelector.getInstance();
        Set<Id> oppIds = new Set<Id>();
        for (CoBuyer__c coBuyer : coBuyers){
            oppIds.add(coBuyer.Opportunity__c);
        }
        Map<Id, Opportunity> oppMapById = oppSelector.getOpportunityWithCoBuyerMapById(oppIds);
        List<Opportunity> opportunities = oppMapById.values();
        List<Opportunity> updatedOpportunities = oppService.stampCoBuyerName(opportunities);
        update updatedOpportunities;
        return updatedOpportunities;
    }
}