force-app/main/default/objects/CoBuyer__c/CoBuyer__c.object-meta.xml
<CustomObject>
    <label>Co-Buyer</label>
    <nameField>
        <displayFormat>COB-{000000}</displayFormat>
        <label>Co-Buyer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Buyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/TriggerActivation__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to configure to acitvatate/deactivate trigger execution</description>
    <label>Trigger Activation</label>
    <pluralLabel>Trigger Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerActivation__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean to check to activate/deactivate Trigger</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CoBuyerTriggerHandler.cls
public with sharing class CoBuyerTriggerHandler {
    public CoBuyerTriggerHandler() {

    }
    public static CoBuyerTriggerHandler instance;
    public static CoBuyerTriggerHandler getInstance(){
        if (instance == null){
            instance = new CoBuyerTriggerHandler();
        }
        return instance;
    }

    public Boolean isActive = true;
    public List<CoBuyer__c> newRecords;
    public Map<Id, CoBuyer__c> oldMap;

    public Boolean isTriggerActivated() {
        if (TriggerActivation__mdt.getInstance('CoBuyerTrigger') != null) {
            return this.isActive && TriggerActivation__mdt.getInstance('CoBuyerTrigger').isActive__c;
        }
        return this.isActive;
    }
    public void setParams(List<CoBuyer__c> newRecords, Map<Id, CoBuyer__c> oldMap) {
        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }
    public void setBypass() {
        this.isActive = false;
    }

    public void clearBypass() {
        this.isActive = true;
    }

    public void executeAfterInsert() {
        this.stampOppCoBuyerNameAndFlag();
    }

    public void executeAfterUpdate() {
        this.stampOppCoBuyerNameAndFlag();
    }

    public void executeAfterDelete() {
        this.stampOppCoBuyerNameAndFlagAfterDelete();
    }

    private void stampOppCoBuyerNameAndFlag(){
        CoBuyerService service = CoBuyerService.getInstance();
        service.stampOppCoBuyerNameAndFlag(this.newRecords);
    }

    private void stampOppCoBuyerNameAndFlagAfterDelete(){
        CoBuyerService service = CoBuyerService.getInstance();
        List<CoBuyer__c> coBuyers = this.oldMap.values();
        service.stampOppCoBuyerNameAndFlag(coBuyers);
    }
}