force-app/main/default/objects/InvoiceSetting__c/InvoiceSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom settings for control invoice</description>
    <label>Invoice Setting</label>
</CustomObject>

force-app/main/default/objects/InvoiceSetting__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/IsMasterData__c.field-meta.xml
<CustomField>
    <fullName>IsMasterData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>เพื่อบอกว่า Record นี้ เป็นค่าตั้งต้นใน Opportunity Payment</description>
    <label>Is Master Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Payments</relationshipLabel>
    <relationshipName>Opportunity_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <formula>IF(
  Remaining__c == 0,
  &quot;Fully Paid&quot;,
  IF(
    AND(DueDate__c &lt; TODAY(), ISBLANK(ReceivedAmount__c)),
    &quot;Overdue&quot;,
    IF(
      ReceivedAmount__c &gt; 0,
      &quot;Partially Paid&quot;,
      &quot;&quot;
    )
  )
)</formula>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Remaining__c.field-meta.xml
<CustomField>
    <fullName>Remaining__c</fullName>
    <formula>if(ISNULL(ReceivedAmount__c),
   Amount__c ,
   Amount__c -  ReceivedAmount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceBatch.cls
public with sharing class CreateInvoiceBatch implements Database.Batchable<sObject> {
    @TestVisible
    private Date invoiceDate;

    @TestVisible
    private Date dueDate;

    public CreateInvoiceBatch() {
        setDueDate(System.today());
		setInvoiceDate(System.today());
    }

    public CreateInvoiceBatch(Date runBatchDate) {
        setDueDate(runBatchDate);
		setInvoiceDate(runBatchDate);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> queryStringList = new List<String> {
            'SELECT Id, Opportunity__c, Term__c, DueDate__c, Amount__c, Remaining__c, PaymentStatus__c',
            'FROM OpportunityPayment__c',
            'WHERE Remaining__c > 0',
            '   AND IsMasterData__c = true' +
            '   AND DueDate__c = ' + String.valueOf(dueDate),
			'	AND Opportunity__r.StageName != \'Closed Lost\'',
            'ORDER BY Opportunity__c'
        };

        String queryString = String.join(queryStringList, ' ');

        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext BC, List<OpportunityPayment__c> oppPayments) {
        InvoiceService.getInstance().insertInvoiceAndRelatedRecords(oppPayments, dueDate, invoiceDate);
    }

    public void finish(Database.BatchableContext BC) {
		Database.executeBatch(new CreateRelatedInvFilesAndSendEmailBatch(dueDate), 50);
    }

    private void setDueDate(Date runBatchDate){
        dueDate = runBatchDate.addDays(Integer.valueOf(InvoiceSetting__c.getInstance().DueDate__c));
    }

    private void setInvoiceDate(Date runBatchDate){
        invoiceDate = runBatchDate;
    }
}