force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BankName</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BankService.cls
public with sharing class BankService {
	public static BankService instance;
	public static BankService getInstance() {
		if (instance == null) {
			instance = new BankService();
		}
		return instance;
	}

	public final String OBJECT_API_NAME = 'Bank__c';

	public Map<String, String> getBankNameLabelMapByValue() {
		Map<String, String> bankNameLabelMapByValue = new Map<String, String>();

		List<Schema.PicklistEntry> pickListValues = PicklistValueUtility.getInstance().getPicklistEntries(OBJECT_API_NAME, 'BankName__c');
		for (Schema.PicklistEntry pickListValue : pickListValues) {
			bankNameLabelMapByValue.put(pickListValue.getValue(), pickListValue.getLabel());
		}
		return bankNameLabelMapByValue;
	}
}