force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <formula>Text(BankName__c) + &quot; (&quot; +  BankAccountNumber__c +  &quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Bank</relationshipLabel>
    <relationshipName>Bank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MakeAPaymentConfig__mdt/MakeAPaymentConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuring information to be displayed when the &apos;Make a Payment&apos; button is pressed on the Opportunity, ensuring that relevant payment details are shown on the screen.</description>
    <label>Make a Payment Config</label>
    <pluralLabel>Make a Payment Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPayment__c/OpportunityPayment__c.object-meta.xml
<CustomObject>
    <label>Opportunity Payment</label>
    <nameField>
        <label>Opportunity Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceiptLineItem__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceiptLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt Line Item</label>
    <referenceTo>PaymentReceiptLineItem__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Receipt</relationshipLabel>
    <relationshipName>Payment_Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/recordTypes/PaymentReceipt.recordType-meta.xml
<RecordType>
    <fullName>PaymentReceipt</fullName>
    <active>true</active>
    <label>Payment Receipt</label>
</RecordType>

force-app/main/default/objects/PaymentReceiptLineItem__c/PaymentReceiptLineItem__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt Line Item</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Payment Receipt Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/OpportunityPayment__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Payment</label>
    <referenceTo>OpportunityPayment__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>Payment_Receipt_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>PaymentMethod__c</referenceTo>
    <relationshipLabel>Payment Receipt Line Item</relationshipLabel>
    <relationshipName>PaymentReceiptLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentReceiptLineItem__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <description>การชำระเงินนี้อยู่ใต้ใบเสร็จใด</description>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProceedPaymentController.cls
public with sharing class ProceedPaymentController {

    @AuraEnabled(cacheable=true)
    public static List<MakeAPaymentConfig__mdt> getMakeAPaymentConfig() {
        try{
            List<MakeAPaymentConfig__mdt> configs;
            Map<String,MakeAPaymentConfig__mdt> configMapByName = MakeAPaymentConfig__mdt.getAll();
            configs = configMapByName != null ? configMapByName.values() : new List<MakeAPaymentConfig__mdt>();
            return configs;
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<ComboboxModel> getPicklistValues(String objectName, String fieldName) {
        List<ComboboxModel> values = new List<ComboboxModel>{};
        PicklistValueUtility utility = PicklistValueUtility.getInstance();
        try {
            values = utility.getPicklistComboboxes(objectName, fieldName);
            return values;
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

	@AuraEnabled(cacheable=true)
	public static List<ComboboxModel> getCompanyBanks(Id opportunityId){
		try {
			List<ComboboxModel> comboboxes = new List<ComboboxModel>();
			OpportunitySelector oppSelector = OpportunitySelector.getInstance();
			ProjectSelector projectSelector = ProjectSelector.getInstance();
			Opportunity targetOpportunity = oppSelector.getById(opportunityId);
			Id proojectId = targetOpportunity.Project__c;
			Map<Id, Project__c> projectWithActiveCompanyBankMapById = projectSelector.getProjectWithActiveCompanyBankMapById(new Set<Id>{proojectId});
			Project__c targetProject = projectWithActiveCompanyBankMapById.get(proojectId);
			List<Bank__c> banks = targetProject.Bank__r == null ? new List<Bank__c>() : targetProject.Bank__r;
			for (Bank__c bank : banks){
				comboboxes.add(new ComboboxModel(bank.DisplayName__c, bank.Id , bank.IsDefault__c));
			}
			return comboboxes;
		} catch (Exception e) {
			System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
		}
	}

    @AuraEnabled
    public static Map<String,List<SObject>> proceedPayment(Id opportunityId, Decimal recievedAmount, List<PaymentMethod__c> paymentMethods , Id receiptId) {
        Savepoint sp = Database.setSavepoint();
        try{
            Map<String,List<SObject>> resultMap = new Map<String,List<SObject>>();
            OpportunityPaymentSelector oppPaymentSelector = OpportunityPaymentSelector.getInstance();
            OpportunityPaymentService oppPaymentService = OpportunityPaymentService.getInstance();
            PaymentReceiptService paymentReceiptService = PaymentReceiptService.getInstance();
            InvoiceService invoiceService = InvoiceService.getInstance();
            Map<Id, List<OpportunityPayment__c>> opportunityPaymentMapByOppId = oppPaymentSelector.getOpportunityPaymentsWithInvoiceLineItemMapByOppId(
                new Set<Id>{opportunityId}
            );
            List<OpportunityPayment__c> oppPayments = opportunityPaymentMapByOppId.get(opportunityId);
            if (receiptId == null){
                PaymentReceipt__c paymentReceipt = paymentReceiptService.generatePaymentReceiptRelatedToOpportunity(opportunityId);
                insert paymentReceipt;
                PaymentReceipt__c paymentReceiptWithRunningNo = paymentReceiptService.generateRunningNo(paymentReceipt);
                update paymentReceiptWithRunningNo;
                receiptId = paymentReceiptWithRunningNo.Id;
                resultMap.put('PaymentReceipt__c' , new List<PaymentReceipt__c>{paymentReceiptWithRunningNo});
            }
            for (PaymentMethod__c paymentMethod : paymentMethods){
                paymentMethod.PaymentReceipt__c = receiptId;
            }
            insert paymentMethods;
            resultMap.put('PaymentMethod__c', paymentMethods);
            List<PaymentReceiptLineItem__c> paymentReceiptLineItems = paymentReceiptService.generatePaymentReceiptLineItemFromTotalReceivedAmount(recievedAmount,oppPayments,receiptId,paymentMethods[0].Id);
            insert paymentReceiptLineItems;
            List<OpportunityPayment__c> updatedOppPayments = oppPaymentService.stampFieldFromReceiptLineItem(paymentReceiptLineItems);
            update updatedOppPayments;
            return resultMap;
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
}