force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <label>Bank Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/BankAddress__c.field-meta.xml
<CustomField>
    <fullName>BankAddress__c</fullName>
    <label>Bank Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/BankBranch__c.field-meta.xml
<CustomField>
    <fullName>BankBranch__c</fullName>
    <label>Bank Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BankName</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <formula>Text(BankName__c) + &quot; (&quot; +  BankAccountNumber__c +  &quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/IsUsedInPaymentGateway__c.field-meta.xml
<CustomField>
    <fullName>IsUsedInPaymentGateway__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Used In Payment Gateway</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Bank</relationshipLabel>
    <relationshipName>Bank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/SWIFTCode__c.field-meta.xml
<CustomField>
    <fullName>SWIFTCode__c</fullName>
    <label>SWIFT Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankBranch__c/BankBranch__c.object-meta.xml
<CustomObject>
    <label>Bank Branch</label>
    <nameField>
        <label>Bank Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankBranch__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่่อธนาคาร</description>
    <label>Bank Name</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Branches</relationshipLabel>
    <relationshipName>BankBranches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <formula>Unit__r.AreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <formula>(  BLANKVALUE(UnitPrice__c, 0.00)  -( BLANKVALUE(UnitPrice__c, 0.00) *BLANKVALUE(TotalDiscountPercent__c, 0.00) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship กับ Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>Foreign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Product2.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>The original price before discounts. Get value from &apos;Pricebook2&apos;</description>
    <label>Unit Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnitPricePerSqm__c.field-meta.xml
<CustomField>
    <fullName>UnitPricePerSqm__c</fullName>
    <label>Unit Price/sq.m.</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Not for Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <formula>IF(
    ISPICKVAL( CompanyBankName__c , &quot;Bangkok Bank&quot;),
    &quot;123-456-7890&quot;,  /* เลขที่บัญชีของ Bangkok Bank */
    IF(
        ISPICKVAL(CompanyBankName__c , &quot;Bank of Ayudhya&quot;),
        &quot;987-654-3210&quot;,  /* เลขที่บัญชีของ Bank of Ayudhya */
    IF(
        ISPICKVAL(CompanyBankName__c , &quot;Kasikorn Bank&quot;),
        &quot;987-654-3210&quot;,  /* เลขที่บัญชีของ Kasikorn Bank */
    IF(
        ISPICKVAL(CompanyBankName__c , &quot;Krungthai Bank&quot;),
        &quot;987-654-3210&quot;,  /* เลขที่บัญชีของ Krungthai Bank */
        IF(
            ISPICKVAL(CompanyBankName__c , &quot;Siam Commercial Bank&quot;),
            &quot;555-444-3330&quot;,  /* เลขที่บัญชีของ Siam Commercial Bank */
            &quot;Please specify Company Bank Name&quot;
        )
    )
)))</formula>
    <label>Bank Account Number for Invoice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/BankAddress__c.field-meta.xml
<CustomField>
    <fullName>BankAddress__c</fullName>
    <label>Bank Address for Invoice</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/BankBranch__c.field-meta.xml
<CustomField>
    <fullName>BankBranch__c</fullName>
    <label>Bank Branch for Invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <description>Date on which Project is finished or completed.</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <description>รหัส Project</description>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectLogo__c.field-meta.xml
<CustomField>
    <fullName>ProjectLogo__c</fullName>
    <label>Project Logo</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>สถานะของ Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SWIFTCode__c.field-meta.xml
<CustomField>
    <fullName>SWIFTCode__c</fullName>
    <label>SWIFT Code for Invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit (Waiting Del)</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Waiting Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/AreaSqm__c.field-meta.xml
<CustomField>
    <fullName>AreaSqm__c</fullName>
    <description>พื้นที่ของห้อง</description>
    <label>Area (Sq.m.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่อ Project ที่ Unit นี้อยู่</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <formula>Project__r.ProjectCode__c</formula>
    <label>Project Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <description>Tower</description>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UnitType__c/UnitType__c.object-meta.xml
<CustomObject>
    <label>Unit Type</label>
    <nameField>
        <label>UnitType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitType__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit Type</relationshipLabel>
    <relationshipName>Unit_Type</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectSelector.cls
public without sharing class ProjectSelector {
	public ProjectSelector() {
	}
	public static ProjectSelector instance;
	public static ProjectSelector getInstance() {
		if (instance == null) {
			instance = new ProjectSelector();
		}
		return instance;
	}
	/**
	 * Phase2
	 * Details:
	 * - Select more fields
	 * 		- NovationFee__c
	 */
	public Map<Id, Project__c> getProjectById(Set<Id> projectIds) {
		Map<Id, Project__c> projectMap = new Map<Id, Project__c>();
		List<Project__c> projectRecords = [
			SELECT Id, Name, CompletionDate__c, ProjectLogo__c,NovationFee__c,Tower__c,ProjectLogoPublicURL__c
			FROM Project__c
			WHERE Id IN :projectIds
		];
		for (Project__c project : projectRecords) {
			projectMap.put(project.Id, project);
		}
		return projectMap;
	}

	public Map<String, Project__c> getProjectMapByProjectCode(Set<String> projectCodes) {
		Map<String, Project__c> projectMapByProjectCode = new Map<String, Project__c>();
		List<Project__c> projects = [
			SELECT Id, Name, CompletionDate__c, ProjectLogo__c, ProjectCode__c
			FROM Project__c
			WHERE ProjectCode__c IN :projectCodes
		];
		for (Project__c project : projects) {
			projectMapByProjectCode.put(project.ProjectCode__c, project);
		}
		return projectMapByProjectCode;
	}

	public Map<Id, Project__c> getProjectWithActiveCompanyBankMapById(Set<Id> projectsId) {
		return new Map<Id, Project__c>(
			[
				SELECT
					Id,
					Name,
					CompletionDate__c,
					ProjectLogo__c,
					ProjectCode__c,
					(
						SELECT
							Id,
							BankAccountNumber__c,
							BankName__c,
							BankBranch__c,
							BankAddress__c,
							SWIFTCode__c,
							Project__c,
							DisplayName__c,
							IsActive__c,
							IsDefault__c,
							IsUsedInPaymentGateway__c
						FROM Bank__r
						WHERE IsActive__c = TRUE
					)
				FROM Project__c
				WHERE Id IN :projectsId
			]
		);
	}

	/**
	 * Phase2
	 * Details:
	 * - Add method to query Project__c with related Unit__c
	 */
	public Map<Id, Project__c> getProjectWithForeignOppMapById(Set<Id> projectIds){
		return new Map<Id, Project__c>(
			[
				SELECT
					Id,
					Name,
					CompletionDate__c,
					ProjectLogo__c,
					ProjectCode__c,
					NovationFee__c,
					ForeignQuotaArea__c,
					(
						SELECT
							Id,
							Unit__r.AreaSqm__c,
							Unit__r.Status__c
						FROM Opportunities__r
						WHERE Quota__c = 'Foreign'
						AND
						(
							StageName !=: GlobalConstants.OPP_STAGENAME_CLOSED_LOST
						)
					)
				FROM Project__c
				WHERE Id IN :projectIds
			]
		);
	}
	/**
	 * Phase2
	 * Details:
	 * - Add method to query Project__c and Opportunity with related Unit__c
	 */
	public Map<Id, Project__c> getProjectWithOppMapById(Set<Id> projectIds){
		return new Map<Id, Project__c>(
			[
				SELECT
					Id,
					Name,
					CompletionDate__c,
					ProjectLogo__c,
					ProjectCode__c,
					NovationFee__c,
					ForeignQuotaArea__c,
					(
						SELECT
							Id,
							Name,
							NetPrice__c,
							UnitPrice__c,
							UnitPricePerSqm__c,
							NetPricePerSqm__c,
							AreaSqm__c,
							CoBuyerName__c,
							PaymentPortalToken__c,
							Account.Name,
							Account.Phone,
							Account.Email__c,
							Account.AccountCode__c,
							Account.AddressEN__c,
							Account.AddressTH__c,
							Account.TaxID__c,
							ContactPerson__c,
							ContactPerson__r.MobilePhone,
							ContactPerson__r.Email,
							Project__r.Name,
							Project__r.ProjectLogo__c,
							Project__r.CompanyName__c,
							Project__r.CompanyAddress__c,
							Project__r.CompanyPhone__c,
							Project__r.CompanyTaxID__c,
							Unit__r.Name,
							Unit__r.AreaSqm__c,
							Unit__r.UnitType__r.Name,
							NovationDate__c
						FROM Opportunities__r
					)
				FROM Project__c
				WHERE Id IN :projectIds
			]
		);
	}
}