force-app/main/default/objects/BankBranch__c/BankBranch__c.object-meta.xml
<CustomObject>
    <label>Bank Branch</label>
    <nameField>
        <label>Bank Branch Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankBranch__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>ชื่่อธนาคาร</description>
    <label>Bank Name</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Branches</relationshipLabel>
    <relationshipName>BankBranches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/PaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentMethod__c/fields/BankAccountNo__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNo__c</fullName>
    <label>Bank Account No.</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankBranch__c.field-meta.xml
<CustomField>
    <fullName>BankBranch__c</fullName>
    <inlineHelpText>For International Transfers, you can specify the branch as &apos;CREDIT ADVICE&apos;.</inlineHelpText>
    <label>Bank Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/BankDraftNo__c.field-meta.xml
<CustomField>
    <fullName>BankDraftNo__c</fullName>
    <label>Bank Draft No.</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/ChequeNo__c.field-meta.xml
<CustomField>
    <fullName>ChequeNo__c</fullName>
    <label>Cheque No</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/CreditCardNo__c.field-meta.xml
<CustomField>
    <fullName>CreditCardNo__c</fullName>
    <label>Credit Card No.</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/DebitCardNo__c.field-meta.xml
<CustomField>
    <fullName>DebitCardNo__c</fullName>
    <label>Debit Card No.</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/InternationalBankName__c.field-meta.xml
<CustomField>
    <fullName>InternationalBankName__c</fullName>
    <label>International Bank Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentReceipt__c.field-meta.xml
<CustomField>
    <fullName>PaymentReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Receipt</label>
    <referenceTo>PaymentReceipt__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>PaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentMethod__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/PaymentReceipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PAR-{000000}</displayFormat>
        <label>Payment Receipt REF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentReceipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentReceipt__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentReceipt__c/fields/ReceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>ReceivedAmount__c</fullName>
    <label>Received Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentMathodSelector.cls
public with sharing class PaymentMathodSelector {
	public static PaymentMathodSelector instance;
	public static PaymentMathodSelector getInstance() {
		if (instance == null) {
			instance = new PaymentMathodSelector();
		}
		return instance;
	}
	public PaymentMathodSelector() {

	}
	public Map<Id, List<PaymentMethod__c>> getPaymentMethodMapByPaymentReceiptId(Set<Id> paymentReceiptIds) {
		Map<Id, List<PaymentMethod__c>> paymentMethodMapByPaymentReceiptId = new Map<Id, List<PaymentMethod__c>>();
		List<PaymentMethod__c> paymentMethods = [
				SELECT
							Id,
							PaymentReceipt__c,
							PaymentType__c,
							ChequeNo__c,
							BankName__c,
							BankBranch__c,
							BankAccountNo__c,
							CreditCardNo__c,
							DebitCardNo__c,
							InternationalBankName__c,
							PaymentDate__c,
							BankDraftNo__c,
							ReceivedAmount__c
				FROM PaymentMethod__c
				WHERE PaymentReceipt__c IN :paymentReceiptIds
			];
			for (PaymentMethod__c paymentMethod : paymentMethods) {
				if (!paymentMethodMapByPaymentReceiptId.containsKey(paymentMethod.PaymentReceipt__c)) {
					paymentMethodMapByPaymentReceiptId.put(paymentMethod.PaymentReceipt__c, new List<PaymentMethod__c>());
				}
				paymentMethodMapByPaymentReceiptId.get(paymentMethod.PaymentReceipt__c).add(paymentMethod);
			}
			return paymentMethodMapByPaymentReceiptId;

}
}